### ISSUE TITLE
Save/load state shortcuts need 2 button presses on controller

### ISSUE THREAD

**Issue by Derolis** [mgba-emu/mgba#2214] opened 2021-06-12 02:58 UTC
Pretty easy to replicate if someone wants to see if it's just on my end or not, but I had Save and load recent state mapped to my thumbstick buttons on my Xbox 1 controller and I always need to press them twice for them to function. I have rewind and fast forward bound to the triggers and those function just fine. I tried swapping them around, and it doesn't matter what button I map them to, but it's specifically the save/load state shortcuts that seem to have this problem for me.

**Comment by endrift** [comment] 2021-06-12 03:05
Duplicate of #2143.

**Closed by endrift** 2021-06-12 03:05 UTC
