### ISSUE TITLE
Random crash whilst playing game.

### ISSUE THREAD

**Issue by Mario3264** [mgba-emu/mgba#1156] opened 2018-08-30 01:28 UTC
I was playing Mario & Luigi - Superstar Saga and it randomly crashed at the point where you find Fawful the second time. I can't seem to reproduce it again, unfortunately.
System Information:
mGBA version: 0.7-5203-2c6715d7
OS: Windows 10 Professional Insider Preview (Build 18219)
CPU and GPU: Intel Core i3-4160 @ 3.60 GHz; Intel HD Graphics 4400

**Comment by endrift** [comment] 2018-08-30 01:29
Dupe of #1059. (Sorry, I want to fix it, but I haven't been able to reproduce it yet.)

**Closed by endrift** 2018-08-30 01:29 UTC
