### ISSUE TITLE
Crash when saving Game Overrides.

### ISSUE THREAD

**Issue by SuperFlomm** [mgba-emu/mgba#427] opened 2016-10-04 19:57 UTC
Open **Tools -> Game overrides** and click save. mGBA should now crash.

**Comment by endrift** [comment] 2016-10-04 19:58
This was reported ages ago and I've never been able to reproduce it. I'll need much more information about your setup.

**Comment by SuperFlomm** [comment] 2016-10-04 20:06
Sure, just tell me what information you need.

**OS:** Windows 10
**mGBA versions tested:** 0.5.0 and 0a791a2
and it only crashes if Autodetect is selected.

When I select anything but Autodetect and save it doesn't crash. But when I then close the Game Overrides window and open it again, the setting is back to Autodetect.

**Comment by endrift** [comment] 2016-10-04 20:07
Do you have a game running when you do this?

**Comment by SuperFlomm** [comment] 2016-10-04 20:09
I don't have a game running. In fact I can't even change any of these settings while a game is running. Everything is grayed out and saving does nothing.

**Comment by endrift** [comment] 2016-10-04 20:11
The intended workflow is to set the overrides, load a game, and then save. The override screen is for changing what the next game that's loaded has for some in-game bits. Save saves it to the configuration file, not a separate selectable file, so there's no feedback that it's saved. Furthermore, if you try to save it while there isn't a game loaded, it doesn't know what game the override should apply to, so it can't do anything useful.

**Comment by endrift** [comment] 2016-10-04 20:12
Fixed in 742538dc432a3d85b66318eded435a73dfce0f5c, btw.

**Closed by endrift** 2016-10-04 20:12 UTC
