### ISSUE TITLE
Colors are inaccurate

### ISSUE THREAD

**Issue by Snodeca** [mgba-emu/mgba#2782] opened 2023-01-11 23:39 UTC
I've been messing around with the color palettes of Mario & Luigi: Superstar Saga, but as I've been working with it it's come to my attention that the colors that are displayed on mGBA, though extremely minor, are inaccurate, or at least this game has inaccurate color.

The game works with 15-bit color coding. This means that, accurately, 0x043F (a very red color) should be #F80808. This is Mario's main color in the aforementioned game. If I, however, take a screenshot of mGBA itself (such as in the example attached), the bright part of Mario's hat is the color #FF0808. Or Luigi's arm, bright green, 15-but 0x03A3, is supposed to have a color of #18E800 but it is instead #18EF00.

There are bits in the 24-bit color code (the one that everyone and everything uses) that are completely useless when converting to 15-bit. The first 3 bits of each color (Red, Blue, Green) should be 0 in 24-bit when it is converting from 15-bit, but this is for some reason not the case. Only bits 4 to 8 should be used.

...I hope this made sense. Either way, this extremely minor issue that the naked eye can't see is causing me inconveniences because I have to use a workaround to check new colors or whatever lol. Last sentence is unimportant, just me ranting.
![MLRedGreenbits](https://user-images.githubusercontent.com/52331547/211941186-60bd9428-a3dd-4a8c-aae7-4698e428bf83.png)

**Comment by endrift** [comment] 2023-01-11 23:41
Duplicate of #2193. Saying what's the "correct" way of representing a lower bit-depth color in a higher bit-depth is not as cut and dry as you seem to think it is.

**Comment by Snodeca** [comment] 2023-01-11 23:41
Didn't spot it while looking at the issues, sorry.

**Closed by endrift** 2023-01-11 23:41 UTC
