### ISSUE TITLE
Fast Forward not adjusting to speeds using OpenGL

### ISSUE THREAD

**Issue by nostringyoyo** [mgba-emu/mgba#1936] opened 2020-11-09 07:00 UTC
I have fast forward on toggle (Space) and different speeds bound on my number bar, 1 = unbounded, 2 = 2x speed, 3 = 3x speed, etc.

Display Driver is set to OpenGL. With FF toggled on, it only runs at 2x or unbounded. Changing speed to 3x and higher does not change the speed at which the game is running (it still runs at 2x unless I change to unbounded). This is both when changing it manually in settings and using key-binds.

Syncing to either Video, Audio or both enabled does not fix the issue.

The issue goes away when Display Driver is set to Software. 

Issue persists on both dev build and 0.8.4 on Windows 10.

**Comment by endrift** [comment] 2020-11-09 07:01
Are you using the OpenGL Enhancement renderer too?

**Comment by nostringyoyo** [comment] 2020-11-09 07:06
Yes it's set to OpenGL under Enhancements.

**Comment by endrift** [comment] 2020-11-09 07:08
What's your GPU and what's scale set to?

**Comment by nostringyoyo** [comment] 2020-11-09 07:09
High-res scale set to 2x. Using a GTX 1080 FE.

**Comment by endrift** [comment] 2020-11-28 00:11
I can confirm at least some amount of this bug. On my 144 Hz monitor, bounded fast forward seems to max out at 144 Hz.

**Comment by endrift** [comment] 2020-11-28 03:48
Fixed as of fc3e47a4bab1465b91e7368c6396b222f65f51cb, but add-on fixes were needed for other things, and it still seems to be having issues on AMD.

**Closed by endrift** 2020-11-28 03:48 UTC
