### ISSUE TITLE
AGS Aging Cartridge fails on 0.11-8213-f2186f6a5 and older

### ISSUE THREAD

**Issue by randomsomeone69** [mgba-emu/mgba#3016] opened 2023-08-28 22:07 UTC
Specs : Intel Core i5-10400F, nVidia GTX 1050 Ti
OS : Windows 10 22H2

So, to test the "accuracy" of emulators, I put a file called "AGB_CHECKER" more commonly called as AGS Aging Cartridge, which is a cartridge who test the Game Boy Advance for testing hardware.

On all of the test, it succeed except one. 

Here's the log showed after the tests finished :

![AGB_CHECKER v9 0 (TCHK30)-0](https://github.com/mgba-emu/mgba/assets/90721584/7d5608da-a22c-4dc1-8580-731bdd38c06c)

For whatever reason, the memory section fails. I've tried with other versions, same things.

![AGB_CHECKER v1 0 (TCHK-0)-0](https://github.com/mgba-emu/mgba/assets/90721584/5482f2a4-c863-4735-b767-37e0d1d59453)
![AGB_CHECKER v7 0 (TCHK10)-0](https://github.com/mgba-emu/mgba/assets/90721584/44e5427b-9a5e-4c89-a758-94a584b7bb0a)
![AGB_CHECKER v7 1-0](https://github.com/mgba-emu/mgba/assets/90721584/c1c32cd2-501e-4cd0-88d2-03b2284f18bf)

I really wonder how this can be fixed, since realistically I have no clue how it passes.

Thank you for your time !

**Comment by endrift** [comment] 2023-08-28 22:08
Duplicate of #2108. Please use search next time.

**Closed by endrift** 2023-08-28 22:08 UTC
