### ISSUE TITLE
Can't use Shift as Fast Forward (Held) Bind?

### ISSUE THREAD

**Issue by Sartaryon** [mgba-emu/mgba#3131] opened 2024-02-02 20:05 UTC
When I try to bind Fast Forward (Held) or Fast Forward to shift, fast forwarding doesn't work.

I removed every bind in Shortcuts that had Shift+Something bound.

**Comment by endrift** [comment] 2024-02-05 09:45
Yes, this is a known limitation. I believe there's already a bug open about this but I'll have to find it.

**Comment by endrift** [comment] 2024-10-02 13:22
Duplicate of #3007.

**Closed by endrift** 2024-10-02 13:22 UTC
