### ISSUE TITLE
Fast Forward Not Working Mac OSX

### ISSUE THREAD

**Issue by domesticated** [mgba-emu/mgba#1932] opened 2020-11-07 18:17 UTC
Having the same problem as https://github.com/mgba-emu/mgba/issues/1590 but on Mac OSX with Pokemon Fire Red on the latest Development version.

Works fine on 8.4

**Comment by endrift** [comment] 2020-11-08 04:17
What are your sync settings?

**Comment by domesticated** [comment] 2020-11-09 05:50
I tried audio sync, video sync, audio & video sync, and no sync options selected. None seemed to make a difference which I believe was also reported to be the same on #1590

**Comment by endrift** [comment] 2020-11-09 05:59
So this is specifically with bounded fast forward? What are the symptoms of "not working"? Does it do nothing? Does the sound get garbled at all?

**Comment by domesticated** [comment] 2020-11-09 06:07
Yes, bounded fast forward. The audio increases in tempo but the gameplay and video remain at their standard 1x gameplay and 60 fps. On 0.8.4 I'm not having any troubles with bounded fast forward on any speed, just the latest development version.

**Comment by endrift** [comment] 2020-11-28 00:06
Are you using the OpenGL renderer under the enhancements tab in settings?

**Comment by endrift** [comment] 2020-11-28 03:49
If you're using the OpenGL enhancement (not the same as the OpenGL display driver in the a/v settings tab), this is a duplicate of #1936.

**Comment by endrift** [comment] 2021-05-24 01:42
Closing due to lack of reply.

**Closed by endrift** 2021-05-24 01:42 UTC
Labels: blocked:needs info, blocked:needs retest, system:macOS
