### ISSUE TITLE
Menu rendering issue on start, black background (Qt, Linux)

### ISSUE THREAD

**Issue by akien-mga** [mgba-emu/mgba#821] opened 2017-07-23 20:13 UTC
When starting mgba-qt 0.6.0 on Mageia 6 (self-compiled, preparing a RPM package for that distro), the menu is partly shown with a black background:
![image](https://user-images.githubusercontent.com/4701338/28502489-b28e54d2-6ff3-11e7-8685-f0fea6357bc3.png)

After hovering some entries, the hover background stays:
![image](https://user-images.githubusercontent.com/4701338/28502494-cb1cb084-6ff3-11e7-9f54-7069ac78b230.png)

When running a ROM, the window properly refreshes and displays its menus properly:
![image](https://user-images.githubusercontent.com/4701338/28502501-e69d7168-6ff3-11e7-95cc-37c584e1c542.png)

Environment:
- Linux 4.9.38
- Qt 5.6.2
- Nvidia GTX 670M with proprietary driver 375.66
- GCC 5.4.0

**Comment by endrift** [comment] 2017-07-23 20:15
Dupe of #514. Presumed to be an upstream bug.

**Closed by endrift** 2017-07-23 20:15 UTC
