### ISSUE TITLE
The ability to change the file directories

### ISSUE THREAD

**Issue by Trexador96** [mgba-emu/mgba#86] opened 2015-08-17 21:36 UTC
Im unable to change the savefile and cheats directory, It currently saves to the roms folder and I dont want clutter.

**Comment by karasuhebi** [comment] 2015-08-17 22:06
I second this request. It'd be nice to keep the ROMs directory tidy, plus it would lower the barrier to entry for people moving from VBA and VBA-M since they wouldn't have to move their .sav files.

**Comment by endrift** [comment] 2015-08-17 22:06
VBA stores them the same way as mGBA--this changed at some point in VBA-M though.

**Comment by karasuhebi** [comment] 2015-08-17 22:09
Yeah sorry about that, I should have checked VBA's behavior before including it in the sentence. Fixed :)

**Comment by tony971** [comment] 2015-08-18 09:55
Duplicate of https://endrift.com/mgba/bugs/show_bug.cgi?id=209

**Comment by endrift** [comment] 2016-01-15 22:40
Fixed in a38beac307b7b42dbc5ad5806a92b91396bea555.

**Closed by endrift** 2016-01-15 22:40 UTC
Labels: enhancement
