### ISSUE TITLE
Framepacing issues

### ISSUE THREAD

**Issue by perguto** [mgba-emu/mgba#3125] opened 2024-01-28 22:49 UTC
![image](https://github.com/mgba-emu/mgba/assets/103294508/8fe548cc-fce0-471e-8d82-3952f0288841)

The frametimes of the mgba standalone program aren't even, but have regular small spikes (See the spikes in the pink frametime graph).
For comparison, the mgba core in Retroarch has basically perfect framepacing:

![image](https://github.com/mgba-emu/mgba/assets/103294508/85436ea7-ba01-43f0-ab23-34494bbdaa04)

**Comment by endrift** [comment] 2024-01-30 05:44
Duplicate of #2199, or close to it.

**Closed** 2024-01-30 05:44 UTC

**Comment by perguto** [comment] 2024-03-12 16:29
I did some further testing and found out that it's an audio synchronization issue. Turning off audio sync stabilizes the framerate, but introduces some noise, which can be fixed by setting the buffer size sufficiently high (4096 samples), which however leads to noticable audio lag (about 120ms?). Still suboptimal, as Retroarch runs fine with just 30ms of audio latency.
