### ISSUE TITLE
Multiplayer Window

### ISSUE THREAD

**Issue by Maxx9595** [mgba-emu/mgba#1002] opened 2018-02-26 22:34 UTC
I continue to get a white blank screen when trying to load a rom in a second, multiplayer window. PLEASE HELP! I am trying to trade pokemon in fire red and leaf green

**Comment by endrift** [comment] 2018-02-26 22:43
Dupe of #854

**Closed by endrift** 2018-02-26 22:43 UTC

**Comment by Maxx9595** [comment] 2018-02-26 22:50
wait but it doesnt say how to fix it?

**Comment by endrift** [comment] 2018-02-26 22:55
That's because it's a bug in mGBA that hasn't been fixed yet. There are some troubleshooting steps but for the most part there's not much you can do on your own.

**Comment by Maxx9595** [comment] 2018-02-26 23:06
Oh okay thanks!

**Comment by CyboZax** [comment] 2018-12-07 17:12
it worked before 
and now its not

**Comment by RunisDauphin** [comment] 2019-04-08 09:23
Does anyone know how to play 1 vs. 1 matches in Megaman Battle Network 3 (blue/black or white, US version) without speed dropping?
I tried playing this game to obtain one Giga chip that depends on this, but speed drops below 20% (although mGBA does not notice the speed drop) and is pretty much impossible both using a combo with VarSword (like B, B, Left, Down, Up) and getting a rank above 9. If you want, I can supply you a sav save file to check it. If helpful, my versions have the BN3 Plus hack by Prof. 9 (available in romhacking.net).

The computer on which I tried has these specs:
-/Processor: Intel Core i7-2600 @ 3,40 GHz.
-/RAM: 4 GB (4 GB usable).
-/Système Opératif (Operative System): Windows 10 v1803, architecture 64 bits.
-/Graphic Card: ?

I do not want to think what will happen to my laptop if I ever tried it.
