### ISSUE TITLE
GBC - Loading quick saves on screen transitions makes games mute

### ISSUE THREAD

**Issue by themalu866** [mgba-emu/mgba#1305] opened 2019-02-13 19:24 UTC
Playing on Windows, the music plays just fine and I quick save, then I die, or go to the next level, or enter a bonus/warp, it doesn't matter, at the exact moment when the screen fades and there's a brief SILENCE if I quick load on that moment the level music don't play and only returns if I die or go to different screen.

As far as I know this only happens when there is this quiet moment, it doesn't seem to happen with games where the transition is instantaneous but I not sure. And maybe that happens with GB games too.

[Donkey Kong Land 2.zip](https://github.com/mgba-emu/mgba/files/2861807/Donkey.Kong.Land.2.zip)

[Donkey Kong Land III.zip](https://github.com/mgba-emu/mgba/files/2861808/Donkey.Kong.Land.III.zip)

**Comment by endrift** [comment] 2020-08-12 07:38
This is likely fixed on latest dev builds. Please retest.

**Comment by themalu866** [comment] 2020-08-24 07:36
I checked on Donkey Kong Land III and still happens.

**Comment by endrift** [comment] 2020-08-24 07:39
Was this with a save state you made on the newer builds? Old save states may have been created with errors in them as a result of bugs.

**Comment by endrift** [comment] 2020-08-24 07:45
Never mind, I can reproduce.

**Comment by themalu866** [comment] 2020-08-24 07:56
It's a new save but this time the glitch is kinda different.
If I quick load at silent moments it still gets mute, but if I close mgba, quick load really fast then the music partially plays and if I wait for the title screen to appears and then load it the music plays fine.
This is only happening with Donkey Kong Land III, Donkey Kong Land 2 is fine.
[Donkey Kong Land III.zip](https://github.com/mgba-emu/mgba/files/5116491/Donkey.Kong.Land.III.zip)

**Comment by endrift** [comment] 2020-08-24 08:28
Turns out the commit I thought I fixed this in broke something related in the process. It's properly fixed now.

**Closed** 2020-08-24 08:28 UTC
Labels: feature:audio, feature:savestates, platform:GB/GBC
