### ISSUE TITLE
Dolphin +mGBA support

### ISSUE THREAD

**Issue by fancymelonub** [mgba-emu/mgba#952] opened 2018-01-02 01:28 UTC
It's 0.6.1 and nearly 0.7 and no real support with Dolphin yet? Why?
You clearly should've at least publicly added the feature in 0.6 or 0.6.1.

**Comment by endrift** [comment] 2018-01-03 19:23
(Super entitled) dupe of #422

**Closed by endrift** 2018-01-03 19:23 UTC
