### ISSUE TITLE
[Regression] Magical Vacation JPN - bad Audio

### ISSUE THREAD

**Issue by exhalatio** [mgba-emu/mgba#230] opened 2016-02-18 08:01 UTC
I've get the great Audio in previous 2016-02-11 build.
However, I don't get some part of Audio in 2016-02-15 build and newest.

I use the BIOS file and enable Skip BIOS intro.

**Comment by endrift** [comment] 2016-02-18 20:40
Probably caused by the audio overhaul. I'm in the middle of cleaning it up; it's known to be really buggy.

**Comment by exhalatio** [comment] 2016-02-19 03:59
I'm sorry, I reported the regression seem to be in a hurry.
Thank you for caring the issue.

**Comment by endrift** [comment] 2016-02-20 13:08
Should be fixed as of b8ed859, which just missed the cutoff for the most recent nightly.

**Closed by endrift** 2016-02-20 13:08 UTC
