### ISSUE TITLE
[3DS] Issues with sprites when at top of screen

### ISSUE THREAD

**Issue by Ty-Dye** [mgba-emu/mgba#1490] opened 2019-07-18 15:12 UTC
This is a issue that causes sprites to either look weird (as shown in pic) or vanish tottaly

I have seen this in both Mario Advance 2 and Battle for Bikini Bottom, Battle for bikini bottom is the one shown in picture

Mario advance 2 had this issue and it was annoying during boss fights that involved koopas on the ceiling because you had no clue whare they were at (as they vanished)

using v1.7.2

![](https://i.imgur.com/6Af8y9n.jpg)

**Comment by endrift** [comment] 2019-07-18 15:32
Dupe of #1436, which is fixed in the dev builds.

**Closed by endrift** 2019-07-18 15:32 UTC
