### ISSUE TITLE
Key IRQ always happens at the same VCOUNT

### ISSUE THREAD

**Issue by pinobatch** [mgba-emu/mgba#2490] opened 2022-04-02 18:19 UTC
A program can tell that it's running on mGBA because the key IRQ always happens right at vblank.

To reproduce:
1. Build mGBA Qt 0.10-7193-a9ef7af3b on Xubuntu 21.10
2. Start the attached test ROM "Telling LYs?" [tellinglys-gba-0.01.zip](https://github.com/mgba-emu/mgba/files/8403149/tellinglys-gba-0.01.zip)
3. Press all 10 buttons in any order
4. Watch the arrow sprite at the right side

Expect: Arrow moves after each press, followed by "Pass", as on my AGB-001

Actual: Arrow stays half off the bottom of the screen, followed by an "Incorrect behavior" screen

Related issues
- mGBA Game Boy: https://github.com/mgba-emu/mgba/issues/1232
- Tracking: https://github.com/pinobatch/little-things-gb/issues/3

**Comment by endrift** [comment] 2022-04-03 10:04
Given that this is caused by the frontend, not the core (the core itself is agnostic), this is a duplicate of #1232.

**Closed by endrift** 2022-04-03 10:04 UTC
