### ISSUE TITLE
Space Channel 5 crash

### ISSUE THREAD

**Issue by CowboyJoseph64** [mgba-emu/mgba#1758] opened 2020-05-20 17:11 UTC
Near the end of the first stage, the yellow... things, that come out of the big purple robot will have scrambled graphics, and then the game freezes.

**Comment by RetroEdit** [comment] 2020-05-20 22:38
I didn't experience this issue when I tested mGBA 0.8.1. What's your platform and version of mGBA?

**Comment by CowboyJoseph64** [comment] 2020-05-21 19:34
The version is 0.8.1, and I'm on Windows 10.
I'm using the american version of the rom, typically numbered 1071.

**Comment by RetroEdit** [comment] 2020-05-21 19:55
What do you have the display driver set to, Qt software or OpenGL? (Found in `Tools > Settings > Audio/Video`). Does it consistently happen every time you reach that section of the game? And also, if you're able, can you attach a savestate showing the glitched state? It would probably be useful to get a savestate right before it transitions to the yellow robots exiting the giant purple robot that leads into the glitched graphics and freeze.

**Comment by CowboyJoseph64** [comment] 2020-05-21 21:14
It is set to opengl, and it consistently happens every time. Here's a save state:
[space channel 5 save state.zip](https://github.com/mgba-emu/mgba/files/4664811/space.channel.5.save.state.zip)

**Comment by endrift** [comment] 2020-05-22 02:43
What does the ROM Info dialog say about the game? Like the CRC32?

**Comment by CowboyJoseph64** [comment] 2020-05-22 06:58
I'm sorry, what do you mean by rom info dialog? How do I check that?

**Comment by endrift** [comment] 2020-05-22 07:37
It's in the File menu, right above the recent ROMs list.

**Comment by CowboyJoseph64** [comment] 2020-05-22 14:20
![image](https://user-images.githubusercontent.com/25892341/82677299-66b70600-9c0d-11ea-923f-b3558b613dde.png)

**Comment by RetroEdit** [comment] 2020-05-22 14:26
Yep, that's indeed likely to be a good copy according to [No-Intro](https://datomatic.no-intro.org/?page=show_record&s=23&n=1054), and probably the same as the one I tested.

**Comment by RetroEdit** [comment] 2020-05-22 15:00
Huh, so loading that attached savestate brought me back to the Bios screen, which seems rather odd. Maybe @endrift can comment further on the savestate at some point? The savestate preview image seems reasonable, but the savestate itself does not function in a way I would have expected.

**Comment by CowboyJoseph64** [comment] 2020-05-22 16:09
After you mentioned the bios, I loaded one, and sure enough, that was the problem. The game needs the bios to function correctly.

I could have sworn there was an emulator that warned you if a bios file was needed for the game, but I don't think it's this one. Sorry for the trouble.

**Comment by RetroEdit** [comment] 2020-05-22 16:13
Oh, no problem. I didn't even think of that, and normally I wouldn't even be using a bios, but I happened to set it up for that latest release

This may still have relevance because mGBA still generally tries to be accurate without a bios (but a bios helps a lot).

**Comment by endrift** [comment] 2020-05-22 19:38
The savestate won't load because I changed the built-in BIOS at some point and the savestate is inside the BIOS. I was able to fiddle with it enough to get the state to load and it does reproduce from the state. However, I don't know if the game was already in a bad state when the savestate was created.

**Comment by RetroEdit** [comment] 2020-05-22 19:44
I don't think it's too hard to get there with fast-forward and just pressing the right inputs for the robot encounter. But I didn't get around to it, because I just gave up after I botched the robot encounter 1 time, so it's still a TODO. Would doing that be helpful or is there anything else that would be helpful?

**Comment by CowboyJoseph64** [comment] 2020-05-22 19:57
All I did is play normally up to that point, I don't think I did anything in particular. You can't just fast forward though, I'm pretty sure if you mess it up too many times in a row, the show gets cancelled.

**Comment by RetroEdit** [comment] 2020-05-22 20:45
Yeah, you have to survive the robot fight. But you don't have to avoid a game over, you just have to get to the screen with the smaller yellow robots, so you can just fast-forward everything before the purple robot fight.

**Comment by endrift** [comment] 2021-09-20 02:45
I no longer seem to be able to reproduce this in. Can you confirm that it still happens from a fresh save (not a savestate)?

**Comment by endrift** [comment] 2021-11-12 19:55
Closing due to lack of reply.

**Closed by endrift** 2021-11-12 19:55 UTC
Labels: platform:GBA, blocked:needs retest
