### ISSUE TITLE
PCM12 and PCM34 are not emulated

### ISSUE THREAD

**Issue by pinobatch** [mgba-emu/mgba#1951] opened 2020-11-25 22:04 UTC
LIJI discovered years ago that the Game Boy Color APU includes registers for reading back the four 4-bit PCM values that the four audio channels are sending to the DACs. These are reportedly "undocumented" (not described in purported leaked official manuals).

- PCM12 ($FF76): pulse 1 in bits 3-0, pulse 2 in bits 7-4
- PCM34 ($FF77): wave in bits 3-0, noise in bits 7-4

The APU tests in [SameSuite](https://github.com/LIJI32/SameSuite) and [GBVisualizer](https://github.com/LIJI32/GBVisualizer) test this.

**Comment by endrift** [comment] 2020-11-25 22:28
Dupe of #1468

**Closed by endrift** 2020-11-25 22:28 UTC
