### ISSUE TITLE
The Smurfs (1993) (Infogrames) does not start

### ISSUE THREAD

**Issue by lioneltrs** [mgba-emu/mgba#2016] opened 2021-01-17 14:32 UTC
Hello,
The Gameboy game  "the Smurfs (1993)" from Infogrames (in black in white)
```
sha1sum SMURFS.gb
9fc50648c18f7f8f0e567ba8791b1d9a43c9f044  SMURFS.gb
```
does not start. It only displays a white screen. I checked it on (with and without a bios):
- mgba 0.7.0 on Ubuntu 20.04.
- lr-mgba 0.8.3 on Ubuntu 20.04.
- mgba 0.8.4 on 3DS.

The same rom works on Retropie lr-gambatte.
Regards,
Lionel

**Comment by endrift** [comment] 2021-01-17 20:05
Duplicate of #1982.

**Closed by endrift** 2021-01-17 20:05 UTC
