### ISSUE TITLE
Object not displayed and incorrect Object palette

### ISSUE THREAD

**Issue by Yalefeuv** [mgba-emu/mgba#185] opened 2015-12-08 19:48 UTC
Tested on versions mGBA-0.3.1-2015-10-24-win32 and mGBA-nightly-2015-12-08-win32

The tiny technichal demo available below should display a sprite in the upper left corner. One of the sprite color should change every frame.

The sprite is invisible and the color palette is incorrect. The first 4 colors are OK including the changing one but the others should be black.

Works well on a DS lite and visual boy advance, untested on GBAs.

PS: header needs to be fixed to run on actual hardware, only the branch instruction is correct, the others fields are filled with 0. I wrote this in assembly, years ago.

http://dl.free.fr/vIajZLqRE (30 days limit or so)

**Comment by endrift** [comment] 2015-12-08 21:36
Not sure about the color palette issue (which I can't reproduce), but the reason the sprite is invisible is because the sprite isn't initialized properly...the first halfword never gets set to "not invisible". It looks like the BIOS clears that out on hardware, which is why it's working. I guess I should change mGBA to match the post-BIOS state.

**Comment by Yalefeuv** [comment] 2015-12-09 09:34
Thank you for the quick reply. I made a few tests with a correct header:

BIOS enabled with intro => OK
no BIOS => Sprite not visible + the 4 colors are OK but the others are not all black (values seems random for some of them)
BIOS but no intro => Palette is OK but the sprite is invisible.

Hope this will help

**Comment by endrift** [comment] 2015-12-10 05:24
Fixed in df3ee0e2be38095bbfc2385d430fa82542c64334

**Closed by endrift** 2015-12-10 05:24 UTC
Labels: minor bug
