### ISSUE TITLE
[Wii Port] Small BUG in Gambe Boy Color game Puchi Carat

### ISSUE THREAD

**Issue by SieKensou** [mgba-emu/mgba#1920] opened 2020-10-29 17:27 UTC
Hi! I noticed a small BUG in this game when testing it on the Nintendo Wii.
When you press START at the title screen, when you select mode, when you select character, at the characters conversations, when the game starts, etc... the screen should show a white flash between that screens. For some reason that is missing in this emulator. Here is a video for reference of how should it look:
https://www.youtube.com/watch?v=70EeEiZHjCg

**Comment by endrift** [comment] 2024-09-30 10:21
Duplicate of #1285

**Closed by endrift** 2024-09-30 10:21 UTC
