### ISSUE TITLE
(mGBA Vita 0.7 b1) How to add cheats?

### ISSUE THREAD

**Issue by nanashi89** [mgba-emu/mgba#1277] opened 2019-01-24 18:50 UTC
Your readme says it has cheat code support, but I don't see how to activate it....
[README.txt](https://github.com/mgba-emu/mgba/files/2793115/README.txt)

**Comment by autofire372** [comment] 2019-01-25 20:17
Last I checked, the homebrew ports don't have that exposed in the GUI.

**Comment by endrift** [comment] 2021-03-31 07:15
Duplicate of #903.

**Closed by endrift** 2021-03-31 07:15 UTC
