### ISSUE TITLE
[Feature Request] Networked Multiplayer via emulated link cable.

### ISSUE THREAD

**Issue by RSC-Games** [mgba-emu/mgba#2469] opened 2022-03-04 14:14 UTC
Duplicate of #2379, however it was not addressed.

I'm trying to build a Raspberry Pi-based GBA, and wanted network link cable emulation. So I tested on PC, and there is no option for online multiplayer between two GBA consoles (only Dolphin).
I tried VBA-M 2.1.4, and it turns out multiplayer is broken, so they aren't an option.
However, VBA 1.8 works, but I don't know if there is a build for RPi.

So, could you, by chance, add networked multiplayer to the next release of mGBA?

**Comment by endrift** [comment] 2022-03-04 21:16
Filing a known duplicate of a *still open* bug is generally inadvisable and will just result in the bug being closed. Networked multiplayer is a big effort and will not be in the next release, but it is a goal that I've had for a while.

**Closed** 2022-03-04 21:16 UTC
