### ISSUE TITLE
mGBA acts different due to type of slash in ROM path

### ISSUE THREAD

**Issue by Blazewardog** [mgba-emu/mgba#220] opened 2016-02-10 04:59 UTC
I noticed an issue tonight which originally made me think the "Saves in a different Directory" setting was broken. I instead found mGBA is acting odd depending on what type of slash in used in the path on Windows (In my case Win 10 x64).

Basically, if the path is windows style and you launch the game as such via the cmd prompt with:
"D:\ROMS\mGBA\mGBA.exe" "D:\ROMS\GBA\GBAROM.gba"
It won't actually load or save any .sav files (or save states). But if you launched it as:
"D:\ROMS\mGBA\mGBA.exe" "D:/ROMS/GBA/GBAROM.gba"
It works just as if you loaded the ROM through the menu.

Additionally, both types of paths are saved as different ROMs in the recent menu.

This breaks file association in Windows as it always passes paths "Windows Style"

**Comment by endrift** [comment] 2016-02-10 05:00
I thought I'd flattened all of these out. Sigh. Time for more fixing.

**Comment by tony971** [comment] 2016-03-22 14:31
Confirmed.

**Comment by tony971** [comment] 2016-04-18 13:44
The latest nightlies are unusable as I am unable to save or load saves/savestates.

**Comment by endrift** [comment] 2016-04-21 20:56
@tony971 I haven't been able to reproduce your (unrelated) issue on the latest master on my end.

**Comment by tony971** [comment] 2016-05-14 12:35
I'm unable to reproduce either bug on my end anymore.

**Comment by endrift** [comment] 2016-05-23 06:19
Fixed in 210ef6db506e26cd3bc2f0eb67d46563285fdfdb.

**Closed by endrift** 2016-05-23 06:19 UTC
Labels: bug
