### ISSUE TITLE
[Wii] Graphical glitches

### ISSUE THREAD

**Issue by rayabusa** [mgba-emu/mgba#1061] opened 2018-04-23 02:34 UTC
Having some weird graphical glitches on version 0.6.3 for the wii, this wasnt happening on 0.6.1.

While playing Sonic Advance 2 for example, Sonic sprites appears at random places on the screen.

Playing on Wii, via component 240p mode.

**Comment by endrift** [comment] 2018-04-23 05:35
Do these glitches also occur in a recent development build?

**Comment by rayabusa** [comment] 2018-04-23 21:49
Did't test recent builds and dont know how can i even play those versions, only in version 0.6.3 downloaded from the mgba.io site.

**Comment by endrift** [comment] 2018-04-23 21:50
There's a development builds section on the downloads page: https://mgba.io/downloads.html#development-downloads

**Comment by rayabusa** [comment] 2018-04-24 12:54
Nice, gonna test and post results here later.

**Comment by rayabusa** [comment] 2018-04-24 14:47
Its still happening but less frequent, and depends on the game im playing.

Version tested:  0.7 - 5092-2798622

**Comment by endrift** [comment] 2018-04-24 14:51
What game does it reproduce the most in? I'll try to take a look today.

**Comment by rayabusa** [comment] 2018-04-24 15:02
Sonic Advance 2, sometimes it happens even on the menus.

BTW thanks for the support and this emulator man, its awesome.

**Comment by SuperrSonic** [comment] 2018-04-28 15:17
![sa2_01](https://user-images.githubusercontent.com/6880539/39397496-1a2fc3ae-4ace-11e8-917c-143edf329700.gif)
![sa2_02](https://user-images.githubusercontent.com/6880539/39397782-c861caa4-4ad2-11e8-91b2-aec01aa8032a.gif)
I tried finding a spot to easily get the flicker.
State:
![0815 - sonic advance 2 j ss1](https://user-images.githubusercontent.com/6880539/39397797-ff090310-4ad2-11e8-8dab-3dfd8ba2d7a4.png)
I just fall to the pit and it would sometimes flicker randomly on the stage banner transition.
This was tested on 67a135e5e7a5d6366f516972f25e7c71bff91447 win32 build, Japanese rom.

**Comment by endrift** [comment] 2018-04-28 20:11
Might be a dupe of #361.

**Comment by JMC47** [comment] 2018-09-05 21:47
Definitely a dupe of #361 after comparing this savestate to the behavior described there.

**Comment by endrift** [comment] 2018-09-21 21:33
Closing as dupe.

**Closed by endrift** 2018-09-21 21:33 UTC
Labels: category:duplicate
