### ISSUE TITLE
Super Mario Advance 4 - Super Mario Bros. 3 color restoration patch doesn't work with mGBA.

### ISSUE THREAD

**Issue by John-Enigma** [mgba-emu/mgba#775] opened 2017-07-02 22:34 UTC
I know this is gonna sound weird, and I don't know if I'm allowed to post this but, whenever I try to play this [color restoration hack for Super Mario Advance 4 - Super Mario Bros. 3](http://www.romhacking.net/hacks/3315/), it doesn't work. Every time I go to the first level, it freezes at the word "MARIO START" (or "LUIGI START" for that matter). 

I've tested other color restoration hacks for the other three Super Mario Advance games, and they all work. Except for this one. 

Can this be fixed?

**Comment by endrift** [comment] 2017-07-02 22:34
I'm...pretty sure this is a dupe. I know it's been reported before. Let me see if I can find it.

**Comment by endrift** [comment] 2017-07-02 22:35
Dupe of #520

**Closed by endrift** 2017-07-02 22:35 UTC

**Comment by John-Enigma** [comment] 2017-07-02 22:37
Thanks for telling me. 

I didn't know this was addressed before.
