### ISSUE TITLE
Error when trying to record using the lossless preset

### ISSUE THREAD

**Issue by shenef** [mgba-emu/mgba#2286] opened 2021-08-21 22:02 UTC
The other presets work fine. The file does not already exist and there is no file created when attempting to start the recording.
![image](https://user-images.githubusercontent.com/20268890/130335668-2f93c52d-3987-4384-a15b-51ea70e8ad74.png)
Also of note, when opening the list of codecs, the codec that is chosen by the lossless preset is not listed.
![image](https://user-images.githubusercontent.com/20268890/130335798-b4704c59-a358-44c0-8b37-a7796476d3b3.png)

mGBA release version 0.9.2, Windows 10 21H1, i7-2600k, GTX 1060

**Comment by endrift** [comment] 2021-08-21 22:03
Huh, I thought I fixed this already. Pretty sure there's an open bug report about this already if not, but I'll have to find it.

**Comment by endrift** [comment] 2021-08-21 23:47
Turns out this is a duplicate of #2084, which there was a PR to fix but it didn't get merged.

**Closed by endrift** 2021-08-21 23:47 UTC
