### ISSUE TITLE
Is it possible to do making mGBA for Android (.apk)

### ISSUE THREAD

**Issue by Squidward22** [mgba-emu/mgba#2574] opened 2022-06-30 12:50 UTC
Is it possible to do making mGBA for Android (.apk). Android devices are touch screen. It requires touch overlays controls (overlays128.png or overlays256x256.png). I don't know are you using Android devices.

**Comment by endrift** [comment] 2022-06-30 12:51
Duplicate of #1660.

**Closed by endrift** 2022-06-30 12:51 UTC
