### ISSUE TITLE
Power Pro Kun Pocket 3 (Japan): BGM timing issues

### ISSUE THREAD

**Issue by Nukotan** [mgba-emu/mgba#1399] opened 2019-04-30 14:01 UTC
mGBA v0.7.1

The problem that the FIFO ch sound disappears temporarily.
Changing the value of info->when changes the situation.
But I don't know the correct value.
https://github.com/mgba-emu/mgba/blob/1deff07aa1b0d3d4b6b15e875fbeb0cc8eff0926/src/gba/dma.c#L297-L302

**Comment by endrift** [comment] 2022-01-22 04:07
Does this still reproduce on latest mGBA?

**Comment by endrift** [comment] 2023-02-09 09:52
Closing due to lack of reply.

**Closed by endrift** 2023-02-09 09:52 UTC
Labels: platform:GBA, blocked:needs retest
