### ISSUE TITLE
Cannot map certain keyboard keys on latest Development build on Windows

### ISSUE THREAD

**Issue by TheGershon** [mgba-emu/mgba#3323] opened 2024-10-25 00:16 UTC
At some point between Stable and the current Development build it's become impossible to map keyboard keys like Shift, Enter, anything on the Numpad, etc on Windows. Maps can properly carry over from Stable, but attempting to map again results in incorrect mappings.

Here's my config in the GUI on Stable:
![image](https://github.com/user-attachments/assets/757c9d0b-7eaf-433b-9d00-f746bcbd0011)
and here's [gba.input.QT_K] within config.ini:
```
[gba.input.QT_K]
keyRight=68
keyDown=83
keyR=16777221
keyL=16777248
keyB=52
keyUp=32
keySelect=50
keyLeft=65
keyA=53
keyStart=49
```
These mappings continue to work when updating to Development. However, remapping the same keys results in this:
![image](https://github.com/user-attachments/assets/95d44623-e522-40af-a35a-2b2828f49d84)
and here's [gba.input.QT_K] again:
```
[gba.input.QT_K]
keyRight=68
keyDown=83
keyR=553648133
keyL=33554432
keyB=536870964
keyUp=32
keySelect=536870962
keyLeft=65
keyA=536870965
keyStart=536870961
```
Now, only the D-Pad controls work.

**Comment by endrift** [comment] 2024-10-25 00:27
Probably a regression caused by https://github.com/mgba-emu/mgba/pull/3201

**Comment by endrift** [comment] 2024-10-25 00:28
cc @oltolm

**Comment by TheGershon** [comment] 2024-10-25 00:36
> Probably a regression caused by #3201

Yup, Revisions 8478-79193b9 and 8479-a824989 are before & after this began to happen

**Comment by TheGershon** [comment] 2024-10-30 06:34
I regret to inform you that the issue persists on 0.11-8585-47e5cd243
![image](https://github.com/user-attachments/assets/250665b0-bc94-4378-98d6-2fd5a9a27964)

**Comment by endrift** [comment] 2024-10-30 07:20
Shift should work now, but numpad might not be fixed. I didn't check those and feared they might still be broken, but merging the PR auto-closed this.

**Closed** 2024-10-31 23:45 UTC
Labels: severity:regression, port:Qt
