### ISSUE TITLE
Single Pak Connection Error

### ISSUE THREAD

**Issue by TsukiruP** [mgba-emu/mgba#2602] opened 2022-07-26 04:06 UTC
Tried with both Sonic Advance 2 and 3, "finishes" downloading data before saying Connection Error. I know this error has been brought up in 2021 and 2019 but there seems to not have been any further discussion with this, at least from what I could find.

I open Sonic Advance 2/3, then create a new multiplayer menu set to the boot the bios. Outside of controls I haven't touched anything.

**Comment by endrift** [comment] 2022-07-26 04:54
Duplicate of #2044. Opening duplicates of known-but-not-resolved bugs does not help them get fixed faster.

**Closed by endrift** 2022-07-26 04:54 UTC

**Comment by TsukiruP** [comment] 2022-07-26 17:04
Less of wanting to get "them helped fixed faster" but thanks regardless I guess.
