### ISSUE TITLE
Pokemon bootleg can't save the game

### ISSUE THREAD

**Issue by moniker-a11y** [mgba-emu/mgba#2118] opened 2021-04-07 00:35 UTC
I've been playing a bootleg translation of Pokemon Emerald, known as "Chinese Emerald", I hadn't noticed at first since I just used save states, but the game can't save. It says that it saved but when I restart it, it says the save file is gone and takes me to start a new game.

Now the game itself is not broken, I tried running it on VBA and there were no issues whatsoever, it saved just fine and I could load my save. I tried setting the game override save to all the other options (not that it would matter anyway, since apparently you can't do that in-game, meaning I'd have to restart it, making the whole thing pointless) but none of them worked, in fact they made the game stall forever when trying to save, which the default one did not, it gave the illusion that it properly saved. 

I tried using a save convert option I saw, to convert the save state, maybe? The sav file I got seemed rather small, and was unreadable by VBA and just did nothing on mGBA. The exact same thing happened with the Gameshark save option, VBA said the file was invalid, mGBA just did nothing.

Anything I can do to transfer the game state out of there? This probably wouldn't be an issue for most titles, since you could just use save states, but Pokemon games forcibly restart themselves at a certain point, meaning it would instantly be a dead end.

**Comment by endrift** [comment] 2021-04-07 00:39
This is probably a duplicate of #247. What size is the save that VBA makes when running it there?

**Comment by moniker-a11y** [comment] 2021-04-07 00:45
VBA's sav file is 64kb, mGBA's is 128kb

**Comment by endrift** [comment] 2021-04-08 05:43
That sounds like it's an SRAM save. Try setting the save type to SRAM in the Game overrides menu before loading the ROM.

**Comment by moniker-a11y** [comment] 2021-04-08 12:15
It did not change anything, I believe it was automatically set to that as well

**Comment by endrift** [comment] 2021-04-08 19:24
And to confirm, if you leave the window open when loading the game it doesn't get reset to Flash anything?

Can you upload the 64K save that VBA creates?

**Comment by moniker-a11y** [comment] 2021-04-08 22:42
It's definitely locked into SRAM, and like I said, the other options make it so it can't even finish the supposed saving
[save.zip](https://github.com/mgba-emu/mgba/files/6281951/save.zip)

**Comment by endrift** [comment] 2021-04-08 22:45
Ah, this confirms my suspicions. This bootleg uses the full 64kB, which mGBA does not support since no official cartridges use it, but VBA supports it by accident. It also makes me think that this is indeed a dupe of #247, but since that one hasn't been updated in  years I'm gonna forward dupe it to this.

**Comment by endrift** [comment] 2022-02-21 04:06
mGBA has a 64kB SRAM override option in the dev builds--can you test to see if that works? Or, alternatively, upload a patch for the bootleg (against a clean ROM) so I can test myself.

**Comment by moniker-a11y** [comment] 2022-03-01 03:09
It worked, I'll provide the patch anyway, apply it to "1649 - Pokemon Emerald (J)(Independent)"
[pokemon chinese emerald.zip](https://github.com/mgba-emu/mgba/files/8158494/pokemon.chinese.emerald.zip)

**Comment by endrift** [comment] 2022-03-01 03:50
Thanks for confirming.

**Closed** 2022-03-01 03:50 UTC
Labels: severity:enhancement, platform:GBA, blocked:needs retest, software:romhack
