### ISSUE TITLE
Window is small on 4K screen

### ISSUE THREAD

**Issue by Yave-Yu** [mgba-emu/mgba#3327] opened 2024-10-28 16:49 UTC
Currently mGBA gives 8x resize option, but it still small on 4K screen, so it need give more option, or a custom value feature?

**Comment by endrift** [comment] 2024-10-29 02:20
Duplicate of #3292, also opened by you.

**Closed by endrift** 2024-10-29 02:20 UTC

**Comment by Yave-Yu** [comment] 2024-10-29 09:24
Ah sorry, I forgot that…
