### ISSUE TITLE
Screenshotting crashes 0.9.0

### ISSUE THREAD

**Issue by Kairi5431** [mgba-emu/mgba#2089] opened 2021-03-29 05:24 UTC
At least on my computer anytime I try to screenshot something it crashes the emulator regardless of whether I am using keyboard or controller. I have tried taking multiple screenshots in both "Metroid Zero Mission" and "Bleach Advance Kurenai ni Somaru Soul Society", don't get me wrong it takes the screenshots, it just crashes the emulator on my laptop in the process lol. It works just fine in the copy of 0.8.1 I already have installed (I have an installer version of 0.8.1 and grabbed the 64 bit archive of 0.9.0 in case that information would be helpful somehow).
[mGBA 0.9.0 screenshot crash report.zip](https://github.com/mgba-emu/mgba/files/6219461/mGBA.0.9.0.screenshot.crash.report.zip)
**Edit**: sorry I think it was "Metroid Fusion" I tried it with not "Metroid Zero Mission"

**Comment by endrift** [comment] 2021-03-29 05:30
You've got a pretty old CPU...can you see if it works using the 32-bit build? I'm having trouble reproducing.

**Comment by Kairi5431** [comment] 2021-03-29 05:43
Still crashes sadly, if there is anything else I can try to help let me know. I'm heading to bed but I will leave myself a reminder to check this when I wake up.

**Comment by endrift** [comment] 2021-04-01 04:11
Does it work if you change the screenshot directory? Does it crash if you make a savestate? Same if you toggle the "save state extra data > screenshot" option?

**Comment by endrift** [comment] 2021-05-09 09:18
Does this still crash for you? I never got that info I asked for either.

**Comment by endrift** [comment] 2021-06-23 09:38
Closing due to lack of reply.

**Closed by endrift** 2021-06-23 09:38 UTC
Labels: blocked:needs info, severity:host crash
