### ISSUE TITLE
mGBA Vita fails to save games (or fails to load save files)

### ISSUE THREAD

**Issue by brainard52** [mgba-emu/mgba#441] opened 2016-10-14 04:30 UTC
If I save a game on version 0.5.0 and close the emulator, it starts the next time as though it never saved to begin with. The .sav file gets created but I'm not sure whether it actually wrote anything to it. I'm not sure what else I need to provide.

**Comment by endrift** [comment] 2016-10-14 04:53
- Please don't use 0.5.0. 0.5.1 is out and provides many critical bugfixes.
- What games are you playing that are causing this issue?
- Are you exiting the game using the menu (triangle > exit) or are you tearing the page off?
- Please upload the sav file and tell me what game it's for.

**Comment by brainard52** [comment] 2016-10-14 05:43
I just tested on 0.5.1 with The Legend of Zelda: The Minish Cap and Dragon Warrior Monsters (GB). It seems to be working. I still have the 0.5.0 vpk if you still want me to test on there.

**Comment by Asuza** [comment] 2016-10-28 00:12
I'm having this same issue. I downloaded version 0.5.1, installed it, and added _Castlevania: Circle of the Moon (E)(Eurasia)_. I played for a while, saved a few times (within the game), I then exited the game using the "Exit game" option in the menu. When I came back to Castlevania later, a .sav file had been created for it, but my file in the game was not there.

Then, I tried the same process with _Mother 3_. For this game, I had an existing .sav file from an old version of mGBA (pre-5.0) and the save file loaded without issue. But, when I saved the game and exited, then reloaded the game, it did not have the new save. The .sav file is still loading fine, so it didn't break the existing save, but it did not update the file at all. Oddly, VitaShell shows a new date for the save file, so it was touched in some way.

**Comment by endrift** [comment] 2016-10-28 00:13
I've had people report this on the Wii, too.

I'll need to look into it again, but were you using savestates at the time?

**Comment by Asuza** [comment] 2016-10-28 00:15
@endrift I didn't use save states for Castlevania. I did for Mother 3, and those seemed to work fine.

**Comment by brainard52** [comment] 2016-10-28 02:42
@endrift I remember using save states for Minish Cap and having them fail on me. I was introducing my sister to the game when it happened and she had played for a good hour and a half. She didn't play after that.

**Comment by rraab8** [comment] 2016-12-10 05:21
I'm having the same problem but on the Microsoft Windows version for the game Super Mario Advance 2
Other games I've tried are saving probably.
I've been trying new nightlies as they come out to see if the issue is resolved.

**Comment by ml-** [comment] 2017-01-11 20:47
# Reproduce bad save on the Vita
**Game:** Pokemon - Version Rouge Feu (France) ( md5: b8663b80eef5a1e9b41b683aa1234902 ) [No-Intro](http://datomatic.no-intro.org/?page=show_record&s=23&n=1658)

## Steps:
1. Start game
2. Load state (1)
3. Wait 2-3 seconds, game will save
4. Reset the game after it saved (you don't want to sit through 10 minutes of credits)
5. See if game created a valid savegame file.

**On the PC** a valid savegame should be created and look like this:
![poke-0](https://cloud.githubusercontent.com/assets/6209465/21865611/2eee1070-d847-11e6-840f-604a0e7c883d.png)

**On the Vita** a **.sav** file is created but won't be shown ingame. This is an issue with the created savegame, not an issue with loading it because you can place a valid savegame on your Vita and it'll work.

[Pokemon - Version Rouge Feu (France).ss1.zip](https://github.com/mgba-emu/mgba/files/699988/Pokemon.-.Version.Rouge.Feu.France.ss1.zip)

**Comment by endrift** [comment] 2017-01-31 08:37
This SHOULD be fixed now.

**Closed** 2017-01-31 08:37 UTC
Labels: bug, port:vita, port:wii

**Comment by Ason3737** [comment] 2023-02-05 12:22
Can somebody tell me how to load sav file on gba ps vita. Every time I try it says load failed

**Comment by BrunoHellmeister** [comment] 2023-07-17 19:42
I uploaded the .sav file to the device using the name as the .gba and deleted the other files that had the same name as the .gba (such as autosave or cheats). It worked.
