### ISSUE TITLE
ALMOST passed the AGS test

### ISSUE THREAD

**Issue by Bossiskeyboard** [mgba-emu/mgba#2894] opened 2023-04-23 15:10 UTC
According to an image by luigiblood it almost passed the ags test but failed at the memory part https://twitter.com/LuigiBlood/status/1624019753206423552/photo/1  AGS Aging Cartridge is a test used by Nintendo to test GBA systems

**Comment by endrift** [comment] 2023-04-24 04:19
Duplicate of #2108.

**Closed by endrift** 2023-04-24 04:19 UTC
