### ISSUE TITLE
[GB Audio] Some sounds do not play or get cut off

### ISSUE THREAD

**Issue by bryc** [mgba-emu/mgba#2478] opened 2022-03-22 19:25 UTC
There are some cases in GB/GBC games where some sounds are not played or get cut off. This happens in `0.10-7299-50e0fe997` and does not occur in `0.9.3`. May be related to #1925.

- **Pokemon Yellow (GBC)**: The sound effect that plays when the star falls over the dev logo is absent. It appears to work when the intro loops again.  Only happens in the GBC version, not Japanese SGB(?).
- **Pokemon Yellow (GBC)**: At the title screen when the "Pikachu" voice is played, some of the initial notes of the title screen music are absent. I think only Pulse channels are affected here. Also seems to affect the Japanese SGB version. Still occurs after intro loops.
- **Pokemon Crystal (GBC)**: During intro some of the Unown cries or silent or get immediately cut off after 1-5 samples. Still occurs after intro loops.

There may be other instances but these popped out immediately to me.

Tested under Windows 10 20H2,  64-bit.

**Comment by endrift** [comment] 2022-04-22 10:00
Can you see if this still reproduces in 7336 (dcdd6d2dd2064e488ccf245fe6bacbc775323ce4) or newer? I think it might have been fixed since then.

**Comment by bryc** [comment] 2022-04-22 10:47
> Can you see if this still reproduces in 7336 ([dcdd6d2](https://github.com/mgba-emu/mgba/commit/dcdd6d2dd2064e488ccf245fe6bacbc775323ce4)) or newer? I think it might have been fixed since then.

Hmm that seems to fix the Pokemon Yellow issues, but Crystal is still missing some of the sounds. So an aspect seems to be fixed but completely.

The part in question:

https://user-images.githubusercontent.com/1408749/164700110-5be179bb-9d2c-4bf2-b3f8-b438ddeb0f69.mp4

**Comment by endrift** [comment] 2022-06-02 02:39
Fixed as of 76a8f4da2bb4fc4ef10a64eae5d3da0d7846c73f (possibly earlier)

**Closed by endrift** 2022-06-02 02:39 UTC
Labels: blocked:needs retest
