### ISSUE TITLE
mGBA issues

### ISSUE THREAD

**Issue by bwitch** [mgba-emu/mgba#1589] opened 2019-12-02 18:54 UTC
every time i restart mGBA i have to select the shaders
it does not save my configuration to **Active Shader**

if I am using a Twin Joystick n.º2 controller, every time I enter I have to select Twin Joystick n.º2
resume - every time I enter it goes back to the default **Twin Joystick n.º1**

**Comment by endrift** [comment] 2019-12-02 18:56
One issue per, uh, issue please. The first issue is a dupe of #1553 and the second is a dupe of #926 (I think; you didn't really describe the issue very well).

**Comment by bwitch** [comment] 2019-12-02 18:59
> Um problema por problema, por favor. A primeira edição é uma mentira do [# 1553](https://github.com/mgba-emu/mgba/issues/1553) e a segunda é uma mentira do [# 926](https://github.com/mgba-emu/mgba/issues/926) (eu acho; você realmente não descreveu a questão muito bem).

I appreciate your answer and apologize for posting wrong or not explaining very well
I'm using the translator, ty

**Comment by endrift** [comment] 2019-12-14 21:17
Please see if the shader configuration is fixed.

**Comment by bwitch** [comment] 2019-12-14 21:22
> Please see if the shader configuration is fixed.

where? update?

**Comment by endrift** [comment] 2019-12-14 21:23
Download one of the builds from the top of this list: https://mgba.io/builds/1/

**Comment by bwitch** [comment] 2019-12-14 21:53
> Download one of the builds from the top of this list in the 5984-2583c5c section: https://mgba.io/builds/1/

yes, I restarted several times, played a little and continued with shaders enabled

**Comment by endrift** [comment] 2019-12-18 19:57
I believe the second issue is now fixed too, please download 5985-0707cc2 and test.

**Comment by endrift** [comment] 2020-08-18 04:12
Closing due to lack of reply.

**Closed by endrift** 2020-08-18 04:12 UTC
Labels: category:needs retest
