### ISSUE TITLE
Port to WASM platform?

### ISSUE THREAD

**Issue by HadesD** [mgba-emu/mgba#1322] opened 2019-02-26 09:43 UTC
I 've compaire mGBA with some another emulator on windows, and mGBA is the best performance emulator.
I think if port to WASM then i can use this API to write my own emu site to playoffline on my phone :)

I'm making mGBA-wasm repo to contrib but do not know so much about mgba code. And if you all will be release a wasm build, then let me know.

Thanks you all.

**Comment by endrift** [comment] 2019-02-26 17:50
Dupe of #1296.

**Closed by endrift** 2019-02-26 17:50 UTC

**Comment by patrickcorrigan** [comment] 2019-11-03 21:04
Any update on this? I'm up for trying to port it too.
