### ISSUE TITLE
I downloaded it and it doesn't open

### ISSUE THREAD

**Issue by RedT6591** [mgba-emu/mgba#2518] opened 2022-05-10 21:48 UTC
I downloaded the mgba onto my lenovo laptop and when i press the open button it doesn't open. I downloaded the windows installer and it doesn't work, is there a fix to this?

**Comment by endrift** [comment] 2022-06-09 07:52
Duplicate of your previous issue...

**Closed by endrift** 2022-06-09 07:52 UTC
