### ISSUE TITLE
Golden Sun blue line with OpenGL video renderer

### ISSUE THREAD

**Issue by bajolzas** [mgba-emu/mgba#1674] opened 2020-02-19 20:43 UTC
With OpenGL video renderer, there appears a blue line in the middle of the screen at the start of every battle on both Golden Sun games.
It doesn't happen with software renderer.

![gs2](https://user-images.githubusercontent.com/51722671/74874142-59615580-5358-11ea-92dc-4fd46e7046cc.png)

**Comment by endrift** [comment] 2020-02-19 20:43
Duplicate of #1631

**Closed by endrift** 2020-02-19 20:43 UTC
