### ISSUE TITLE
[Vita] Aria of Sorrow glitches

### ISSUE THREAD

**Issue by debigulator** [mgba-emu/mgba#333] opened 2016-08-08 21:08 UTC
Hopefully this isn't another framerate issue :). I first ran into one against the [big golem boss](https://www.youtube.com/watch?v=djTnc7liLgk). It would just rotate around the axis on its ankle super fast, and seemed partially invisible. I was able to cheese my way through it using potions. Then when I got to the [headhunter](https://www.youtube.com/watch?v=g1577Lpvojc&index=5&list=PL0A90564BA7457165) where the head and body start flashing, the head just continued moving into the next room and I got locked in, unable to do anything.

**Comment by endrift** [comment] 2016-08-08 21:25
These are quite possibly HLE BIOS bugs. If you have saves still around, please attach them, and also retry those bosses using the official BIOS.

**Comment by debigulator** [comment] 2016-08-09 00:45
[0999 - Castlevania - Aria of Sorrow (U)(GBATemp).ss1.zip](https://github.com/mgba-emu/mgba/files/407991/0999.-.Castlevania.-.Aria.of.Sorrow.U.GBATemp.ss1.zip)

This save is right outside the headhunter. I've been overwriting, so I don't have one for the golem. To use the official bios, do you just stick it in the same folder as the rom like other emulators?

**Comment by yuriks** [comment] 2016-08-09 00:46
FWIW I played through Aria of Sorrow a while back with the HLE BIOS and had no issues with either of those bosses, so if anything it might be a regression in the last 6 months or so.

**Comment by endrift** [comment] 2016-08-09 00:59
@debigulator You put it in ux0:/mGBA/gba_bios.bin, and it should auto detect. If not, you can specify the path manually in the settings.

@yuriks Yeah it could be a regression with the ArcTan2 function; I changed it recently. I might need to grab some tables out of the BIOS and do it by hand :(

**Comment by debigulator** [comment] 2016-08-09 01:07
Using the actual bios fixed it. Thanks!

**Comment by endrift** [comment] 2016-08-13 21:12
Fixed in 6867400ca875277929f8aec1964c99d85cb0e1a9. Turns out one of the math functions I was calling on the Vita is outright broken.

**Closed by endrift** 2016-08-13 21:12 UTC
Labels: bug, GBA, port:vita
