### ISSUE TITLE
Audio popping in Shantae for GameBoy colour 

### ISSUE THREAD

**Issue by kurayami6** [mgba-emu/mgba#1046] opened 2018-04-07 13:26 UTC
There is a loud popping sound every time you enter and leave the save room.

mGBA version 0.7.5071-21d808d0

Windows 7, i5, GTX 970

**Comment by TurdPooCharger** [comment] 2018-04-07 19:45
I think there's been a regression. I notice popping sounds, too, on top of graphical glitches for titles, not necessarily just rom hacks.

**mGBA v1.6.2 stable release, no selected external BIOS:**
- Pokemon Blue & Red Version DX hack - pops at startup. Blank white screen when New Game at professor Oak.
- Metroid II - Return of Samus DX hack - Missing missing and health bar.

- Super Mario Land 2 - 6 Golden Coins (v1.2, original GB rom) - Missing bottom status bar.

**Comment by orbea** [comment] 2018-04-07 23:28
This seems easy to test with `Pokemon Crystal` where the audio will pop as soon as the game boots. It also seems to have been a regression between `0.6.1` and `0.6.2`. I bisected this and found the following commit.
```
commit fd60a1caff2c80ede9c2acda6986dea09abea5f0
Author: Vicki Pfau <vi@endrift.com>
Date:   Sat Jul 8 21:32:51 2017 -0700

    GB Audio: Make audio unsigned with bias (fixes #749)

:100644 100644 a0a8c6eaf7ababbffaa0880ffbc786a6d7cbc101 4c5c8466d754e4789bbc3b9ce7d359074126ad60 M	CHANGES
:040000 040000 c24e964b0d4208c2cc25036f33063d57a76dd45e 916954518f711c1ff0d97723ae013693f7a3908a M	src
```
fd60a1caff2c80ede9c2acda6986dea09abea5f0

**Comment by orbea** [comment] 2018-04-08 00:37
Reverting the above commit also works around this.

**Comment by endrift** [comment] 2018-04-08 03:48
Dupe of #1036.

**Closed by endrift** 2018-04-08 03:48 UTC
