### ISSUE TITLE
mGBA - POKEMON FIRE - 0.9.1 Fast Forward Causing Crashes (Windows X)

### ISSUE THREAD

**Issue by Weberton01** [mgba-emu/mgba#2160] opened 2021-05-05 13:47 UTC
When I use fast forward on the emulator, it causes a crash an unpredictable amount of time after or whenever I turn fast forward off. It might go for five minutes or one minute. All my settings are set to default. Help is appreciated.

**Comment by endrift** [comment] 2021-05-06 18:27
If you have sync to video turned on turn it off. That setting is buggy in 0.9.1.

**Comment by endrift** [comment] 2021-05-24 01:40
Have you tried seeing if it's on and if turning it off to see if it fixes it?

**Comment by endrift** [comment] 2021-06-04 06:02
Closing due to lack of reply, assuming it's a duplicate of #2138.

**Closed by endrift** 2021-06-04 06:02 UTC
Labels: blocked:needs info
