### ISSUE TITLE
OpenGL display driver not working

### ISSUE THREAD

**Issue by worsel99** [mgba-emu/mgba#2966] opened 2023-06-29 11:59 UTC
I cannot load any roms with either OpenGL display driver selected. It will show a white screen, sometimes the rom will play audio after a few seconds, and mGBA will freeze. No problems with the Qt driver, seems to work perfectly. I did not have this issue when I first installed mGBA, I'm not sure what broke it. I have tried reinstalling and tried other builds (originally was on 0.10.2, tried 0.10.1, 0.9.0, and the latest dev build on rev [8144-c5a7b1a](https://github.com/mgba-emu/mgba/commit/c5a7b1a9b7b1581a6cf348cf20d755f5df08dc5a), no difference on any. After installing all available driver updates and restarting, then installing, it worked for loading the first time used. After closing and reopening the problem was back.
Environment: Windows 11 22H2, Intel i712700KF, RTX 3070Ti (Driver 31.0.15.3626)

**Comment by endrift** [comment] 2023-06-29 12:01
Where did you get this Driver version? That's not at all the driver versioning that Nvidia uses. Please use the Report Bug dialog the emulator provides to gather this information correctly.

**Comment by worsel99** [comment] 2023-06-29 12:04
That's the driver version I see in Device Manager. I just updated my drivers through GeForce Experience while seeing if that would fix this, in there the driver version is 536.23.

**Comment by worsel99** [comment] 2023-06-29 12:05
[info.zip](https://github.com/mgba-emu/mgba/files/11905453/info.zip)

**Comment by endrift** [comment] 2023-06-29 12:08
Given that some of these non-working versions have been out for over a year, and we've only received one or two similar bug reports from anyone, I'm inclined to believe that you have something else installed on your system that's breaking mGBA. Every similar bug report we've gotten within that timespan has amounted to that. Do you have anything running that you can think of that might interfere?

**Comment by worsel99** [comment] 2023-06-29 12:12
Just Firefox running, aside from that some system things like ASUS Armory Crate, Corsair iCUE, Xbox Game Bar run in the background.

**Comment by endrift** [comment] 2023-06-29 12:16
I have no idea what those first two are, but basically anything that could hook the graphics, like ReShade, OBS, RTSS, or Xbox Game Bar should be quit first just to check.

**Comment by worsel99** [comment] 2023-06-29 12:22
Not sure if it's useful, but this is the log windows spat out
[Report.wer.txt](https://github.com/mgba-emu/mgba/files/11905534/Report.wer.txt)

**Comment by worsel99** [comment] 2023-06-29 12:23
Tried with all the stuff mentioned above turned off, no change. Also tried turning off game mode in windows settings, didn't help

**Comment by endrift** [comment] 2023-06-30 04:58
I must have misread, I thought you said it was a black screen. Try switching the audio driver; it sounds like it's hanging on that. The OpenGL driver has nothing to do with that. Not sure why the software driver would be any different though.

**Comment by Squall-Leonhart** [comment] 2024-09-15 20:37
This is caused by the nahimic service embedded in Asus's sonic studio.

**Comment by endrift** [comment] 2024-11-24 09:48
Given the thumbs up emoji I'm assuming this was resolved by my suggestion. If not, let me know and I can reopen it.

**Closed by endrift** 2024-11-24 09:48 UTC
Labels: blocked:needs info
