### ISSUE TITLE
[Wii] aspect ratio in Wii version unable to be changed in latest versions

### ISSUE THREAD

**Issue by WaffleJames** [mgba-emu/mgba#1108] opened 2018-06-24 08:45 UTC
In the nightly commit: [c8dacbb](https://github.com/mgba-emu/mgba/commit/c8dacbb6456682351c90b8424966ab466a4fb6e9) I was able to change the aspect ratio in the config.ini file using stretchWidth and stretchHeight. Now, as of nightly commit: [dc753d8](https://github.com/mgba-emu/mgba/commit/dc753d8117161f819f392ad6a667e8800a1e9003) and all nightlies after, I am unable to change the aspect ratio with the config.ini file. The aspect ratio just defaults to some value that is clearly wrong.
I was told that if I post which commit started this issue, it might be fixed. So could this be fixed in some future nightly? I loved this little feature for getting me to that perfect 3:2 aspect ratio, and it made mgba my favorite emulator on the Wii.
Thanks!

**Comment by endrift** [comment] 2018-06-24 08:56
Why did you file this issue twice? Dupe of #1106.

**Closed by endrift** 2018-06-24 08:56 UTC

**Comment by WaffleJames** [comment] 2018-06-24 08:58
I was told that if I posted which commit broke it, it might get it fixed. I thought that meant to post it again with a more detailed explaination. My bad

**Comment by endrift** [comment] 2018-06-24 16:07
Ah, no, since it was in the other bug I could keep track of it. I will probably look into this next week.
