### ISSUE TITLE
MGBA WII: MS Pac Man Maze Madness GFX N Sound Issues + Fan Made GBA Video Issues

### ISSUE THREAD

**Issue by DarthBellic** [mgba-emu/mgba#1939] opened 2020-11-12 11:26 UTC
Ms. Pac Man MM Has GFX the corrupt as they enter/exit the top part of the screen, the music also has a constant crackle to it

![MGBA Report](https://user-images.githubusercontent.com/74355945/98934060-80942000-24af-11eb-8073-b743ebfc2ca7.jpg)

As for GBA Video i find that fan made GBA vid roms will not load with bios set to "on"
if bios is set to "off" they load fine, but in both cases attempting to quit the roms causes the emulator to freeze, forcing me to use the reset button to quit out of the emulator.

Thank you so much for this excellent emulator

**Comment by endrift** [comment] 2020-11-18 03:40
The constant crackle is #875, which was fixed recently (but the fix didn't make it into 0.8.4). I don't appear to be able to reproduce the graphical issue in 0.8.4 though (but I can in 0.7.2).

I don't know of any fanmade GBA video ROMs, so I can't check those without more info.

**Comment by endrift** [comment] 2020-11-19 02:44
Fanmade GBA video fixed in 2def7289f3cb02c3a3edc51e26ce3f634033e264

**Comment by endrift** [comment] 2020-11-20 00:32
Looks like graphical issue was caused by a forwarder using an old version (likely 0.7.2) instead of what was downloaded, so all of the issues mentioned here have since been fixed.

**Closed by endrift** 2020-11-20 00:32 UTC
