### ISSUE TITLE
Can't control when inactive in link mode

### ISSUE THREAD

**Issue by leoxxx** [mgba-emu/mgba#1841] opened 2020-08-05 07:20 UTC
As shown in the title.
Not select "Pause when inactive".
I set different keyboard keys for two windows. Can't control when inactive in link mode with same key setting, too. Just active one can be controlled.
@endrift

**Comment by endrift** [comment] 2020-08-06 09:36
Duplicate of #1378

**Closed by endrift** 2020-08-06 09:36 UTC
