### ISSUE TITLE
ARM64 Linux support in future releases (AppImage, .deb, FlatPak, etc)

### ISSUE THREAD

**Issue by Vortigern-The-Grey** [mgba-emu/mgba#3127] opened 2024-01-29 03:01 UTC
# Support for ARM64 architecture in future releases.
Just a feature suggestion recommending building mGBA for the ARM64 linux architecture.
I use a Raspberry Pi 4B running XFCE on Raspberry Pi OS for a lot of my daily driver tasks, and being able to play gba games on it with the best gba emulator around would be awesome.

soz in advance if this isn't possible or feasible atm

**Comment by endrift** [comment] 2024-01-29 08:21
The biggest limiting factor is build hardware. The only appropriate ARM device I have for building is an M1 Mac Mini, which is used for the macOS builds. I can probably set up a VM on it for one or two builds, but beyond that I'd need more ARM hardware to avoid cross-compiling.

**Comment by Vortigern-The-Grey** [comment] 2024-01-31 04:03
Regarding build hardware, for ARM64 Linux I would recommend using a Raspberry Pi 4 or 5. Relatively cheap, easy to set up.
Alternatively, a ARM64 Linux VM could be use, though I am unsure of its viability, indeed its possibility.

**Comment by endrift** [comment] 2024-02-07 11:44
The problem is less which thing to buy and more just buying and setting it up. The mGBA budget isn't super huge.

Anyway, I've pushed some fixes for OpenGLES in the Qt version and am working on setting up a builder. I should be able to start getting appimage builds up soon, and will look into some Ubuntu images next.

**Comment by JakobDev** [comment] 2024-02-08 13:21
The [Flatpak](https://flathub.org/apps/io.mgba.mGBA) already has a ARM64 build

**Comment by endrift** [comment] 2024-03-19 01:30
Reopening this so I actually remember to finish setting up the ARM64 builder--it's almost done, I just need to finish it.

**Comment by LivexMania** [comment] 2024-05-31 13:00
Hello, does the ARM64 builder would make _pylib works on ARM64 too ?

**Comment by endrift** [comment] 2024-06-17 07:35
AppImage builder finally up--closing this now.

**Closed by endrift** 2024-06-17 07:35 UTC

**Comment by slrgt** [comment] 2024-07-18 18:04
does this mean it is now possible to run mgba on devices like the Miyoo Mini+ so we can play gba games with link cable support?
