### ISSUE TITLE
Sonic Advance 3 ring sprite glitch

### ISSUE THREAD

**Issue by MazeGuardian92** [mgba-emu/mgba#1506] opened 2019-08-18 15:43 UTC
Using mGBA 0.7.2 and playing Sonic Advance 3 on Windows, not using any save states just the battery save, sometimes in specific places the rings will glitch and llok like white boxes with black lines as shown in this screenshot at the top right, there are three boxes where rings should be. Also if I unpause they will go back to looking like rings.
![Sonic Advance 3 (USA) (En,Ja,Fr,De,Es,It)-0](https://user-images.githubusercontent.com/54243345/63226826-1c64ac80-c1d7-11e9-92a4-0518ccaf1e7f.png)

**Comment by endrift** [comment] 2019-08-18 22:00
This is probably a dupe of #1436, please try a dev build.

**Comment by MazeGuardian92** [comment] 2019-08-19 14:46
I've tried the dev build and the rings are now shown correctly. Thanks

**Closed** 2019-08-19 22:41 UTC
