### ISSUE TITLE
Graphical glitch in Medusa

### ISSUE THREAD

**Issue by fizzmaister** [mgba-emu/mgba#835] opened 2017-08-02 06:32 UTC
In Mario and Luigi 2 (Mario and Luigi Partners in Time), the layering in the level up screen is incorrect. The levelup numbers appear behind the banner that they're supposed to be on top of.

**Comment by endrift** [comment] 2017-08-02 15:12
Duplicate of #567

**Closed by endrift** 2017-08-02 15:12 UTC
