### ISSUE TITLE
No ROM is playable without an connected sound output device.

### ISSUE THREAD

**Issue by SatanicSlurpee** [mgba-emu/mgba#2677] opened 2022-10-10 17:56 UTC
Title shoud be self explainatory. discovered it randomly when i forgot to turn on my headphones.
It might be problem if someone doesn't have an acces to any sound device at the moment,
People might as well unnecesarily delete their configs as this was one of the supposedd fixes i found.

I don't think report will be of any use but i might as well upload it.
[report.zip](https://github.com/mgba-emu/mgba/files/9748000/report.zip)

**Comment by endrift** [comment] 2022-10-10 20:40
Duplicate of #280

**Closed** 2022-10-10 20:40 UTC
