### ISSUE TITLE
Donkey Kong GB: Dinky Kong & Dixie Kong - severe gameplay glitches upon entering the water in the first level

### ISSUE THREAD

**Issue by GeekyFerret** [mgba-emu/mgba#720] opened 2017-04-28 19:23 UTC
When you jump into the water in the first level the game will start spawning random objects throughout the level and will suffer from intermittent pauses.

**Comment by endrift** [comment] 2017-05-31 07:14
There is no game by this name. The closest I can find is Donkey Kong Land 2, which stars Diddy Kong and Dixie Kong, but the first level does not have water.

**Comment by endrift** [comment] 2017-05-31 07:22
I cannot reproduce this issue. Seems to work fine on my end. Are you sure you have a good dump?

**Comment by GeekyFerret** [comment] 2017-06-04 01:18
The md5 of mine is 3ADE99CDF4349D3F7D1C273A7F008E3B

**Comment by endrift** [comment] 2017-06-04 01:22
Are you using 0.5.x or a nightly?

The md5sum I have is 22afe691095c65f34aeaba3c283b2a9c.

**Comment by GeekyFerret** [comment] 2017-06-04 22:15
I found a dump with an md5 of 22AFE691095C65F34AEABA3C283B2A9C.

I tested it in the 2017-06-04 64 bit and 32 bit windows nightlies and the issue is still present in both. I also tested it in the 3DS and Wii nightlies as well and it's present in those too.

I also found an additional bug in the Wii build: if you get hit by an enemy, the emulator will freeze for a few seconds before going into fast forward mode.

**Comment by endrift** [comment] 2019-06-06 05:12
There have been lots of GB fixes in the past two years, can you please retest?

**Comment by benderscruffy** [comment] 2019-06-07 07:02
just tested it no problem with the mention problems above
the only problem was the graphics are all messed up in software mode
![dkc](https://user-images.githubusercontent.com/2696404/59086749-3c553580-8935-11e9-92cb-925497918117.PNG)

**Comment by endrift** [comment] 2019-06-07 07:03
Looks like an issue with the video stride being wrong. By software mode you mean Software (Qt) Display Driver?

**Comment by benderscruffy** [comment] 2019-06-07 07:06
yes

**Comment by endrift** [comment] 2019-06-07 07:16
Ok, I have a fix fo that. I'll push it in part of a batch of fixes tomorrow.

**Comment by benderscruffy** [comment] 2019-06-07 07:19
ok nice work
you can close it whenever

**Comment by benderscruffy** [comment] 2019-06-08 00:59
fixed can be closed

**Comment by Testsr** [comment] 2020-11-11 01:57
Should be  closed @endrift.

**Comment by endrift** [comment] 2020-11-11 01:59
I don't think anyone was able to reproduce @GeekyFerret's original issue. Nonetheless, the request for him to retest was met with no reply.

**Closed by endrift** 2020-11-11 01:59 UTC
Labels: category:questionable, platform:GB/GBC
