### ISSUE TITLE
Game performance degraded when upgrading from 0.6.3 to 0.7.0

### ISSUE THREAD

**Issue by hugojmaia** [mgba-emu/mgba#1313] opened 2019-02-21 00:25 UTC
Today I decided to run the sweep of blaarg roms on the mGBA I had on my 3ds. Results were good and when I shared them I learned there was a newer version.
I update and re-run the tests, mostly the same results except for 7 failing on both sound tests.
People tell me "It's no big deal, it's probably something that won't be noticed in normal play".
I boot up crystal clear and as soon as leave the pokémon center into Olivine city I notice the difference.
On 0.6.3 I had 59.89 fps and perfect sound. On 0.7.0 I had 50.41 fps and choppy sound.

This was run on a 3DS XL running the Sys 11.9.0-42U firmware that was originally hacked on 9.0.0-something.

**Comment by endrift** [comment] 2019-02-21 00:37
3dsx or CIA? CFW or no?

**Comment by endrift** [comment] 2019-02-21 00:37
Probably a dupe of #1264, though I was never able to reproduce on 3DS.

**Comment by hugojmaia** [comment] 2019-02-21 10:41
CFW and CIA. As far as I know my 3DS is refered to as the o3DS, it has weaker hardware when compared with the n3DS line.

**Comment by Astrinus** [comment] 2019-02-28 17:56
Also, Fast-Forward seems not to work anymore (stuck around 59.9-60.5 fps even when selecting 3x fast-forward speed)

**Comment by endrift** [comment] 2020-01-02 01:41
This may have been fixed in ad870aa26b872f3ccf3ec535bc0b674fa067f8b3, please confirm.

**Comment by hugojmaia** [comment] 2020-01-21 15:59
Testing done with those roms:
[gb-test-roms-master.zip](https://github.com/mgba-emu/mgba/files/4091797/gb-test-roms-master.zip)
Results:
[mGBA-0.6.3-3ds.zip](https://github.com/mgba-emu/mgba/files/4091798/mGBA-0.6.3-3ds.zip)
[mGBA-0.7.0-3ds.zip](https://github.com/mgba-emu/mgba/files/4091799/mGBA-0.7.0-3ds.zip)
[mGBA-0.8-b1-3ds.zip](https://github.com/mgba-emu/mgba/files/4091800/mGBA-0.8-b1-3ds.zip)
And then I decided to do a more practical test using pokemon prism. (Only gbc game I had left there).
The S.S. Anne music makes heavy use of sound 7 so it makes for a clear day and night comparison.
On version 0.6.3 it gets anywhere between 58 and 59.9 fps.
On versions 0.7.0 all the way to the current 0.8 it won't hit 50 fps with very broken sound.
Here's my save file for prism version 235 (Rom not included) in case anyone wanna test, save point is in front of the battle arcade, just go down 2 screens to get the S.S. Anne music.
[Pokemon Prism.zip](https://github.com/mgba-emu/mgba/files/4091848/Pokemon.Prism.zip)

As far as GBC emulation is concerned, no improvements have been made since sound 7 broke when leaving 0.6.3.
As for GBA emulation, I tried Castlevania Aria of Sorrow and got 45~50 fps with choppy sound. Although the only way I've managed to get GBA games running on the 3ds has been through VC injects. And as a bonus to that NSUI doesn't work on linux.

My testing platform is an o3DS XL, running Luma3DS v10.0.1 CFW.
Just for fun I booted BGB using wine and it's running prism with no issues at all.

**Closed** 2021-03-19 01:53 UTC
Labels: platform:GB/GBC, system:3DS

**Comment by endrift** [comment] 2021-03-19 01:57
The biggest regression was caused by me un-batching channel 4 audio. This is now reimplemented, though other things have gotten a little slower since.
