### ISSUE TITLE
Super Mario Advance 4 crashes with Color Restoration hack on mGBA.

### ISSUE THREAD

**Issue by ShadowOne333** [mgba-emu/mgba#526] opened 2017-02-14 16:09 UTC
If the recently released [Color Restoration hack for Super Mario Advance 4](http://www.romhacking.net/hacks/3315/) is applied over a clean Super Mario Advance 4 - Super Mario Bros. 3 (USA, Australia) (Rev 1) (SHA-1:  532F3307021637474B6DD37DA059CA360F612337), the game freezes when loading any kind of level on the message "MARIO/LUIGI START!" and doesn't respond after that.

The SHA-1 of the ROM after applying the patch is 1091017b32ae99d466b4ca4434fe3291c2a136d3.
I believe this might have something to do with the ROM forcing a Gameboy Player mode to achieve the palette restoration, according to the hack's description page.

> Unlike the other palette hacks for GBA games, where hackers had to put in the time and dedication to restore the original SNES palettes, Super Mario Bros. 3 actually already includes the original palette, which is enabled when playing on a Game Boy Player. **This hack simply forces the GBP palette to be used at all times.**

**Comment by vaguerant** [comment] 2017-02-14 16:16
Duplicate of #520. (Also, hi, glad people are using the patch.)

**Comment by endrift** [comment] 2017-02-14 17:28
Yep, vaguerant and I had been discussing this in IRC.

**Closed by endrift** 2017-02-14 17:28 UTC
Labels: duplicate
