### ISSUE TITLE
Pops in audio of M&L:SS

### ISSUE THREAD

**Issue by waddlesplash** [mgba-emu/mgba#546] opened 2017-03-22 23:09 UTC
Easily noticed with headphones on Stardust Fields and the warp pipe music at least. (haven't gotten farther so can't say where else)

I can make a recording if you're unable to reproduce.

**Comment by sergiobenrocha2** [comment] 2017-03-22 23:10
Pokemon Emerald, go to a region you can change the route easily (i'm testing in route 118 / 123), you'll notice some noise in the transition

You can notice too in the Continue screen, when the music is ending/fading

**Comment by rootfather** [comment] 2017-04-04 15:27
I have similar clicking issues in the Pokémon Crystal intro. At the beginning, you hear a clicking/crackling noise when the Unowns appeared.

I'll make a recording soon and upload it to Youtube.

**Comment by waddlesplash** [comment] 2017-04-04 15:38
Yep, the pops are exactly what I'm experiencing.

**Comment by MWisBest** [comment] 2017-04-07 15:50
This may be a duplicate of #461 . If you change the FPS target to 60 instead of Native (59.7), do the pops become much less frequent?

**Comment by waddlesplash** [comment] 2017-04-07 15:53
My FPS target is already set to 60. I changed it to 59.7, and the pops are just as frequent.

**Comment by rootfather** [comment] 2017-04-07 21:35
Same here. No changes between 59.7 and 60 FPS.

**Comment by CharlesCorrin** [comment] 2017-04-08 21:41
Take note please: At some point my PC stopped behaving differently on different FPS settings. For whatever reason. Now both settings pop the same as the 60 FPS setting did before (and it was the option with less popping). Which is not too bad, but still noticeable. I still use the Mother 3 title screen for testing.

**Comment by endrift** [comment] 2017-04-21 23:07
Can you try bisecting this?

**Comment by sergiobenrocha2** [comment] 2017-04-25 01:52
It started with 8ac6f83

**Comment by endrift** [comment] 2017-06-17 16:14
Audio popping is coming from PSG channel 1. It makes a pop every time it plays a note.

**Closed** 2017-06-17 16:45 UTC
Labels: audio

**Comment by endrift** [comment] 2017-06-17 16:49
Note that this fixes many but not all of the audio issues with Crystal. And yeah the grass effect sounds wrong to me, but I haven't confirmed it yet.
