### ISSUE TITLE
Multiplayer issues

### ISSUE THREAD

**Issue by 3FzhlD** [mgba-emu/mgba#2748] opened 2022-12-10 15:32 UTC
Can I have multiplayer under one keyboard? Multiple multiplayer windows, only the currently active window can receive keyboard commands, other windows cannot, perhaps you can set up a few more sets of operation schemes for the keyboard to solve this problem.

**Comment by RetroEdit** [comment] 2024-07-14 18:00
Duplicate of #276 .

**Closed by RetroEdit** 2024-07-14 18:00 UTC
Labels: resolution:duplicate
