### ISSUE TITLE
Some issues for Summon Night - Craft Sword Monogatari - Hajimari no Ishi Chinese translational rom

### ISSUE THREAD

**Issue by leoxxx** [mgba-emu/mgba#3143] opened 2024-02-15 10:37 UTC
ROM Info
Game name:(unknown) 
Internal name:CRAFTSWORD H 
Game ID:AGB-B3CJ 
File size:33554432 bytes 
CRC32:6a5b099a 

My boy is O.K.

VBA: Bgm have some issue at beginnig of the battle.

https://github.com/mgba-emu/mgba/assets/5364709/5639a573-c784-4fa5-b1e4-d87dd41f1419

mgba: It will lag when enemies ≥3.  Missing some voice when battle with a character.

https://github.com/mgba-emu/mgba/assets/5364709/9fa154d0-3e45-497c-aef5-2a41b71e9547

**Comment by endrift** [comment] 2024-02-15 10:38
Don't upload ROMs. Also you need to describe the issues.

**Comment by leoxxx** [comment] 2024-02-15 10:46
> Don't upload ROMs. Also you need to describe the issues.

I am sorry.I see.

**Comment by leoxxx** [comment] 2024-02-17 02:11
Upload the video.

**Comment by leoxxx** [comment] 2024-03-20 02:32
Can you fix it, Cofflag?
I found mgba force close when playing it once.

**Comment by Hambaka** [comment] 2024-04-14 17:42
I mean Cofflag already provided the solution, and it works. This problem can be fixed by editing the rom, you can use a hex editor like HxD to change this value from 00 to its original value in Japanese version: 14. 

![HxD_1BA0](https://github.com/mgba-emu/mgba/assets/20476755/a990fdb3-6b98-4cc6-ba19-4ec361f3e358)

就照着 Cofflag 说的做，用`HxD`这类的十六进制编辑器把汉化版的`1BA0`的值从`00`改成日版原始值`14`就修好了。

至少我这边修改后简单测试的结果，3个及以上敌人的战斗没有再遇到卡顿问题，你可以试试。

**Comment by Hambaka** [comment] 2024-04-14 18:10
Before`(mGBA 0.10.3)`:

https://github.com/mgba-emu/mgba/assets/20476755/9b7b54e4-393b-4fdb-95e5-b2c15245cee1

After`(mGBA 0.10.3)`:

https://github.com/mgba-emu/mgba/assets/20476755/79f99053-7d53-4007-8152-8134beb02e40

**Comment by endrift** [comment] 2024-04-14 22:48
I finally tested this on a real GBA and can confirm that the issue is the ROM hack itself, not mGBA.

**Closed by endrift** 2024-04-14 22:48 UTC
Labels: blocked:needs info, software:romhack, pending

**Comment by leoxxx** [comment] 2024-04-15 10:19
> I mean Cofflag already provided the solution, and it works. This problem can be fixed by editing the rom, you can use a hex editor like HxD to change this value from 00 to its original value in Japanese version: 14.
> 
> ![HxD_1BA0](https://private-user-images.githubusercontent.com/20476755/322292328-a990fdb3-6b98-4cc6-ba19-4ec361f3e358.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzY2MTYsIm5iZiI6MTcxMzE3NjMxNiwicGF0aCI6Ii8yMDQ3Njc1NS8zMjIyOTIzMjgtYTk5MGZkYjMtNmI5OC00Y2M2LWJhMTktNGVjMzYxZjNlMzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDEwMTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ODhmYzE4ODU3MTAzYmJiZDEyYjViNzA3ZWJiYjAzN2M1MzgxMzk5YTc2OTFhM2Y2YzdmYjA0MDRlOTk1MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mnEnWGhcTqMtiXiN9OXz1eshkS5c58Ph2jjeJ0uW_Ns)
> 
> 就照着 Cofflag 说的做，用`HxD`这类的十六进制编辑器把汉化版的`1BA0`的值从`00`改成日版原始值`14`就修好了。
> 
> 至少我这边修改后简单测试的结果，3个及以上敌人的战斗没有再遇到卡顿问题，你可以试试。

谢谢，我去试试。

**Comment by leoxxx** [comment] 2024-04-15 10:50
@Hambaka 
你好，请问有没有其它的联系方试。有一个和这里不相关的汉化问题想请教一下。
