### ISSUE TITLE
[Question]The acceleration function is sometimes not smooth

### ISSUE THREAD

**Issue by salamabici-602** [mgba-emu/mgba#3349] opened 2024-11-19 11:53 UTC
When I use the acceleration function of this emulator, when I accelerate to triple speed(180fps), quadruple speed(240fps) and higher speed, the picture seems to become unsmooth, my computer screen refresh rate is 165Hz, when I enable double speed to accelerate the game(120fps), it is very smooth, I noticed that the frame rate displayed by the emulator will be obvious if the acceleration exceeds my screen refresh rate, I hope someone can help me to solve it.

**Comment by endrift** [comment] 2024-11-19 12:24
I'm not sure what to say here. If the speed exceeds the refresh rate, frames will be visibly dropped, leading to it looking less smooth. That's just how that works regardless of thing. I dunno if it's worse than just 15 frames dropped per second at 180 fps but I can't really tell without some sort of recording.

Anyway, this is not a troubleshooting forum, it's a bug report page, and I don't think this is a bug (and if it is it's probably a duplicate of #827

**Closed by endrift** 2024-11-19 12:24 UTC
