### ISSUE TITLE
Game Boy/Color Games Fail to Load 

### ISSUE THREAD

**Issue by Burnt-Lasagna** [mgba-emu/mgba#481] opened 2016-12-19 16:53 UTC
It seems after 0.5.0 Wii builds of mGBA fail to load GB/C games (receive a code dump when loading).
The two games I've tested this with is Link's Awakening (USA) and Metal Gear Solid (USA). Both games worked (or at least started) prior to 0.5.0.

Others have told me that some games still load but it appears that a large portion of the library is dysfunctional now.

**Comment by JMC47** [comment] 2016-12-19 18:26
Is this reproduce-able in Dolphin?  If so, I can probably confirm this.  It'd also make it easier for endrift to debug it if it happens there.

**Comment by endrift** [comment] 2016-12-19 19:06
This was fixed quite a while ago. I don't recall if it was fixed in 0.5.1 (why does no one seem to realize 0.5.1 is out, and has been for months?), but it's certainly fixed in the nightlies.

**Comment by endrift** [comment] 2016-12-21 01:55
Nevermind, it looks like it is still broken.

**Comment by endrift** [comment] 2016-12-21 02:06
It appears I never committed the fix. It's applied now in b5c62da07088347e8329cd27e130d7b7c3a315f3.

**Closed by endrift** 2016-12-21 02:06 UTC
