### ISSUE TITLE
Fast-forward appears to be frame-skipping

### ISSUE THREAD

**Issue by Obnoxygen** [mgba-emu/mgba#3387] opened 2024-12-28 03:31 UTC
Hi! I'm playing Pokemon FireRed using the latest version of mGBA on Windows 11.

The issue is whenever I enable the fast-forward option (bounded to 2x), the game does speed up, but it becomes very choppy/laggy, as if the frame-skip option was enabled (even though I set it to 0). I've tried using VBA-M to check if the same thing happens there. However, it seems that VBA-M handles fast-forwarding slightly differently, since its fast-forward setting has its own frame-skipping option aside from the general frame-skip setting. When I enabled that frame-skip under the fast-forward, it runs exactly like the fast-forward of mGBA in terms of choppiness. But when I disabled it, it was still twice as fast (in terms of speed), yet now smooth. Thus, I have this guess that maybe the frame-skipping is automatically enabled when fast-forwarding in mGBA, resulting in the choppiness.

**Comment by endrift** [comment] 2024-12-29 05:10
Fast-forward _requires_ frameskip on any monitor that runs less than 2× the rate of the system, as otherwise it would have to display more than one frame per frame. What monitor are you using? What is the "expected" behavior here? "Smooth" and "choppy" are too vague to be actionable without concrete points of comparison.

**Comment by Obnoxygen** [comment] 2024-12-29 09:02
Hello, thanks for the response. Someone who is also facing the same issue uploaded videos showing the choppiness during fast-forward. Here is the link: https://github.com/mgba-emu/mgba/issues/2549#issuecomment-2564424008

Also, in VBA-M and Retroarch (mGBA core), the fast-forward is smooth (unlike in those linked videos).

**Comment by endrift** [comment] 2024-12-29 09:19
Ah, if it's a duplicate of #2549 then I'll keep that one over this since it has more info.

**Closed by endrift** 2024-12-29 09:19 UTC
