### ISSUE TITLE
AppImage won't open on Wayland

### ISSUE THREAD

**Issue by DisasterArea96** [mgba-emu/mgba#3088] opened 2023-12-16 22:18 UTC
Heya,

Appear to be having an issue after switching over to Wayland after previously being on x11, using Debian 12.

When I try and run the AppImage via the command line, I get the following error:

/home/george/ProgramFiles/AppImageFiles/mGBA-0.10.2-appimage-x64.AppImage: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags

Some googling, it appears wl_proxy_marshal_flags is related to wayland in some way, and previously I was able to launch the appimage while on x11.

Edit: Have just switched back over to x11 and I am able to utilise the mGBA AppImage with no problem, so the issue is definitely wayland-related in some way.

**Comment by dpanter** [comment] 2023-12-21 14:54
`QT_QPA_PLATFORM=xcb`

Setting this environment variable allows both 0.10.2 and the current dev build to run in KDE Plasma/Wayland, tested on Siduction (Debian sid base)

**Comment by endrift** [comment] 2023-12-29 11:10
I believe this is the same root cause as #2996, as I saw the same error in ld.so logs when attempting to debug it.

I believe this is fixed in this dev build, please download it and test it: https://s3.amazonaws.com/mgba/build/mGBA-build-2023-12-29-appimage-x64-8282-d83b2f99cd3d35509cf110bb47cbc72f569a31ed.appimage

**Comment by dpanter** [comment] 2023-12-29 14:26
> I believe this is the same root cause as #2996, as I saw the same error in ld.so logs when attempting to debug it.
> 
> I believe this is fixed in this dev build, please download it and test it: https://s3.amazonaws.com/mgba/build/mGBA-build-2023-12-29-appimage-x64-8282-d83b2f99cd3d35509cf110bb47cbc72f569a31ed.appimage

Confirmed, this new dev build works properly on my system in all three scenarios noted below.

`QT_QPA_PLATFORM` unset or set to `wayland` -> native Wayland window.
Set to `xcb` -> XWayland window.

**Closed** 2023-12-29 21:54 UTC
Labels: blocked:needs retest
