### ISSUE TITLE
mGBA: Kirby: Nightmare in Dreamland

### ISSUE THREAD

**Issue by Reinc01** [mgba-emu/mgba#1583] opened 2019-11-26 11:08 UTC
Kirby: Nightmare in Dreamland crashes at the beginning of level 3, stage 4. I was playing using the mGBA core of the Bizhawk emulator.

[Kirby - Nightmare in Dream crash.zip](https://github.com/mgba-emu/mgba/files/3891507/Kirby.-.Nightmare.in.Dream.crash.zip)

**Comment by RetroEdit** [comment] 2019-12-20 02:40
This appears to have been fixed in 0.7.3. I can reproduce in 0.7.2, and in Bizhawk (the most recent Bizhawk uses 0.7.2, and I can reproduce it there, too). It does not reproduce in 0.7.3.

**Comment by endrift** [comment] 2019-12-20 23:47
Yes, this does appear to be caused by an emulation bug fixed in 0.7.3.

**Closed by endrift** 2019-12-20 23:47 UTC
