### ISSUE TITLE
[Feature Request] Add option to map multiple inputs to the same button in the emulator

### ISSUE THREAD

**Issue by Clozent** [mgba-emu/mgba#2984] opened 2023-07-19 10:21 UTC
I tried connecting a Switch Pro Controller to play, and found out that I can't have both my d-pad and left stick mapped to the GBA d-pad at the same time, and the X and Y buttons are useless, and I can't map both X and B to the GBA B button, for example.
This would be great quality of life feature.

**Comment by endrift** [comment] 2023-07-20 06:30
> I tried connecting a Switch Pro Controller to play, and found out that I can't have both my d-pad and left stick mapped to the GBA d-pad at the same time

Yes you can

> and the X and Y buttons are useless

What do you mean by useless?

> and I can't map both X and B to the GBA B button, for example. This would be great quality of life feature.

This is a duplicate of #87, which I hope to resolve somewhat soon.

**Closed by endrift** 2023-07-20 06:30 UTC
