### ISSUE TITLE
[Switch] Add Gameboy model to emulate

### ISSUE THREAD

**Issue by RetroMarioBros** [mgba-emu/mgba#1944] opened 2020-11-19 13:22 UTC
It is not possible to select the GB model to emulate on this system
for example select (without removing the bios path) 
-gameboy advance for Zelda games
-gameboy or gameboy color on pokemon games
![2020111914092000-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/6499349/99671037-c33a9700-2a71-11eb-8689-74542cb95223.jpg)

**Comment by endrift** [comment] 2020-11-20 07:21
The GUI code is shared with the 3DS, so this is a duplicate of #1697.

**Closed by endrift** 2020-11-20 07:21 UTC
