### ISSUE TITLE
Screen doesn't update when using OpenGL

### ISSUE THREAD

**Issue by Heath123** [mgba-emu/mgba#2463] opened 2022-02-28 12:01 UTC
When launching mGBA with "Display driver" set to anything oter than "Software (Qt)", the emulator shows a blank screen, though the game is running and audio can be heard. Pausing the game or doing similar actions causes the screen to update and show a single frame from the game. Using the build from https://archlinux.org/packages/community/x86_64/mgba-qt/

![image](https://user-images.githubusercontent.com/13787163/155979871-6b7a6c41-dbc3-47b6-bc1d-518c56794ad0.png)

Hardware/OS info: Arch Linux, Ryzen 7 5700U, Mesa open-source drivers

[report.zip](https://github.com/mgba-emu/mgba/files/8153097/report.zip)

**Comment by endrift** [comment] 2022-02-28 12:03
Hmmm...are you using GNOME Shell + Wayland by any chance?

**Comment by endrift** [comment] 2022-02-28 12:04
If you could, please. There's an existing bug where it fails on Wayland, but I haven't been able to reproduce yet: #2190

**Comment by Heath123** [comment] 2022-02-28 12:04
Setting `QT_QPA_PLATFORM=xcb` does fix the issue

**Comment by endrift** [comment] 2022-02-28 12:05
It would appear this is a duplicate of #2190 then, which I'm still trying to figure out how to fix.

**Closed by endrift** 2022-02-28 12:05 UTC
