### ISSUE TITLE
Updater Settings Don't Save, Doesn't Update mgba

### ISSUE THREAD

**Issue by joshvickerson** [mgba-emu/mgba#2788] opened 2023-01-15 04:07 UTC
Changing the Update settings from the Development channel to the Stable channel doesn't persist. When I change the channel to Stable and click Apply, the settings window loses focus, but it does recheck for updates and correctly shows 0.10.1 is available. If I click OK, then restart the app, the setting reverts to the Development channel.

If I attempt to install 0.10.1 with the updater, it downloads, says it will restart to install the update but it never restarts on its own. When I launch the app again, it's still version 0.10.0.

Windows 11 (22H2), mgba 0.10.0 (Win64, installed)

**Comment by endrift** [comment] 2023-01-15 04:08
does it drop the file anywhere? Is this a portable or installed version?

**Comment by joshvickerson** [comment] 2023-01-15 04:13
It does - the file `update-.10.1-win64-installer.exe` is placed in `\AppData\Roaming\mGBA`. This is the installed version, 64-bit.

**Comment by endrift** [comment] 2023-01-15 04:14
Duplicate of #2681.

**Closed by endrift** 2023-01-15 04:14 UTC
