### ISSUE TITLE
Red Coin Sound Missing in SM64

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#589] opened 2017-04-09 21:20 UTC
Pick up a red coin and only the normal coin pickup sound plays.

**Comment by waddlesplash** [comment] 2017-04-09 21:21
98.6% chance this is a dupe of #574.

**Comment by endrift** [comment] 2017-04-09 21:21
Almost certainly.

**Comment by endrift** [comment] 2017-04-11 03:45
Fixed in e9c1a53cfbf03252db40b5a19b830f8eb968c684.

**Closed by endrift** 2017-04-11 03:45 UTC
Labels: DS
