### ISSUE TITLE
Feature Request: Expanded Multiple Buttons/Keys per Game Boy Button Combination Options.

### ISSUE THREAD

**Issue by ibercee** [mgba-emu/mgba#3014] opened 2023-08-28 11:51 UTC
Hello, if I may, I would like to share that the desktop version of mGBA has some limitations in its input settings:

It is not possible to combine together:
   1.  _A_, _B_, _X_, _Y_, _L_, _R_, _D-Pad_, _Start_, _Select_, _Home_, _Capture_
   2.  _ZR_ **+** _ZR_
   3. _L Stick_ **+** _R Stick_ (i.e. To use both Sticks as the Game Boy _D-Pad_)

On the other hand, it is possible to combine together:
1. (_A_, _B_, _X_, _Y_, _L_, _R_, _D-Pad_, _Start_, _Select_, _Home_ or _Capture_) **+** (_ZR_,  _ZL_,  _L Stick_ or _R Stick_)
2.  (_ZR_ or _ZL_) **+** (_L Stick_ or _R Stick_)

Therefore, I would like to request the ability to create more complex input combinations, without the restrictions listed above.
Ideally, combinations of up to 3 buttons would be supported.
The most obvious case being able to use the Game Boy _D-Pad_ with both, the _L_ and _R Sticks_, as well as the _D-Pad_).

Additionally here are my use cases:

1. For most games, I would like to be able to assign the buttons the following way:
    _A_ from Game Boy -> _A_ and _X_ from my controller.
    _B_ from Game Boy -> _B_ and _Y_ from my controller.

2. In Mario & Luigi: Superstar Saga (GBA), the _Start_ button is used to swap the positions of Mario and Luigi.
However, on a Switch Pro Controller, pressing the _Start_ button can be challenging, due to its less accessible location and stiffer feel.
Because of this, I would like to assign the Game Boy _Start_ button to both, the _Start_ and _X_ buttons on my controller, for convenience.

This QoL feature would provide users with greater flexibility and customization, resulting in an improved gameplay experience.
Although I have only mentioned controllers, I believe that keyboard users should receive the same treatment.

Thank you very much! 😃

**Comment by endrift** [comment] 2023-08-28 20:19
Duplicate of #87 -- it's been open for a while but I do intend to get to it.

**Closed by endrift** 2023-08-28 20:19 UTC
