### ISSUE TITLE
Save State File not working

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#2237] opened 2021-07-08 17:39 UTC
Using this feature only results in the emulator creating a blank savestate file.
Like this:
	0000 0000 0000 0000 0000 0000 0000 0000
	0000 0000 0000 0000 0000 0000 0000 0000
	0000 0000 0000 0000 0000 0000 0000 0000
	0000 0000 0000 0000 0000 0000 0000 0000
	0000 0000 0000 0000 0000 0000 0000 0000
	0000 0000 0000 0000 0000 0000 0000 0000
	0000 0000 0000 0000 0000 0000 0000 0000
	0000 0000 0000 0000 0000 0000 0000 0000

0.10-7059-558f644fd
Window 10 64-bit

**Comment by endrift** [comment] 2021-07-08 19:52
It's working for me, so I'm gonna need a hell of a lot more info. Please attach the bug report zip at the very least.

**Comment by SSpeed01** [comment] 2021-07-09 15:39
more informations:
- The issue occurred on both games that I tried it with - Pokemon Unbound and Advance Wars Returns.
- I attempted to use 'Save state file' over the 5th savestate slot of the game, but the results are as shown below.


[bug report.zip](https://github.com/mgba-emu/mgba/files/6792258/bug.report.zip)

![0](https://user-images.githubusercontent.com/53837164/125102816-b246a080-e0a9-11eb-9583-5cafdfdc3fe9.png)

![1](https://user-images.githubusercontent.com/53837164/125101976-cdfd7700-e0a8-11eb-9ed0-b9fa51cfa5a4.png)

![2a](https://user-images.githubusercontent.com/53837164/125100809-84605c80-e0a7-11eb-91f1-1ffd5bf0c287.png)

![2b](https://user-images.githubusercontent.com/53837164/125100826-87f3e380-e0a7-11eb-83e5-2ab66ba651a4.png)

**Comment by endrift** [comment] 2023-04-13 09:39
Since the user deleted their account, and I've never gotten any other reports like this nor any capacity to reproduce it, I kind of have to close it. However, my best guess is that something was going wrong with OneDrive integration (or whichever sync program was in use).

**Closed by endrift** 2023-04-13 09:39 UTC
Labels: blocked:needs info
