### ISSUE TITLE
pokemon leaf green fast fowarding crash

### ISSUE THREAD

**Issue by Celiois** [mgba-emu/mgba#2236] opened 2021-07-08 01:44 UTC
In Pokemon Leaf Green, if you fast forward, for what seems like a random amount of time, then it crashes. The emulator or something might just be overloaded bc of the fast forwarding, but I wouldn't know.
[pkmnlg.zip](https://github.com/mgba-emu/mgba/files/6780874/pkmnlg.zip)

**Comment by endrift** [comment] 2021-07-08 01:51
Duplicate of #2137 (which got deleted, so you'll find more info in #2138).

**Comment by Celiois** [comment] 2021-07-08 03:15
it isnt tho
this isnt about the cpu, its about fast fowarding causing crashes
if you are having the same problem as me, i found a solution:
just set the fast fowarding speed cap to 5x
Which you go to:
Tools -> Settings -> Emulation, and after that it's at the top and check off "Unbounded" and put the speed cap at 5x, which is the default, you can try more but idk about it.

**Comment by endrift** [comment] 2021-07-08 03:17
You...didn't read enough of the replies. Turn off sync to video.

**Comment by Celiois** [comment] 2021-07-08 03:20
it is off, it was always off

**Comment by endrift** [comment] 2021-07-08 03:21
Alright, try downloading a development build from the website and let me know if it's fixed in that. I'm going to be releasing 0.9.2 soon which has some fixes that are currently only available in the development builds.

**Comment by Celiois** [comment] 2021-07-08 03:32
yeah, it still is a problem

**Comment by Celiois** [comment] 2021-07-08 03:33
it might be caused by switching off of fast forward and moving at the same time

**Comment by Celiois** [comment] 2021-07-08 03:33
im going to try to recreate it for testing

**Comment by Celiois** [comment] 2021-07-08 03:34
oh yeah btw if i didnt make it clear, it crashes the emulator, not freezes the game

**Comment by endrift** [comment] 2021-07-08 03:35
Does it crash the emulator or just hang it? They're different and have different meanings from a development point of view.

**Comment by Celiois** [comment] 2021-07-08 03:35
well, technically it freezes the game, and you can use the emulator, but once you select an option on the menu, it stops working and you have to end the process in task manager

**Comment by endrift** [comment] 2021-07-08 03:35
Ok, that's a hang. It's probably deadlocking for some reason. So to confirm you were able to make it hang in the development build?

**Comment by Celiois** [comment] 2021-07-08 03:36
yeah

**Comment by Celiois** [comment] 2021-07-08 03:38
ok it seems to just happen randomly, and the previous hypothesis mightve been wrong, since it doesnt happen consistently

**Comment by fancythedeveloper** [comment] 2021-07-08 03:56
your issue sounds like something i had pretty recently as well but with Pokemon Emerald instead of LeafGreen, maybe test this with other games and see if its not just an issue with the Gen 3 Pokemon games?

**Comment by endrift** [comment] 2021-07-08 03:57
It's almost certainly every game.

**Comment by Celiois** [comment] 2021-07-08 04:01
it wasn't an issue with pokemon clover, a fan game of fire red, when i was playing it

**Comment by endrift** [comment] 2021-07-09 10:17
Can you try downloading 7061 or newer (if applicable) from this page to see if it's fixed now? https://mgba.io/builds/1/

**Comment by Celiois** [comment] 2021-07-11 02:15
yeah, i just saw this since i was away from my pc for a while

**Comment by endrift** [comment] 2021-07-11 02:30
Does that "yeah" mean "yeah I checked and it's fixed"?

**Comment by Celiois** [comment] 2021-07-11 02:40
no, that "yeah" means, "ok i will do it"

**Comment by Celiois** [comment] 2021-07-11 02:46
i couldn't recreate it after 30 minutes, so it should be fixed

**Comment by endrift** [comment] 2021-07-11 02:48
Perfect, thanks. I wasn't able to reproduce it myself but I was able to get it to hang when exiting if I'd been fast forwarding for too long. FIxed in d202cddd1b781bc36c09a4b12d41ad2ae69191b6.

**Closed by endrift** 2021-07-11 02:48 UTC
Labels: port:Qt

**Comment by Celiois** [comment] 2022-11-24 16:57
Holy crap this was so long ago, but I found a fix if I haven't already said it in this thread.
Try setting your fast forward speed to a limit instead of unbounded, I usually do 5x since I can still move.
If it is still crashing, then ig it is an issue again.

**Comment by NoisyFlake** [comment] 2022-11-25 10:23
I can confirm that running it at 5x speed does indeed "fix" this issue, had it running the whole night and it's still running.

Would love to get an actual fix for running it at unbound speed though :)
