### ISSUE TITLE
[Wii] Jet Grind Radio - character sprites are garbage values

### ISSUE THREAD

**Issue by mczarnezki** [mgba-emu/mgba#459] opened 2016-11-06 01:00 UTC
Using the Wii nightly as of 11/5/2016.

The character sprites in the game are a scrambled mess. It's pretty obvious upon booting up the game. Sorry if this issue is already known.

**Comment by endrift** [comment] 2016-11-07 08:27
Can't reproduce in Dolphin. Will try on an actual Wii tomorrow.

**Comment by endrift** [comment] 2016-11-07 21:52
Fixed in 8fd14f40c096051e4bcf8ac0cbfed83be5aad0b0. Turns out the issue was with my custom BIOS implementation.

**Closed by endrift** 2016-11-07 21:52 UTC
Labels: GBA
