### ISSUE TITLE
Allow multiple key bindings?

### ISSUE THREAD

**Issue by jasonsparc** [mgba-emu/mgba#1475] opened 2019-06-28 18:26 UTC
So in VBA-M, I usually bind `A/B` with `f/g` on my keyboard and then `L/R` with `r/t`, but there are some games where I find it handy to bind `L/R` with `t/g` as well, giving my fingers more flexibility, especially for very fast games that require you to press `L/R` along with `A/B`.

In VBA-M, I could do this easily, as it supports multiple key bindings for the same emulated button. I wish I could achieve the same with mGBA, eventually.

**Comment by endrift** [comment] 2019-06-28 18:29
Dupe of #87, which is in progress.

**Closed by endrift** 2019-06-28 18:29 UTC
