### ISSUE TITLE
XQ GBA audio SNES music patches

### ISSUE THREAD

**Issue by bajolzas** [mgba-emu/mgba#1484] opened 2019-07-06 00:29 UTC
Im not sure what XQ GBA audio is supposed to do, but when using this option turned on, and using games that have SNES music restoration patches like breath of fire i/ii and I think also Final Fantasy VI, audio just does not play.

Possibly that option may not apply to SNES quality audio, but it would be cool if the emulator could  at least detect when it is running higher than GBA quality audio so it  could simply skip that option (if it could work with these patches as well then better)

**Comment by ipatix** [comment] 2020-01-24 13:29
These hacks use modified sound code. Assuming that the XQ would work, it would not sound right since custom mixer and reverb code is used.

**Comment by DarkD** [comment] 2022-06-22 06:00
XQ GBA also causes problems with Castlevania HoD: Revenge of the Findesiecle Deluxe+ hack. New tracks and sounds inserted in hack makes noises, while all original sounds and tracks play as intended. Something different about them, maybe sample rate causes mGBA mixer to go crazy, yet it works on internal.

**Comment by endrift** [comment] 2024-11-24 09:54
Closing as the old XQ audio driver has been removed.

**Closed by endrift** 2024-11-24 09:54 UTC
Labels: platform:GBA, hardware:audio
