### ISSUE TITLE
MGBA not seen as GBC in pokemon TCG2

### ISSUE THREAD

**Issue by psionx** [mgba-emu/mgba#2755] opened 2022-12-14 02:53 UTC
![ptcg](https://user-images.githubusercontent.com/15111844/207493266-868da444-5f00-4433-ab36-9e5a70bb478f.jpg)
is there a setting/cheat to work around this message?

**Comment by endrift** [comment] 2022-12-14 02:55
This game was never released in English. There might be a problem with your ROM hack.

**Comment by autofire372** [comment] 2022-12-14 03:57
I use that same translation, and I cannot reproduce.

**Comment by psionx** [comment] 2022-12-14 05:02
never mind. it seems a code in my cheat file was getting loaded a startup causing the error.

**Closed** 2022-12-14 05:27 UTC
Labels: software:unlicensed
