### ISSUE TITLE
Pokemon Emerald ROM hack: Jumped to invalid address

### ISSUE THREAD

**Issue by HardGaming01** [mgba-emu/mgba#1445] opened 2019-06-13 15:52 UTC
I was playing a Chinese Pokemon Emerald rom hack and it crashes as soon as it enters the game scene (After setting up gender, names, etc). The rom runs pretty well with vba but crashes at the same location every time I run it with mgba. Here's the rom and a snapshot (quicksave) right before the crash.

[pokemon dark shadow crash.zip](https://github.com/mgba-emu/mgba/files/3287025/pokemon.dark.shadow.crash.zip)

I'm assuming it's trying to load some asset since I see the characters turn black right before the crash.

I'm using this version of mgba

Branch: heads/0.7.2
Revision: c2b6692ce2a5abcfc47dc4ddad020059eb82767e

**Comment by endrift** [comment] 2019-06-14 18:36
I've seen this hack reported to crash before, but I've had trouble tracking down what's going on or if it happens on hardware too.

**Comment by hyno111** [comment] 2019-10-23 08:39
Can reproduce on 0.7.3 win32.
But it seems to be fixed on 0.8 b1 win32/win64.

**Comment by endrift** [comment] 2021-06-19 21:22
Seems to be fixed in latest.

**Closed by endrift** 2021-06-19 21:22 UTC
Labels: blocked:needs hw testing, software:romhack
