### ISSUE TITLE
(IU)(Suggestion) Bigger preference window and being able to alter its size. Resizing IU elements

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2025] opened 2021-01-25 12:55 UTC
The small dimensions of that windows affects usability, specially with the 125% scale value that Windows 10 sets by default

Examples: You can't see the full name of many shortcuts, paths or the whole list of the login section 

In a 1080p display, 125% scale , there's a lot of space wasted...
![imagen](https://user-images.githubusercontent.com/16591467/105707673-95f7e280-5f13-11eb-8195-478a88aa694d.png)

The menu problem is better at 100%, but there's still much unused space
![imagen](https://user-images.githubusercontent.com/16591467/105708320-917ff980-5f14-11eb-96ac-ef971b61ee21.png)

...Even in 768p there's room to increase
![imagen](https://user-images.githubusercontent.com/16591467/105708072-2f26f900-5f14-11eb-954a-3afb9e511458.png)

My suggestions:

- Wider sizeable window
- Bigger shortcut name column

**Comment by endrift** [comment] 2021-01-26 00:23
I've tried to get the bigger shortcut name column thing working already, but Qt has had issues letting me do it properly. I'll look into it more later, but this is just a duplicate of #1789 as is.

**Closed by endrift** 2021-01-26 00:23 UTC
