### ISSUE TITLE
Legend of Zelda, The - The Minish Cap (USA) crashes when rewinding

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1235] opened 2018-11-18 03:07 UTC
Legend of Zelda, The - The Minish Cap (USA) will crash when using rewind at random with this error.
![capture11-17-2018-9 02 42 pm](https://user-images.githubusercontent.com/21169038/48668167-a4811e80-eaac-11e8-9153-6042bc956363.jpg)

mGBA-build-2018-11-10-win32-5394-9262475cb47c1bbfd4422591394b789ce18f6b6b

**Comment by endrift** [comment] 2018-11-23 21:32
Probably the same root cause as #1216

**Comment by endrift** [comment] 2020-08-18 04:05
Please retest in latest dev.

**Comment by Cibomatto2002** [comment] 2020-08-20 02:16
So far no crash.

**Comment by endrift** [comment] 2020-08-20 02:39
Closing unless you find it still crashes eventually.

**Closed by endrift** 2020-08-20 02:39 UTC
Labels: category:needs retest, feature:savestates, platform:GBA
