### ISSUE TITLE
[Request] Turning out sound only in one window

### ISSUE THREAD

**Issue by RunisDauphin** [mgba-emu/mgba#1377] opened 2019-04-08 09:39 UTC
Hi, I am Runis Dauphin from Rebelles Unis

I think it would be nice to have the option for turning off the sound for only one or more of several windows (more or less like VBA Link and VBA-M do). It is quite annoying to hear (for example, when I exchange chips in Megaman Battle Network insert number here) the same music desynchronised twice.

In version 0.7.1, emulator only allows to turn on/off sound to all windows at the same time.

**Comment by endrift** [comment] 2020-08-11 03:11
Duplicate of #857.

**Closed by endrift** 2020-08-11 03:11 UTC
