### ISSUE TITLE
Golden Sun The Lost Age - Random hangs on scene transtitions and when interacting with NPCs/objects

### ISSUE THREAD

**Issue by jdgleaver** [mgba-emu/mgba#1160] opened 2018-09-04 11:20 UTC
Build: 0.7-5219-353176b1 (353176b1e11471b300290ebe950dba10b251fbb1)
OS: OpenSUSE 42.3 64bit (also tested on Android 5.0 via RetroArch)

ROM checksum:

  > md5sum "Golden Sun - The Lost Age (USA, Europe).gba" 
  8efe8b2aaed97149e897570cd123ff6e  Golden Sun - The Lost Age (USA, Europe).gba

'Golden Sun - The Lost Age' randomly hangs during scene transitions, and when interacting with NPCs or objects (typically anything that triggers the display of a text box). The issue affects both the standalone version of the emulator and the RetroArch core, although there is a slight difference between the two:

- With standalone, the hang is either 'silent' (i.e. no log output) or produces a stream of the following log message:

      GBA: Hit Wii U VC opcode: 0000e83d

- With the RetroArch core, the hang produces a stream of the following log message:

      [libretro WARN] GBA: Illegal opcode: 0000e92d

(So it seems to be failing on different lines of the GBAIllegal() function in src/gba/gba.c)

The issue can be reproduced using the following save file: [save.zip](https://github.com/mgba-emu/mgba/files/2348334/save.zip)

- Continue the game from slot 1 - labelled 'Alhafra'

- Run back and forth through the door just north of where you start

- The game will eventually hang (note that this can be tedious to test - sometimes it happens immediately, sometimes you have to keep running back and forth for several minutes)

- The hang may also be trigged by talking to the various NPCs inside the building where you start (again, this can happen immediately, or after wading through dozens of screens of dialogue)

I also attach two save states from the standalone version of the emulator:

[state1_hang_with_log.zip](https://github.com/mgba-emu/mgba/files/2348349/state1_hang_with_log.zip): This restores the game to a 'hang' state where the 'GBA: Hit Wii U VC opcode: 0000e83d' log message is being printed repeatedly to the console

[state2_hang_no_log.zip](https://github.com/mgba-emu/mgba/files/2348361/state2_hang_no_log.zip): This restores the game to a silent 'hang' state where nothing is being logged.

**Comment by JMC47** [comment] 2018-09-05 21:04
Confirmed with your savefile.

![image](https://user-images.githubusercontent.com/6598209/45120953-a5511800-b12d-11e8-9732-e209089b4af1.png)

Behaves similarly to the loading crashes on Mario Golf: Advance Tour.

**Comment by endrift** [comment] 2018-09-16 18:09
@JMC47 can you try bisecting this issue to see if it's a regression and when it regressed if so?

**Comment by endrift** [comment] 2018-09-18 04:51
Confirmed in ce658ff3a540cfcefc3923b47aed41e1becb46bf, can't reproduce in 0.6.3 or 7e8388089a99f4fa57255192265750e8d70d1647 (at least, haven't been able to yet). Will try bisecting.

**Comment by endrift** [comment] 2018-09-18 07:44
Can you confirm if this is fixed in 108b0fc867292c554a6ef9b643fc39209561e35a?

**Comment by endrift** [comment] 2018-09-18 07:52
Possibly related to #969, possibly fixed in 108b0fc867292c554a6ef9b643fc39209561e35a.

**Comment by jdgleaver** [comment] 2018-09-18 10:12
Okay - just spent a solid half hour running back and forth through doors using 108b0fc867292c554a6ef9b643fc39209561e35a, and can no longer reproduce the issue. Thank you so much for fixing this. It is greatly appreciated. 

Would it be possible to get this commit pushed through to the [libretro/mgba](https://github.com/libretro/mgba) core? I can't play GBA games without my [simpletex_lcd+gba-color](https://github.com/libretro/glsl-shaders/blob/master/handheld/shaders/simpletex_lcd/simpletex_lcd%2Bgba-color.glsl) shader! :slightly_smiling_face:

**Comment by endrift** [comment] 2018-09-18 18:16
I'll try to do that later today.

**Closed by endrift** 2018-09-18 18:16 UTC
Labels: severity:priority game

**Comment by jdgleaver** [comment] 2018-09-19 08:46
Thank you :heart:
