### ISSUE TITLE
shader is never remembered by the emulator

### ISSUE THREAD

**Issue by dml360** [mgba-emu/mgba#1553] opened 2019-10-23 03:06 UTC
Whenever I choose a shader, the emulator does not leave it enabled even if I restart the PC and whenever the emulator is closed and reopened I have to go there and reselect the shader, it would be possible a once chosen form not need every time enter emulator select it? is that all the other emulators I use just select once and you're done.

**Comment by jmc92** [comment] 2019-10-23 03:36
I can confirm this is a problem for me as well.

**Comment by endrift** [comment] 2019-10-23 03:38
I've hit this before, but only sometimes. I'll investigate soon.

**Comment by themalu866** [comment] 2019-10-28 00:10
I go to Settings, I make some changes, choose a shader, Restart Needed message appears, close mgba and when I restart the shader is not remembered and I have to choose again.
Sometimes if I change the shader's options like Gamma, Scale, Bias, Desaturation the changes don't save when I close the emulator.

Not only that but some shaders only seems to work if the frame size is at 3x like agb001 and ags001.
And another thing about agb001 and ags001: it's kinda recent but when hold Fast Forward with them loaded it skips around 6 to 10 seconds, its really weird now.
And shaders like the Wiiu really slowdown games, just ruins the framerate.
![agb001](https://user-images.githubusercontent.com/42208976/67644201-07ef0f80-f8fe-11e9-931f-10b8439ef7f0.png)

**Comment by endrift** [comment] 2019-10-28 00:19
I tried to reproduce this and have been unable to. I'll try again later with a fresh config.

As for the agb/ags-001 shaders, they only work at 3x because they triple the pixel density for subpixel effects. If you turn on bilinear filtering it should scale down somewhat properly.

As for the Wii U shader, it might just be slow on your ancient GPU. I didn't write that one so I'm not sure.

**Comment by xupwup** [comment] 2019-11-01 18:21
About the Wii U shader, you can probably get better perfomance with this version of the shader I just made. The results should be very close, but it's a lot simpler. This version never differs by more than 1/255 compared to the old version I believe.

```
varying vec2 texCoord;
uniform sampler2D tex;
uniform vec2 texSize;

float scale(float c) {
	return c * 191.0 / 255.0;
}

void main() {
	vec4 color = texture2D(tex, texCoord);
	color.r = scale(color.r);
	color.g = scale(color.g);
	color.b = scale(color.b);
	gl_FragColor = color;
}
```

**Comment by endrift** [comment] 2019-12-14 21:18
This may be fixed now, please confirm

**Comment by dml360** [comment] 2019-12-14 21:48
Gorgeous gorgeous

I tested it many times, restarted my pc 3 times, shut down and turned on 2 times and at all times the shader remained enabled ..
It seems that the "problem" has been solved .. For my part can already close here ..
Thanks dude you deserve a kiss obs: i tested in build 0.8 5984 2583c5ca  my pc settings: i5 8400 - gtx 1060 6gb - 16gb ram 24000mhz - W10 Pro.

**Closed** 2019-12-14 21:54 UTC
Labels: category:needs retest, port:Qt
