### ISSUE TITLE
Fullscreen problem

### ISSUE THREAD

**Issue by torben656** [mgba-emu/mgba#993] opened 2018-02-16 11:28 UTC
after exiting in fullscreen the application is suddenly in windowed mode. Using x86.

**Comment by rootfather** [comment] 2018-02-17 09:26
Since your bug bug report is lacking quite a bit of necessary information (OS, version, exact steps to reproduce...), I tried to replicate what you reported on my Windows 10 x64_86 machine using the code from current master.

I found two "issues" with the fullscreen mode that might match what you are experience.

1. Maximize the mGBA window and then exit mGBA. On the next start, the mGBA screen will have about the same size as it would have in maximized mode, but it's in the "normal" windowed mode and you can maximize it again, so mGBA can't remember that it was previously maximized.

2. Enter the fullscreen mode by using either the menu option or the Alt+Return hotkey. Then exit mGBA by either choosing File -> Exit or pressing Alt+F4. When you start mGBA the next time, you end up with the following screen:
![mgba fullscreen bug](https://user-images.githubusercontent.com/11882577/36339764-f9d9e7de-13cc-11e8-8fdf-4efa2560b1d1.PNG)

@torben656, does one of those cases matches your experience?

**Comment by endrift** [comment] 2018-02-17 17:26
I think this is a dupe but I can't find the original bug easily.

**Comment by endrift** [comment] 2018-02-17 17:40
Hmm, this doesn't reproduce the same way on Mac. Will need to look into it on Windows.

**Comment by torben656** [comment] 2018-02-18 09:15
Hello @endrift , if I am going to post a new issue, do I need to post a new one or I can just add it here? Another issue I have is that when I click the mGBA.exe , I usually tend to wait for 5 seconds. Can you somehow make a way to speed it up?

**Comment by rootfather** [comment] 2018-02-18 09:17
If you are on Windows 8.x or higher, this is most likely Windows Defender kicking in to check the executable. If your issues persist or get worse, you should open a new issue for this.

**Comment by rootfather** [comment] 2018-02-18 09:18
@endrift, dupe from https://github.com/mgba-emu/mgba/issues/487.

**Comment by endrift** [comment] 2018-02-21 18:24
Ah yeah that's the one I was thinking of.

I have a fix for this but I can't commit it until tonight. It's pretty simple, I just needed to track it down.

**Closed** 2018-02-24 20:08 UTC
Labels: os:Windows, port:Qt

**Comment by lemmikens** [comment] 2023-06-16 19:45
This issue is happening again.
