### ISSUE TITLE
SGB-mode Game Boy saves fail to load from Game Boy mode

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#910] opened 2017-10-16 22:30 UTC
When Playing Gameboy. If you do a Quick Load you may get a black screen or this.

<a href='https://postimg.org/image/9ggqncb67f/' target='_blank'><img src='https://s1.postimg.org/9ggqncb67f/Capture10-1-2017-10.58.50_AM10-1-2017-11.00.30_AM10-1-2017-11.01.jpg' border='0' alt='Capture10-1-2017-10.58.50_AM10-1-2017-11.00.30_AM10-1-2017-11.01'/></a>

Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Pentium G3240 @ 3.10GHz	
	Haswell 22nm Technology
RAM
	8.00GB Dual-Channel DDR3 @ 698MHz (10-10-10-25)
Motherboard
	Gigabyte Technology Co. Ltd. H81-D3 (SOCKET 0)
Graphics
	ELEFW328 (1360x768@60Hz)
	Intel HD Graphics (Gigabyte)
	1023MB NVIDIA GeForce GT 720 (EVGA)	
	ForceWare version: 365.10
	SLI Disabled
Storage
	931GB TOSHIBA DT01ACA100 (SATA)	
Optical Drives
	HL-DT-ST DVDRAM GH24NSC0
Audio
	Realtek High Definition Audio

**Comment by zeromus** [comment] 2017-10-16 22:33
You should probably write which game and which scene

**Comment by endrift** [comment] 2017-10-16 22:56
Things that are useful info:

- Emulator version
- OS
- Game(s) affected

Things that are not:

- Literally any other info about your computer

**Comment by Cibomatto2002** [comment] 2017-10-16 23:33
Sorry I forgot to put the Emulator version I did post Computer info I will post again. Windows 10

Metroid II - Return of Samus (World), Bust-A-Move 2 - Arcade Edition (USA, Europe), Bionic Commando (USA). There are more games but you get the idea.


mGBA-build-2017-10-15-win32-4887-f69b652e272492884472d8993015d189451138b4


Here is A video of the problem

https://www.youtube.com/watch?v=PqhZAsoY4KE&feature=youtu.be





Operating System
Windows 10 Pro 64-bit
CPU
Intel Pentium G3240 @ 3.10GHz
Haswell 22nm Technology
RAM
8.00GB Dual-Channel DDR3 @ 698MHz (10-10-10-25)
Motherboard
Gigabyte Technology Co. Ltd. H81-D3 (SOCKET 0)
Graphics
ELEFW328 (1360x768@60Hz)
Intel HD Graphics (Gigabyte)
1023MB NVIDIA GeForce GT 720 (EVGA)
ForceWare version: 365.10
SLI Disabled
Storage
931GB TOSHIBA DT01ACA100 (SATA)
Optical Drives
HL-DT-ST DVDRAM GH24NSC0
Audio
Realtek High Definition Audio

**Comment by zeromus** [comment] 2017-10-16 23:40
You should have explorer show file extensions, or else programmers will be very distracted when watching this video

**Comment by endrift** [comment] 2017-10-17 03:09
Please upload a savestate that's broken. I can't reproduce locally.

**Comment by Cibomatto2002** [comment] 2017-10-17 23:17
I uploaded Metroid II - Return of Samus (World) and config file. maybe the config file will help you. You can still here the music and when you press the buttons you can here the player jump the screen is only showing black on the screen it's like someone turn down the bright all the way.


[Metroid II - Return of Samus (World) and config file.zip](https://github.com/mgba-emu/mgba/files/1392912/Metroid.II.-.Return.of.Samus.World.and.config.file.zip)

**Comment by Cibomatto2002** [comment] 2017-10-17 23:28
Just download the mGBA-build-2017-10-17-win32-4890-acbd8a3688703772861241a9b87f08cf91a0f66d build same thing happens.

**Comment by endrift** [comment] 2017-10-17 23:56
I can reproduce with that savestate.

**Comment by endrift** [comment] 2017-10-18 04:41
SGB issues partially fixed by 65665324ef9124280a8a310ab9cea048d519a5a9 and mode 3 part fixed by 7ebd2d6e7546b91217d6dba88d0d2d01d72f4905. Old savestates may break, however.

**Comment by endrift** [comment] 2018-08-28 22:45
Can you please retest? This is an 0.7 blocker and I just pushed some fixes, so you'll need to download the latest build.

**Comment by Cibomatto2002** [comment] 2018-09-02 15:50
As of Build mGBA-build-2018-09-02-win32-5211-7d79db7d7d31f5a956123e751f455eee9d4b043e it's work correct now. Thanks !!

**Closed** 2018-09-02 16:47 UTC
Labels: platform:GB/GBC, severity:bug
