### ISSUE TITLE
[BUG] Opening a ROM during gameplay and cancelling causes emulation to break (0.9.1) (Update: Only occurs when VSync is on)

### ISSUE THREAD

**Issue by Agera153** [mgba-emu/mgba#2197] opened 2021-05-24 14:45 UTC
[mGBA_bugreport.zip](https://github.com/mgba-emu/mgba/files/6533134/mGBA_bugreport.zip)

https://user-images.githubusercontent.com/84726693/119364282-bc891880-bc7c-11eb-8448-5c4bb8a2dd4e.mp4

To recreate the steps:

1. Open any ROM and begin emulating.
2. Use ctrl+O keyboard shortcut to open a different ROM. Cancel the load operation.
3. Framerate dips to 20FPS, or about 1/3rd of the emulation speed, completely breaking the emulation for that session.

Refer to the attached video demonstrating the bug.

Some details:

mGBA v0.9.1
Windows 10 Home Edition x64
Intel i7-6700 w/ GeForce GTX 970
Opening another ROM and actually starting a fresh emulation resolves the problem, but you can just cause the same bug to happen again. 
The games I tested this on in the video were Jimmy Neutron - Jet Fusion and Mario Kart Super Circuit, but the bug happens to every game I've tried.

**Comment by Agera153** [comment] 2021-05-24 17:13
Just had a large breakthrough. It only occurs when "Sync Video" is enabled under Emulation menu. Toggling VSync fixes the problem. My screen's refresh rate is 144Hz so that may be causing it.

**Comment by endrift** [comment] 2021-05-25 18:17
Can you see if this happens in dev builds? There were some video sync bugs that have been fixed since.

**Comment by endrift** [comment] 2021-06-04 06:03
Closing due to lack of reply, assuming duplicate of #2138.

**Closed by endrift** 2021-06-04 06:03 UTC
Labels: blocked:needs info
