### ISSUE TITLE
[Threaded video] Games freeze system on 3DS and Vita

### ISSUE THREAD

**Issue by Committee** [mgba-emu/mgba#325] opened 2016-08-06 22:30 UTC
Using mGBA-nightly-2016-08-06-3ds-8a68de198cd39e351ea84e040ecf5882b6234c03 CIA Version on a N3DS CFW Luma3ds Emunand Ver 11.0.

When loading game it just crashes and forces n3ds to restart.

**Comment by endrift** [comment] 2016-08-06 22:31
What game? I've had this problem with a few games, but most work fine. I'm not sure how to debug the crash though, since it's actually a freeze and only happens on 3DS and Vita, neither of which are really debuggable.

**Comment by Committee** [comment] 2016-08-06 22:34
I have tried HM Friends of Mineral Town, FF6, FF Tactics.

**Comment by endrift** [comment] 2016-08-06 22:36
Confirmed broken with FFTA.

**Comment by Committee** [comment] 2016-08-06 22:37
Understood, FF6 and HMFOMT works with the previous nightly build mGBA-nightly-2016-08-03-3ds-6e47d402c8942ca4501d7a09d7e241b5f11a7340

**Comment by endrift** [comment] 2016-08-06 22:38
Yeah, it's almost certainly an issue with the video threading, as it happens on Vita too, but I can't quite figure out what the problem is.

**Comment by Committee** [comment] 2016-08-06 22:39
Pardon the noob question but what has changed in the video threading from that build to the latest nightly?

**Comment by endrift** [comment] 2016-08-06 22:39
Everything. I moved video into a thread in the first place.

**Comment by Committee** [comment] 2016-08-06 22:42
Alright, well, I guess nothing to do but wait for now.

Thank you btw, love your work, been using it since you ported it for the 3DS.

**Comment by endrift** [comment] 2016-08-06 22:50
Just use the 3DSX version for now until I fix this, then.

**Comment by OTFree** [comment] 2016-08-10 01:22
Yep, was just about to bug report but it saw that this thread existed xD Happened with Leaf Green on 3DS (cia), haven't tested the latest nightly on Vita yet though.

**Comment by Committee** [comment] 2016-08-10 03:13
I tried the CIA Version of the version endrift posted on twitter a few hours ago, solved the issue with HMFOMT, FFT, and FF6

**Comment by endrift** [comment] 2016-08-10 05:31
Fixed in 30f124fae4ad0541ef77e85e03bf65cadd59fdc5.

**Closed by endrift** 2016-08-10 05:31 UTC
Labels: bug, port:3ds, port:vita
