### ISSUE TITLE
[Switch][UI suggestion] In the savestates menu show the date next to the savestate slot

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2184] opened 2021-05-15 15:19 UTC
It's hard to know which slots are used or not at a glance, the only way is to move the cursor over to see if the image shows a screenshot.

My suggestion is to show the savestate date next to the slot to easily know how many there are and which is the last one.

**Comment by endrift** [comment] 2021-05-15 22:10
Duplicate of #2012

**Closed by endrift** 2021-05-15 22:10 UTC
