### ISSUE TITLE
Disable touchpad?

### ISSUE THREAD

**Issue by techmouse** [mgba-emu/mgba#2630] opened 2022-08-17 16:38 UTC
How to?

# My problem:
I can't play anything because the touchpad is set as the controller and can't be disabled.

This is a problem because the cursor's **POSITION** is what decides movement, not any actual swipes on the touchpad. So if the cursor is on the left side of the screen, then the character won't stop moving to the left, regardless of how untouched the touchpad is.

It's also obnoxious because I have no idea where I'm supposed to put the cursor to zero out the "axis".

Even **IF** this is supposed to be for a touchpad controller, not unlike the Steam Controller/Deck, it still doesn't work right because it continuously registers input that has already happened.

So how do I disable this goofy clown setting?

# Nopes:
I saw in a thread that somebody had suggested to click "clear button" for each of the entries in the controller setting menu. But this won't work cause I can't tab my way to that button while an entry is selected, and any amount of movement on the touchpad will be applied to that entry. So how is that even supposed to happen?

I saw other people suggest using some specific build of mgba. Wish I could. I'm using mgba for an installation of Puppy Linux on a really old laptop, which means many of my options are hard locked, including the version, which is 0.7.0. So I'm stuck making lemonade with this one.

I tried using a new version of Puppy Linux, which would make use of a newer version of mgba, but **EVERY. SINGLE. EMULATOR.** caused a segmentation fault. Not just mgba. *ALL* of them. So that's not going to fly either. Older Puppy works with my hardware. Newer doesn't. I don't even know.

I edited config.ini and I removed write permissions to it, but it looks like mgba can ignore write permissions and overwrite it anyways. It also looks like mgba doesn't actually read from config.ini, and only outputs to it? I say this because no matter what I tried to do to keep overwriting data to that file while mgba was running, mgba seemed to only write to it too.

I tried creating a symlink from /dev/null to the config.ini, just to hopefully prevent it from reading any touchpad based configurations, but mgba clearly generates this information during runtime and never drops it.

I tried making a dummy /dev/input/js0 just so I could have a single other entry in the controller list to switch to, but this also didn't work. So I have no idea where mgba even finds its controllers.

I tried completely disabling the touchpad **SYSTEM WIDE** so that no input at all could possibly be detected, but I guess even when the touchpad is completely unusable to the rest of the system, mgba can still read it. I was even able to rebind the touchpad buttons in the controller menu **WHILE the touchpad was completely disabled for the rest of the system.**

I eventually had the idea to plug a USB mouse in and use that to click the "clear button" button for every entry. And this actually worked. All entries said "---". Then I immediately loaded a game and all of the obnoxious settings went right back to being obnoxious. So this confirms it. There is no way around this goofy clown setting.

A simple on/off tickbox would have fixed all of this.

A simple "nope" entry in the controller list would have fixed all of this.

Hell, at this point I'd be happy to just have a single relevant result when I google "mgba disable touchpad".

I don't know how nobody has reported this glaringly obvious problem. I must be the edgiest of edge cases.

**Comment by endrift** [comment] 2022-08-18 04:59
Well considering that this doesn't seem to happen to anyone else, it's clearly not a common issue. I don't know if it's SDL, the trackpad drivers, or what, but it seems to be showing up wrong somehow. I couldn't tell you how, because you just ranted instead of providing information about your computer.

Even if this were a support forum and not a bug tracker, I can't really provide support for a 3 year old version of mGBA either, since a ton of stuff has been fixed in the meantime. It's quite possible that it works on a modern version of everything. But that's not what you have.

**Closed by endrift** 2022-08-18 04:59 UTC
