### ISSUE TITLE
[Vita] Pokemon LeafGreen runs slowly after accessing mgba configs

### ISSUE THREAD

**Issue by fqborges** [mgba-emu/mgba#341] opened 2016-08-12 13:27 UTC
Symptoms: After opening and closing mgba configs/options ( /_\ button) game runs slowly.

Version: yesterday nightly build (2016-08-11).

**Comment by endrift** [comment] 2016-08-12 19:00
Dupe of #327.

**Closed by endrift** 2016-08-12 19:00 UTC
Labels: duplicate, port:vita
