### ISSUE TITLE
Square wave emulation issue

### ISSUE THREAD

**Issue by Yave-Yu** [mgba-emu/mgba#1657] opened 2020-02-01 09:20 UTC
Hey, your mGBA is awesome, running fast, emulation speed is accurate, Wave(Ch3) and Noise(Ch4) are accurate to an actual hardware(or VC?), but square waves(Ch1&2) are not very accurate, it emulates lower quality than actual hardware(or VC).
About SFX, my memoriable point are on any Pokemon game's selection sound, it sounds so broken; any Mega Man Battle Network game's jack in "Di" sound, it sounds on lower octave.
About Music, the first game of Mega Man Battle Network series could be an example. Virus Busting and Fire Field are more obvious, it's square wave should be more smooth like actual hardware(or VC), not intermittent.
Hope you can make square wave emulation more better~

**Comment by IamRifki** [comment] 2020-02-01 09:27
Could you provide Waveforms of the Emulated one and Real Hardware?

**Comment by endrift** [comment] 2020-02-01 09:32
Do you have any savegame in MMBN I can use to reproduce and compare this? This isn't much to go on, it's rather anecdotal. As far as I can tell the jack-in SFX doesn't even use the square wave.

**Comment by Yave-Yu** [comment] 2020-02-01 16:33
Here's MMBN1 sav I've played to Fire Field:
http://www.mediafire.com/file/ma4khwgdunhjutl/Mega_Man_Battle_Network_%2528USA%2529.sav/file
And... I'm sorry, I have no real GBA, I just watch someone's playthrough video, he plays on VC, here's video link:
http://www.nicovideo.jp/watch/sm15255402
Also, MMBN2 Title music is also a good example on square wave emulation test.
About Pokemon's selection sound, I also just watch a VC video on SpeedDemosArchive.
I'm sorry I got wrong with that jack in sound.

**Comment by Testsr** [comment] 2020-02-10 03:53
One thing. VC means to me Virtual Console, which is an Nintendo Emulator for older systems, and may not be able to be trusted.

**Comment by TriforceOfPwnage** [comment] 2020-02-10 23:21
> One thing. VC means to me Virtual Console, which is an Nintendo Emulator for older systems, and may not be able to be trusted.

Vc is not technically an emulator. It uses hardware that exists in an actual GBA to run games. It is close to 100 percent accurate. To the point where most issues that mgba has with my roms GBA vc has the same issue.

**Comment by endrift** [comment] 2020-02-10 23:22
In this case it's Wii U VC, not 3DS VC, which is an emulator.

**Comment by TriforceOfPwnage** [comment] 2020-02-10 23:24
Crap i forgot wiiu gba vc was a thing. Lol sorry.

**Comment by endrift** [comment] 2022-06-02 02:42
Please retest in 76a8f4da2bb4fc4ef10a64eae5d3da0d7846c73f or newer.

**Comment by endrift** [comment] 2023-01-29 04:39
Closing due to lack of reply.

**Closed by endrift** 2023-01-29 04:39 UTC
Labels: blocked:needs info, blocked:needs retest, blocked:needs hw testing
