### ISSUE TITLE
"Apply" button in "Tools > Settings" does nothing

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#479] opened 2016-12-18 20:43 UTC
Changing a setting and then clicking on the Apply button does not save the setting change. The only way to save a setting change is to click on the OK button.

Also tested the latest nightly (**0.6-4157** at the time of writing) and it has the same issue.

**OS:** Windows 10 Pro x64
**Build at time of writing:** 0.5.1 stable

**Comment by endrift** [comment] 2016-12-20 07:19
Works fine on macOS. Wonder if it's OS-specific.

**Comment by karasuhebi** [comment] 2016-12-20 14:21
Maybe it's only certain screens where Apply doesn't work? I believe I tested it on the Shortcuts page.

**Comment by endrift** [comment] 2016-12-21 02:10
Couldn't reproduce this on Win10 either, and the Shortcuts thing is covered by #480.

**Comment by karasuhebi** [comment] 2016-12-21 04:11
I meant to say Controllers page, not Shortcuts. Sorry. Can you reproduce it there?

**Comment by endrift** [comment] 2016-12-21 05:21
Fixed in c83833bfd47f7dc31455d53f92e1dc83fa506746.

**Closed by endrift** 2016-12-21 05:21 UTC
Labels: port:Qt, questionable

**Comment by karasuhebi** [comment] 2016-12-21 05:25
Thanks! :)
