### ISSUE TITLE
Hopefully the Switch will add an official shader

### ISSUE THREAD

**Issue by Dsseed** [mgba-emu/mgba#2829] opened 2023-02-15 01:20 UTC
I experienced the Gameboy Avdance Nintendo Switch Online, and the shader in it is really great. 
I hope mgba can also have such shaders and the official game frame size. 
mgba is very good, but the biggest regret is that there is no shader

**Comment by endrift** [comment] 2023-02-15 01:21
Duplicate of #2037.

**Closed by endrift** 2023-02-15 01:21 UTC
