### ISSUE TITLE
Glitch with DK: King of Swing

### ISSUE THREAD

**Issue by PiePusher11** [mgba-emu/mgba#953] opened 2018-01-02 23:39 UTC
I found a glitch in DK: King of Swing that appears to only happen on mGBA (I'm using mGBA - 0.6.1). I have a video of it here: 

https://www.twitch.tv/videos/214814191

If you're unfamiliar with the game, basically the Jungle Jams are a collection of minigames, and what happens is when you click "Select Event" it's supposed to bring you back to the screen where you pick which one you want to play. Instead, what seems to happen is it brings me to the final world of the main game. This seems to only happen on mGBA; it functions as expected on VBA, and on an actual cart.

**Comment by endrift** [comment] 2018-01-02 23:54
Dupe of #902.

**Closed by endrift** 2018-01-02 23:54 UTC
