### ISSUE TITLE
Numerous Games - Mario Bros single pack play will not start

### ISSUE THREAD

**Issue by alex34567** [mgba-emu/mgba#765] opened 2017-06-25 21:36 UTC
Build - 0.6-4606-b61b8a0d
OS - Arch Linux 64-bit
Processor - Intel Core i5-4690K

In all the Super Mario Advance games plus Mario & Luigi: Super Star Saga, there is an option to play a multiplayer version of Mario Bros with one game pack.
In mgba after starting a multiplayer session with one of those games and the gba bios, results in both game boys to error after the stage 2 loader is transferred.

Steps to reproduce:
1. Open mgba and create a multiplayer window.
2. Load Super Mario Advance 4 in one gba then boot the bios in another.
3. In the gba with SMA4 select multiplayer on the title screen.
4. After they connect press start until the game tries to start.
5. The games should error out shortly.

Notes:
Multi pack play seams to work fine.
The gba with the bios runs at 80 fps while the gba with SMA4 runs at 60 fps during the transfer.
I have also confirmed the bug on Mario & Luigi.

**Comment by endrift** [comment] 2017-06-25 22:43
Dupe of #425

**Closed by endrift** 2017-06-25 22:43 UTC
Labels: enhancement, GBA
