### ISSUE TITLE
[Switch][Last nightly][Pokemon Crystal Clear] Audio cracking after abusing the turbo in long gameplays

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2076] opened 2021-03-23 21:35 UTC
After playing for some time, using the turbo key frequently, the audio starts shuttering a lot with white noise. It improves a little after a while, and gets worse if you keep using the turbo.

The game is a hackrom of Pokemon Crystal (UEv1.1) called "Crystal Clear". I've being playing this hack a lot in mgba for windows without any issue, but in Switch this issue starts after some time playing (20 minutes?)

Closing the app fixes it.
Sleeping and waking up the console stops the noise too without having to close it, but in that case the noise resumes immediately after using the turbo again.

Recording of the audio
[audio_2021-03-23_22-31-56.zip](https://github.com/mgba-emu/mgba/files/6192847/audio_2021-03-23_22-31-56.zip)

Specs: Atmosphère 0.18.1
Build: mGBA-build-2021-03-23-switch-6839-9eee7a7c7ac4ee3fa595ca2672e91ce916c92803
mgba official ~~NSP~~ **NRO** (sorry, slip of the tongue)

**Comment by endrift** [comment] 2021-03-24 03:07
There is no official mGBA NSP, only NRO. I shudder to ask where you got it.

**Comment by endrift** [comment] 2021-03-24 03:54
This _might_ be fixed in e073986ea83e4b272a1a92bb8d4d9e2e938fec1b, but I'm not sure. Please retest.

**Comment by RafaelTrepaUnCarballo** [comment] 2021-03-24 08:58
> There is no official mGBA NSP, only NRO. I shudder to ask where you got it.

It wasn't a NSP, sorry, I meant the official **NRO**.
I downloaded today's latest build, retesting...

**Comment by Testsr** [comment] 2021-03-24 12:35
@RafaelTrepaUnCarballo  Yes. This is the latest version of the emulator.

**Comment by RafaelTrepaUnCarballo** [comment] 2021-03-24 16:23
The issue is still there.

**Comment by endrift** [comment] 2021-03-24 22:52
Hmm, what other plugins/ovl/etc do you have enabled? I wonder if you have something that's causing the audio to hiccup somewhere that's having a ripple effect.

**Comment by endrift** [comment] 2021-03-25 06:55
I pushed some more fixes that don't seem related but I've stopped being able to reproduce in the meantime, curiously.

**Comment by RafaelTrepaUnCarballo** [comment] 2021-03-25 16:59
@endrift The bug is unfixed, but it looks like it's harder to reproduce.

About what I'm using, I think the only plugin I installed was the latest sys-clk.

The tesla menu is v1.0.6. It has the following ovl:

- status monitor overlay 0.6.3. I didn't install Nx-FPS (its fps counter) because that can cause problems.
- sys-clk-overlay 1.0.0
- sysmodules 1.2.1 (it says there's no sysmodules installed)
- shutdown-ovl 1.0.0

**Comment by RafaelTrepaUnCarballo** [comment] 2021-03-27 12:35
I found two much easier way of triggering the audio issue:

1. Open a game
2. Close it
3. Open the same game again.

With Autoload and auto save savestate ON, the game starts cracking immediately, even without pressing turbo. Very noticeable during the intro of Mario Golf Advance Tour, with Waluigi's voice. My inexpert opinion there's something wrong with the audio initiation when loading a savestate in startup. Manual savestates work fine.

Without autoload, the audio sounds fine until the first time you press turbo.

**Comment by endrift** [comment] 2021-03-27 21:17
It's possible there's something related. I'll try that now.

**Comment by endrift** [comment] 2021-03-27 21:20
Weirdly that didn't work for me. Are you using GPU rendering? And what scale?

**Comment by RafaelTrepaUnCarballo** [comment] 2021-03-27 21:27
I'm not using GPU rendering, I disabled it.

**Comment by endrift** [comment] 2021-03-27 21:48
I wonder why I can't reproduce then. Is this in docked mode?

**Comment by RafaelTrepaUnCarballo** [comment] 2021-03-27 22:23
No, Portable mode.

Here are my preferences:

![2021032722431700-C7892DA72808DC3F7CBED36F86AE5894](https://user-images.githubusercontent.com/16591467/112736192-11483580-8f51-11eb-869b-8253ad43ac39.jpg)

I'll attach a video of the cracking (it looks it does happen even without autoloading savestates)

[2021032722383000-C7892DA72808DC3F7CBED36F86AE5894.zip](https://github.com/mgba-emu/mgba/files/6216502/2021032722383000-C7892DA72808DC3F7CBED36F86AE5894.zip)

**Comment by endrift** [comment] 2021-03-27 22:31
I wonder if there's something different between the builds we're using. I should try using the Docker builds instead of a generic build from my source tree.

**Comment by endrift** [comment] 2021-03-28 04:36
I believe this is fixed in 4021452f5aaf41ced5a8316b41dd35d8e627a780, please retest.

**Comment by RafaelTrepaUnCarballo** [comment] 2021-03-28 10:24
I can't trigger the issue the easy way (by closing it and open it), but I need to play longer to be sure it isn't triggered after long gameplays.

**Comment by RafaelTrepaUnCarballo** [comment] 2021-03-28 19:13
I've been playing for hours without an issue. I think the issue is solved.

**Closed** 2021-03-28 19:19 UTC
Labels: system:Switch
