### ISSUE TITLE
second window for MP not working

### ISSUE THREAD

**Issue by Numero256** [mgba-emu/mgba#934] opened 2017-11-28 18:16 UTC
mGBA 0.7-4931-72122430
and mGBA 0.6.1
Windows 10 64-bit
i7 7700K and GTX 1070

I tried to trade Pokemon in Fire Red, and I used the option to open a new multiplayer window. In the first window the emulation works without problems, but when I open a copy of the rom in a second window it will not be displayed and it has no sounds. Any rom I tried to open in a second window will not work. I tried both versions mentioned above, but they have the same problem.
And I do have two controllers plugged in.
![grafik](https://user-images.githubusercontent.com/34071713/33336435-2e691c0a-d470-11e7-898f-761d767f754b.png)

**Comment by endrift** [comment] 2017-11-28 18:17
Dupe of #854.

**Closed by endrift** 2017-11-28 18:17 UTC
