### ISSUE TITLE
Zelda: A Link to the Past very long loading times, saving issues

### ISSUE THREAD

**Issue by ml-** [mgba-emu/mgba#885] opened 2017-09-24 14:17 UTC
**Game:** Legend of Zelda, The - A Link to the Past & Four Swords (Europe) (En,Fr,De,Es,It) [[No-Intro]](http://datomatic.no-intro.org/?page=show_record&s=23&n=0867)

**Platform:** Vita. (Doesn't happen on Desktop/Linux)
**Version:** 0.7-4831-5dfa036fa

**What happens:**
When starting the game, you see a white screen for a very long time. (>1min)
Seems like the game is creating the initial .sav file.
**After trying this again, it did take longer but not as long as the first time.**

1. Press start on the title screen and select a language
1. In the **CHOOSE A FILE** dialog, select 1, 2 or 3 (doesn't matter).
2. Enter Name and select **End**
3. Now you see the **Now saving...** window followed by **The file couldn't be created.**
4. You are sent back to the **CHOOSE A FILE** dialog. No save was created.

The loading time and the time it takes (trying) to save varies every time, from a few seconds to longer than a minute.

But the **The file couldn't be created.** is 100% reproducible.

## Edit:
Doesn't happen with 0.6.0!

**Comment by endrift** [comment] 2017-09-24 18:45
Seems to work fine in 0.7-4754-6ab7e17. Must be a regression since then.

**Comment by endrift** [comment] 2017-09-24 18:50
Can you try https://s3.amazonaws.com/mgba/build/mGBA-build-2017-09-18-vita-4822-d582cf7d36a2f1f99b45ba6bc919ea431e08342b.7z and https://s3.amazonaws.com/mgba/build/mGBA-build-2017-09-16-vita-4821-7fc91b1ae6c3e2f80358d39c05d5fc0b3797140d.7z (deleting the .sav in the middle) to see if it regressed in d582cf7d36a2f1f99b45ba6bc919ea431e08342b?

**Comment by endrift** [comment] 2017-09-24 18:57
Never mind, the answer was almost certainly "yes". It's fixed now.

**Closed** 2017-09-24 18:57 UTC
