### ISSUE TITLE
Opening roms associated to mGBA portable opens the emulator with default preferences instead of the current ones

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2021] opened 2021-01-23 16:20 UTC
Opening a ROM by double click or dragging it to mgba.EXE opens an instance of the emulator with default preferences instead of your customized preferences (aka screen size, control binding, shaders, custom paths...).

Config files like **config.ini, nointro.sqlite3 and library.sqlite3** are automatically created in the ROM directory instead of using the ones in the emulator folder.

The issue appeared at some point between the last stable release and the current dev build. I only tested the portable versions (both 32 and 64bits)

Build tested: mGBA-build-2021-01-16-win64-6755-b6dbbb14abc159b9378353df2d978527f3414389 (today, website) and some earlier.
System: Windows 10 x64

**Comment by endrift** [comment] 2021-01-23 19:44
Duplicate of #2009

**Closed** 2021-01-23 19:44 UTC
