### ISSUE TITLE
Unable to save game override settings linux appimage

### ISSUE THREAD

**Issue by calvincorrieri** [mgba-emu/mgba#3219] opened 2024-05-29 08:04 UTC
Issue: clicking the save button after altering game override settings does not close the window. Clicking cancel will close the window, and the altered settings will be preserved if the window is opened again. However, the settings never take effect, and upon restarting mgba, the settings will have reverted to default. If I run a game *before* restarting mgba, it still acts as though auto detect is enabled, and changes the settings accordingly. This completely breaks Warioware Twisted, as it won’t work with rumble enabled, and it’s currently impossible to disable it.

How to reproduce: just do what I said above on the linux appimage

I am beyond frustrated after spending a ton of time attempting to get Warioware Twisted working with gyro on my steam deck. It still won’t work, and I read that having rumble enabled breaks gyro functionality. So I tried disabling it, and it won’t save the change. So f*** me in particular I guess. This damn emulator is mocking me.

oh and this behavior is present in both the latest stable and developer builds.

**Comment by leoxxx** [comment] 2024-05-31 03:15
https://github.com/mgba-emu/mgba/issues/3142
I don't know how to work on Linux. But override settings must be changed and saved on Windows before you load the game which you want to apply to. Overrides settings is confusing now. endrift will improve it.

**Comment by endrift** [comment] 2024-05-31 04:15
It's worth noting that WarioWare Twisted has rumble enabled by default and you don't need to do anything to change that. Getting the gyro working with the Steam Deck gyro is possible but the easiest way to do it involves editing the save file by hand. You also need to modify the Steam Input settings for launching mGBA.

Closing as a duplicate of #3142

**Closed by endrift** 2024-05-31 04:15 UTC
