### ISSUE TITLE
Fire Emblem The Sacred Stones - SFX volume too low

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#932] opened 2017-11-26 20:31 UTC
The difference is not immediately obvious, but I would often notice various sounds getting drowned in the music, but I tested the game elsewhere and the SFX would always sound loud and clear.

I also tested a very old build and it sounded right, so I assume it's a regression.

**Comment by endrift** [comment] 2017-11-26 20:45
Please try to narrow down when this regressed and provide examples.

**Comment by SuperrSonic** [comment] 2017-11-28 03:57
[FE8_expl.zip](https://github.com/mgba-emu/mgba/files/1508355/FE8_expl.zip)
These two audio samples should clearly show the difference.

I'm having some trouble going through recent nightlies, I checked here http://mgba.io/nightlies/1/ but it only shows up to July. I could compile but I'd like to avoid it if possible.

**Comment by endrift** [comment] 2017-11-28 05:17
The new builds are at https://mgba.io/builds/1/

**Comment by SuperrSonic** [comment] 2017-11-29 06:27
https://github.com/mgba-emu/mgba/commit/70204e410c18785a27a39af538642cd3f54e2528 last working nightly
https://github.com/mgba-emu/mgba/commit/691600902c18fbee18ba8ab12cefed8403b3c7ae first broken nightly

There's kind of a lot of commits between the two nightlies, I compiled the three GBA ones assuming they'd be the obvious choice but it still sounded right.

**Comment by endrift** [comment] 2017-11-29 06:30
15d66422a9d9404066a143298f092163834c2725 is probably where it broke. Thanks for narrowing this down, I'll take a look soon.

**Comment by endrift** [comment] 2017-12-27 17:11
Oddly it looks to me like this should have been fixed by 3ae911b829a3700338918842224fa90b71e11655, which was from before this issue was filed. Can you try a dev build that's past the nightlies (i.e. from that builds link).

**Comment by endrift** [comment] 2017-12-27 17:19
Actually caused by 539e63d49b86c097d149c4e6b003783db53d2422.

**Closed** 2017-12-27 17:41 UTC
Labels: feature:audio, platform:GBA, severity:minor bug
