### ISSUE TITLE
[Windows 0.5.2] Crash when saving controller settings

### ISSUE THREAD

**Issue by voltagex** [mgba-emu/mgba#534] opened 2017-03-05 05:58 UTC
After fighting with mGBA to map my control settings, it crashed while trying to save.

I've got an Xbox One wireless adapter with one paired controller.

![image](https://cloud.githubusercontent.com/assets/159567/23584962/f411776a-01c4-11e7-99fd-a8e9e5b97fdb.png)

I have a minidump but I'm not sure how much help it would be - it's 222MB uncompressed so it'll have to go on Mega or similar.

**Comment by endrift** [comment] 2017-07-18 05:38
Does this still reproduce?

**Comment by endrift** [comment] 2020-08-18 04:11
Closing due to lack of reply.

**Closed by endrift** 2020-08-18 04:11 UTC
Labels: category:needs retest, port:Qt, severity:host crash
