### ISSUE TITLE
Mario and luigi superstar saga crashing during gameplay

### ISSUE THREAD

**Issue by Fishyboi2140** [mgba-emu/mgba#2305] opened 2021-09-13 00:40 UTC
i haven't used mgba for long and i'm not certain if it's crashing but sometimes i randomly get thrown out into the title screen and it can get annoying if i haven't saved for a while.

**Comment by endrift** [comment] 2021-09-13 00:58
Duplicate of #1059

**Closed** 2021-09-13 00:58 UTC
