### ISSUE TITLE
The shotcut key setting does not work.

### ISSUE THREAD

**Issue by kpldgba8289** [mgba-emu/mgba#2726] opened 2022-11-18 07:04 UTC
I set the Apostrophe ( ' ) key to fast forward, but it didn't work in the real game. This part needs to be modified.

**Comment by endrift** [comment] 2022-11-18 07:06
Try a different key. Apostrophe can be buggy at times, in my experience. I'm not sure why. But I assure you it's not 100% broken.

**Comment by kpldgba8289** [comment] 2022-11-18 09:33
Unfortunately, the Apostrophe key is the best for my play. So I'll wait for an update where the Apostrophe key works properly.

**Comment by endrift** [comment] 2022-11-18 09:34
I'm asking for diagnostic reasons. Please check if other keys work. That will help me know if it's apostrophe specific. Please also upload a bug report zip (File > Report Bug) so I don't have to ask for additional information a bunch of times.

**Comment by kpldgba8289** [comment] 2022-11-18 09:38
The key from a to z is working. However, other than the default TAP key, there are cases where the key does not work when the mGBA is completely shut down and restarted.

**Comment by endrift** [comment] 2022-11-20 01:39
Duplicate of #2636

**Closed by endrift** 2022-11-20 01:39 UTC
