### ISSUE TITLE
Directory Path Configuration

### ISSUE THREAD

**Issue by Papermanzero** [mgba-emu/mgba#198] opened 2016-01-08 14:10 UTC
It would be great to add a feature to configure the folder/directory path for savestates, roms etc.
Currently all savestates will be saved within the roms folder.
However some users would like to have the saves in a seperated folder.

**Comment by endrift** [comment] 2016-01-08 23:36
Dupe of #86. It's in progress at the moment.

**Closed by endrift** 2016-01-08 23:36 UTC
