### ISSUE TITLE
A+ R B+L A+B and L+R macro options

### ISSUE THREAD

**Issue by sergioad** [mgba-emu/mgba#2583] opened 2022-07-08 17:02 UTC
Hello everyone could you please add A+ R B+L A+B and L+R macros to the button settings? You have already turbos, the macros would allow us to play Super Street Fighter II Turbo Revival in a 6 button layout while using an arcade stick or fightpad

**Comment by endrift** [comment] 2024-01-27 06:56
Duplicate of #87

**Closed by endrift** 2024-01-27 06:56 UTC
