### ISSUE TITLE
mGBA's checkmark next to the current Frame size doesn't stick around after exiting.

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba#88] opened 2015-08-17 23:28 UTC
As of 0.3.0 stable, mGBA will not show a checkmark next to '2x' under the 'Frame size' submenu, even though that's the frame size it's using by default.

You can get it to show up by selecting '2x' yourself via the GUI but once you exit and reopen mGBA, the checkmark will be gone, thus making it a separate issue from #25.

Possibly related:
https://github.com/mgba-emu/mgba/issues/77

OS: Windows 8.1 x64

**Comment by endrift** [comment] 2015-08-17 23:29
Different bug, but known bug nonetheless. I tried to fix it before 0.3.0 but I was unable to do so quickly.

**Comment by endrift** [comment] 2015-10-10 23:05
This is the result of the window size being a different value when opening the application than the window actually is when the window "settles", and I had a lot of trouble fixing it, so I might just punt this since it's...not really an important bug that's been holding up 0.3.1.

**Comment by karasuhebi** [comment] 2015-10-11 05:49
Punt is fine by me. How is it a different size though? The size doesn't change when I click on the right frame size. It's the same.

**Comment by endrift** [comment] 2015-10-11 05:55
When I open a window, I check to see what it reports the size as, and for some reason it reports the wrong size at first. I might be able to kludge in a second check after the window is fully initialized, but I'm not sure that wouldn't break things.

**Comment by CharlesCorrin** [comment] 2016-08-30 23:07
It does the same thing with the FPS target. Set it, then open Settings. The checkmark next to the FPS target object will disappear (the setting is native for me).

**Comment by CharlesCorrin** [comment] 2016-08-30 23:18
FPS target is actually still affected. Choose something from the FPS target menu (I choose native). Then go to Settings. The checkmark in FPS target vanishes.

**Comment by endrift** [comment] 2016-10-04 20:13
This should finally be fixed in 0b2f8bb4dcf74ffc0bd28c7349e73450aea4010d, but I still need to test on Windows.

**Comment by endrift** [comment] 2016-10-04 21:05
Confirmed on Windows.

**Closed by endrift** 2016-10-04 21:05 UTC
Labels: minor bug
