### ISSUE TITLE
Multi-rom archives do not work with "Recent Files" list.

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#592] opened 2017-04-10 01:23 UTC
If you load a multi-rom archive and pick a rom and quit, if you try to load that game via "Recent Files" list, the emulator will load the first rom listed in the archive, not the actual rom you were playing.

**Comment by endrift** [comment] 2017-04-10 01:24
Dupe of #413.

**Closed by endrift** 2017-04-10 01:24 UTC
