### ISSUE TITLE
Update channel keeps changing itself to Development even when Stable is selected

### ISSUE THREAD

**Issue by MatthewLachlanBrown** [mgba-emu/mgba#2739] opened 2022-11-29 19:46 UTC
I keep trying to set the Update Channel to stable, but every time I reopen mGBA it has changed the channel to Development. Using V0.10.0 on Windows Version 10.0.19044.2251.

I've attached a Bug Report since it was asked for, though I'm not sure it will help in this case: 
[bugreport.zip](https://github.com/mgba-emu/mgba/files/10116754/bugreport.zip)

**Comment by SuperfieldCU** [comment] 2022-11-30 03:05
This also happens to me. Are you experiencing any troubles with the auto-updater itself?

**Comment by endrift** [comment] 2022-12-07 08:42
Duplicate of #2679.

**Closed by endrift** 2022-12-07 08:42 UTC
