### ISSUE TITLE
Crash on Megaman Zero 4 (U) opening scene 

### ISSUE THREAD

**Issue by FelipeLopes** [mgba-emu/mgba#1516] opened 2019-09-02 00:44 UTC
When loading the GBA ROM Megaman Zero 4 (U), starting new game from an empty save, and watching the opening scene, where some robots are chasing some trucks, suddenly the video gets locked up and sound becomes completely glitchy.

The game is still playable, because you can skip this cutscene.

ROM CRC is 2128758675, logs do not show anything.

**Comment by endrift** [comment] 2019-09-02 01:54
I cannot reproduce. What version of the emulator are you using?

**Comment by FelipeLopes** [comment] 2019-09-02 09:39
Version 0.7.2, Ubuntu 18.04, the version in flatpak.

**Comment by Testsr** [comment] 2020-01-26 23:00
Cannot reproduc either.
Retroarch Windows mgba 0.8.0. This bug should be closed.

**Comment by endrift** [comment] 2020-12-04 07:14
Are you still able to reproduce this in mGBA 0.8.4?

**Comment by endrift** [comment] 2021-02-01 09:49
Closing due to lack of reply.

**Closed by endrift** 2021-02-01 09:49 UTC
Labels: blocked:needs info, blocked:needs retest
