### ISSUE TITLE
Shutdown option keeps handle on rom files

### ISSUE THREAD

**Issue by AsparagusEduardo** [mgba-emu/mgba#1659] opened 2020-02-02 17:33 UTC
I don't know if this intentional behaviour, but by using the shutdown option it doesn't let me recopile the rom file.

![image](https://user-images.githubusercontent.com/2904965/73612055-1ddc3280-45c7-11ea-9162-d97e284d6f01.png)

**EDIT**: Tried it in 0.7.2 and 0.7.3 and the issue doesn't happen, so it must've been introduced in 0.8.0

**Comment by endrift** [comment] 2020-02-02 22:31
On my end it looks like it's just the window title not getting updated; the file handle appears to be closed. Did you have any other windows open when you hit Shutdown?

**Comment by AsparagusEduardo** [comment] 2020-02-03 20:43
No, I didn't have any other mGBA windows open
I was referred to make an issue report from the pokeemerald project Discord when I tried compiling after pressing Shutdown, and they told me that the common issue with that error is the file handle being open.
![image](https://user-images.githubusercontent.com/2904965/73689060-235f7880-46ac-11ea-8b81-67fb59a54fca.png)

**Comment by endrift** [comment] 2020-02-03 23:00
So I can reproduce this, but the file handle has definitely been closed. Process Explorer can't see it. I wonder if I'm not unmapping the memory properly before closing it.

**Comment by endrift** [comment] 2020-02-04 20:00
Should have a fix for this tonight.

**Closed** 2020-02-05 04:16 UTC
Labels: os:Windows, port:Qt
