### ISSUE TITLE
Boot Bios creates a white screen

### ISSUE THREAD

**Issue by GyoMan** [mgba-emu/mgba#3370] opened 2024-12-12 17:11 UTC
Worked fine a few development versions ago.

**Comment by GyoMan** [comment] 2024-12-13 23:39
![image](https://github.com/user-attachments/assets/10abeb12-1f0a-42dd-b695-af698b67c322)

Use Bios file if found is checked, skip bios intro unchecked. I use the same firmware.bin i used a few weeks ago. MGBA runs in portable mode and i tried a couple of different bios files. I only updated the AMD drivers but i had no problem with anything else. OpenGL & Software give the same results. The games run normally.

**Comment by endrift** [comment] 2024-12-13 23:42
I'm unable to reproduce. The fact that the fps isn't showing in the title makes me think it's a sync issue. Please upload a zip generated by File > Report Bug.

**Comment by GyoMan** [comment] 2024-12-14 08:41
Withe the latest nightly, FPS is shown on the title when i choose Boot Bios, but the screen remains the same.

[report.zip](https://github.com/user-attachments/files/18135135/report.zip)

**Comment by Squall-Leonhart** [comment] 2024-12-14 13:31
Adrenaline 24.9.1 broke opengl shaders, if you turn it off you should see the boot rom, i assume you've been hearing it all this time

**Comment by GyoMan** [comment] 2024-12-14 13:37
I still have the same results if i set the display driver to software QT.

**Comment by Squall-Leonhart** [comment] 2024-12-14 14:09
Uh, please tell me you've not been using the Sameboy agb-boot binary?

I can replicate what you're seeing with that, but its because it doesn't have the animation in the first place.

**Comment by GyoMan** [comment] 2024-12-14 14:24
I was using a bios from retroarch. But now i tried a bios with "a860e8c0b6d573d191e4ec7db1b1e4f6" md5 and this displays the animation correctly!

**Comment by endrift** [comment] 2024-12-15 06:29
Original report was not a bug, but the skip BIOS setting version was one and is now fixed.

**Closed by endrift** 2024-12-15 06:29 UTC
