### ISSUE TITLE
mgba fails to compile on mingw-w64

### ISSUE THREAD

**Issue by rootfather** [mgba-emu/mgba#739] opened 2017-05-16 05:29 UTC
On the current master code, mgba fails to compile for me. I just pulled the latest source code, so in my opinion it is likely that the issue got introduced very recently (I usually compile each and every day a new commit is made to the mgba branch).

```[ 99%] Building CXX object qt/CMakeFiles/mgba-qt.dir/qrc_ts.cpp.obj
make[2]: *** Keine Regel vorhanden, um das Ziel „qt/mgba-qt_autogen/moc_compilation.cpp“,
  benötigt von „qt/CMakeFiles/mgba-qt.dir/mgba-qt_autogen/moc_compilation.cpp.obj“, zu erstellen.  Schluss.
make[1]: *** [CMakeFiles/Makefile2:215: qt/CMakeFiles/mgba-qt.dir/all] Fehler 2
make: *** [Makefile:152: all] Fehler 2
```

Sorry for the German localization. "Keine Regel..." means "No rule to build target..., needed by ..." Error 2.

regards
rootfather

**Comment by endrift** [comment] 2017-05-16 06:10
This just looks like you need to rerun CMake

**Comment by rootfather** [comment] 2017-05-16 12:09
Sadly, this didn't fix the issue for me. I did a rerun of CMake and even started completely from scratch by deleting and re-creating my build directory.

During compilation, the compiler drops the message `RCC: Warning: No resources in 'C:/msys64/home/username/mgba/build/qt/ts.qrc'.` which might be related.

**Comment by endrift** [comment] 2017-05-16 17:13
What the

I wonder if @waddlesplash broke this somehow

**Comment by waddlesplash** [comment] 2017-05-16 17:24
I don't think so? I have, however, continually run into some really nasty automoc bugs that I haven't found a solution for, like CMake generating incorrect ninja rules for automoc and infinitely looping on rerunning automoc, of which there is no solution except for ... manually creating a file inside the CMakeFiles directory called "mgba-qt_automoc". Go figure.

So, maybe try deleting and re-generating the build directory with the Ninja generator and see if you run into that problem...

**Comment by waddlesplash** [comment] 2017-05-16 20:24
Actually, poking around a bit, it looks like this might be related to the enable_language call -- it seems CMake actually sets up a pseudo-subproject with its own make chain because of that, which might be the source of all these oddities. If the CMakeLists could be reworked to remove that, things might improve substantially here.

**Comment by endrift** [comment] 2017-05-16 20:26
You mean the one that's been there since the beginning of time? I...don't think that's the problem.

**Comment by waddlesplash** [comment] 2017-05-16 20:27
I don't know what else would cause CMake to create a pseudo-subproject. I'll investigate further.

**Comment by waddlesplash** [comment] 2017-05-16 20:42
So, uh, I removed the enable_language and subsequently the "C" from the end of the root project() call and CMake no longer creates a pseudo-subproject when generating build files, which does help with a few things.

The moc infinite recursion was not fixed by this -- but it IS fixed by disabling the entire `if(Qt5LinguistTools_FOUND)` block (!?).

**Comment by rootfather** [comment] 2017-05-18 06:45
Thanks for your investigations. Does it make sense to test compilation again at this point?

**Comment by waddlesplash** [comment] 2017-05-18 11:18
Yes. Try again with nothing modified at first, and then try disabling the Qt5LinguistTools_FOUND block if it still fails, and see what happens.

**Comment by rootfather** [comment] 2017-05-18 12:49
Uhm... currently it seems that neither the current codebase nor disabling the Qt5LinguistTools_FOUND block changes anything... compilation still fails and the same compiler error appears as before.

However, if I disable the Qt5LinguistTools block, CMake starts to complain that the "UPDATE_TRANSLATION" variable is not used when generating the new Makefiles.

**Comment by endrift** [comment] 2017-05-19 07:22
This is a regression introduced by CMake 3.8; it's not a recent bug in mGBA.

**Comment by endrift** [comment] 2017-05-19 07:57
So...adding `set(CMAKE_AUTOUIC ON)` fixes this, but...if we're using autouic then all of the ui stuff isn't needed anymore.

Problem: autouic was added in 3.0, but our minimum version is 2.8, as constrained by supporting Trusty still. Not sure what to do about this :/

**Comment by endrift** [comment] 2017-05-19 22:20
Filed https://gitlab.kitware.com/cmake/cmake/issues/16907 for the upstream bug.

**Closed** 2017-05-19 23:03 UTC

**Comment by rootfather** [comment] 2017-05-20 06:25
Fix confirmed, thank you!
