### ISSUE TITLE
[Vita] Black screen, visible character at random points in Megaman Zero 2

### ISSUE THREAD

**Issue by Zeroba** [mgba-emu/mgba#350] opened 2016-08-17 08:16 UTC
Sorry about the previous 'issue', but this one seems to be something bringing up.
At random points through Megaman Zero 2, everything but Zero himself will become black and stay that way until death, where it'll happen again.
If this is know, my bad.
Tried 2 different dumps, however still won't rule out the possibly of both having something off about them.

**Comment by endrift** [comment] 2016-08-17 08:17
Haven't heard of this one. Can you send a savestate after it happens, and a savegame so I can load it up and play around with it?

**Comment by Zeroba** [comment] 2016-08-17 08:30
Hmm, seems loading the save state actually fixes the issue oddly enough, but it's EXTREMELY intermittent. I'll try to find out what causes it to happen, so far it seem like taking damage does it.

**Comment by Zeroba** [comment] 2016-08-17 08:35
Nope, just seems completely random. I can upload a screenshot though I'm sure that won't really help.
Want a save-state just to get past the intro and see if you can trigger it to happen in your build/dump of the game?

**Comment by Zeroba** [comment] 2016-08-17 08:43
https://www.youtube.com/watch?v=4WPlYa1v3fE
Sorry for the shoddy camera work lol.

**Comment by OTFree** [comment] 2016-08-17 15:28
Actually, this glitch seems to occur at random when playing any game
without proper bios.

**Comment by Zeroba** [comment] 2016-08-17 18:34
Odd, considering I'm using the same bios I've never had an issue with for years and pointing mGBA at it and getting the bios splash screen in the beginning of loading. Also only noticed it on Zero

**Comment by endrift** [comment] 2016-08-17 18:35
This might be the threaded renderer crashing. Try opening the menu and then closing it.

**Comment by OTFree** [comment] 2016-08-17 18:37
Huh, that is bizarre. I've only ever been able to replicate this glitch
using auto bios that mGBA provides. Has happened with Pokemon Pinball,
Kirby Nightmare in Dreamland and TLoZ: Minish Cap. I can't recreate any on
command, seems sporadic and related to on screen rendering issues.

Usually, going to a different screen or reloading an area fixes the problem.

**Comment by endrift** [comment] 2016-08-17 18:38
Yep, that sounds like the threaded renderer crashing. If you add the lines "logLevel=3" to the config.ini under [ports.psvita], you should get info in the log file about it after it happens that will let you know if that's what the problem is.

**Comment by Zeroba** [comment] 2016-08-17 18:49
Heading to work soon, if OTFtee doesn't grab you that log I can after work :)

**Comment by OTFree** [comment] 2016-08-17 18:56
Actually...I'm heading to work in a half hour as well haha.

Will try to test afterwards!

**Comment by endrift** [comment] 2016-08-18 07:05
This should be remediated by 041113b09cb8ac12b132cd2be03d3489966376d3 and actually fixed by c3b411fb6b99e91f6f8582f699345806099facf2. Let me know when the next nightly lands.

**Comment by endrift** [comment] 2016-08-24 18:11
I'm pretty sure this is fixed. Let me know if it's not and I'll reopen.

**Closed by endrift** 2016-08-24 18:11 UTC
Labels: GBA
