### ISSUE TITLE
Export the Thumb code from gba roms

### ISSUE THREAD

**Issue by Mte90** [mgba-emu/mgba#1714] opened 2020-03-31 22:54 UTC
I am trying to replicate this tutorial https://web.archive.org/web/20071012203301/http://etk.scener.org/?op=showtutorial&st=2 with mgba and right now is not a problem do the search and change the value in memory.
The second part refer to search using the debugger but as I can see the interface is different, I am facing https://github.com/mgba-emu/mgba/issues/1649 so right now for me add a breakpoint to the ram address where is the value is not possible.

PS: using okteta on linux isn't a problem I patched at the value they said, I am just disappointed that I cannot get the Thumb of the whole rom.

Instead because I was thinking how to automatize a bit patching (yeah I have few ideas, you know quarantine for covid) I was thinking that instead I can patch or add a new command to mgba to export the whole Thumb code that the emulator parsed (I didn't found a way to get just the code like radare2 can do in a file).
In this way I can search the code that involve the memory address I am looking.

About mgba there isn't so much documentation but looking on github or on the official forum (now closed for new users) I saw that people prefer to do a fork (instead to contribute back) like in this case where he investigates the Thumb code with another tool https://sideway.re/Reverse-Engineering-alttp-GBA-ep1/

In my thoughts will be more simple to get a file so everyone can do their analysis as they prefer.

**Comment by RetroEdit** [comment] 2020-04-05 22:09
One way some emulators handle the problem of separating code from other assets is using what they call a "Code-Data logger". Usually this works by creating a new "mirror" ROM where each byte indicates whether the original ROM's data was code or assets.

For just getting a code dump, I generally use no$gba feature of `Utility > Disassemble to File`, which allows the whole ROM to be decoded. It's a bit janky to use, as it just takes whatever type of code is currently being run (ARM vs. Thumb) and decodes the whole selection using only that selection. The output from this is formatted, so it's not really ideal for programmatic use (though most of the formatting can be disabled). mGBA unfortunately does not appear to provide a convenient way to decode an arbitrary-length collection of bytes that are not currently being run. mGBA also has the drawback that it doesn't appear to currently be possible to filter the formatting for decoding, so each line will have the register states, which is not necessarily always wanted.

**Comment by endrift** [comment] 2020-08-14 07:21
This is more or less a duplicate of #1629, at least in terms of how it would be implemented, so I'll track it there.

**Closed by endrift** 2020-08-14 07:21 UTC
