### ISSUE TITLE
Flickering Window in FFVI Advance

### ISSUE THREAD

**Issue by ASillyWalker** [mgba-emu/mgba#2059] opened 2021-03-05 04:57 UTC
Mainly noticed in Figaro and while using Shadow’s Bushido ability. RetroArch core and mGBA standalone, happens on latest macOS and Windows 10 releases.
![image](https://user-images.githubusercontent.com/80085881/110068816-20660a00-7d3c-11eb-9879-0ec4b632afbe.jpeg)
![image](https://user-images.githubusercontent.com/80085881/110069448-6cfe1500-7d3d-11eb-9cb0-b1f01021a47f.png)
![image](https://user-images.githubusercontent.com/80085881/110069488-87d08980-7d3d-11eb-8a65-3d326d9f458f.png)

**Comment by endrift** [comment] 2021-03-05 05:12
Duplicate of #1846 most likely. This has been fixed but the fix hasn't made it into a stable release yet.

**Closed by endrift** 2021-03-05 05:12 UTC
