### ISSUE TITLE
Hello Kitty Collection - Miracle Fashion Maker (Japan) black screen

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#1320] opened 2019-02-23 06:18 UTC
using 0.7.0
nothing but a black screen

**Comment by endrift** [comment] 2019-02-23 06:19
Old bug, never looked into it too deeply.

**Comment by endrift** [comment] 2019-02-24 04:05
Doesn't boot in any emulator. Does work on hardware though. This appears to have a similar root cause to #301 where it's reading a value from RAM and expecting it to be non-zero but it never sets it.

**Comment by endrift** [comment] 2019-04-29 03:17
Looks like the RAM address (0x0200002C) gets initialized (to 0x02000140) right after the function that dies gets called. Confirmed that it gets to 0x080427AA on hardware, so it's not initialized properly on hardware yet I don't think, but for some reason it managed to break out of the loop on invalid RAM it gets into (it looks like it's trying to crawl a linked list, but the linked list is all invalid memory).

**Comment by endrift** [comment] 2020-01-25 02:11
Fixed in 93633ea60.

**Closed** 2020-01-25 02:10 UTC
Labels: platform:GBA, severity:boot failure, severity:holy grail

**Comment by michelhe** [comment] 2020-01-27 19:10
Hey @endrift 
I've read the blog post you made about this issue, thank you for the wonderful read! 👍 
I myself toy with developing a GBA emulator in rust, and this game is booting successfully for me.
I suppose its due to that I'm not implementing the "open bus" behavior at all, I just return 0 for invalid memory region accesses, or mask out invalid address bits if the region is correct. 
When I move on to implement open-bus, I will sure take into account the DMA lingering on the bus 😄

**Comment by endrift** [comment] 2020-01-27 19:16
If you're wondering why Minish Cap hangs when you leave the house at the beginning of the game, that's because you don't have open bus emulated

**Comment by michelhe** [comment] 2020-01-27 19:19
Sadly I did not get to experience that because I don't emulate EEPROM saves , but I will get there soon enough.

**Comment by qamichele5959** [comment] 2021-12-03 00:08
#2370 This Ubisoft Driv3r Game keeps frozen(?)

**Comment by qamichele5959** [comment] 2021-12-03 00:13
#2372 cube frenzy still gets into title then errdisp message "An error occurred (ErrDisp)" on bottom screen.
