### ISSUE TITLE
Multiplayer link for gbc game not working

### ISSUE THREAD

**Issue by Seraphiou** [mgba-emu/mgba#1398] opened 2019-04-28 16:02 UTC
![first-game-save](https://user-images.githubusercontent.com/2487794/56866952-e4471d00-69df-11e9-8a25-2eed241030ce.png)
![second-game-save](https://user-images.githubusercontent.com/2487794/56866954-e4471d00-69df-11e9-8a8f-bba4295bb3df.png)

Branch: heads/0.7.1
Revision: d93e042e5bb10341f7d9cc4832f287b1e2626779
OS: MacBook Pro version 10.13.6
Graphics: Intel Iris Graphics 6100 1536 Mo
CPU: 3,1 GHz Intel Core i7

Hi i'm trying to link pokemon Cristal in separate folders with multiplayer mode and synchronized audio.

When I am going in a pokemon center to do an exchange, entering the exchange mode simultaneously, the game tells me that the _friend is not ready_.

**Comment by rtandy** [comment] 2019-08-24 18:55
I guess this could be another dupe of #854? Depending on sync settings I sometimes get the behaviour described there (freezing/not syncing), sometimes the behaviour described here (no freezing, just not detecting the link).

**Comment by endrift** [comment] 2019-08-24 22:12
It's not a dupe of that but I'm pretty sure I fixed it already. Can't find the commit though.

**Comment by endrift** [comment] 2021-02-28 00:29
This seems to work for me in dev builds. Can you retry with the latest dev version?

**Comment by endrift** [comment] 2021-04-02 04:34
Closing due to lack of reply. Please respond if you have more info and I can reopen it.

**Closed by endrift** 2021-04-02 04:34 UTC
Labels: blocked:needs retest, platform:GB/GBC
