### ISSUE TITLE
Metroid II - Return of Samus (World) codes stay on even if not checked.

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#963] opened 2018-01-14 21:37 UTC
Metroid II - Return of Samus (World) codes stay on even if not checked. SHA-1 74A2FAD86B9A4C013149B1E214BC4600EFB1066D codes came from here. https://gamehacking.org/game/999

Here is a video of the problem. 

https://www.youtube.com/watch?v=0Q5g4LW6VzI&feature=youtu.be

**Comment by endrift** [comment] 2018-01-14 22:19
Almost certainly a dupe of *the issue you filed like 2 hours ago*.

**Comment by Cibomatto2002** [comment] 2018-01-14 22:59
I just wanted you to know it's a problem with this game the other game was just the one code that I found. This game it's all that I have tried.

**Comment by endrift** [comment] 2018-01-15 03:32
Confirmed dupe of #962.

**Closed by endrift** 2018-01-15 03:32 UTC
