### ISSUE TITLE
Closing emulator/shutdown causes system to freeze for a few seconds

### ISSUE THREAD

**Issue by aquova** [mgba-emu/mgba#2069] opened 2021-03-21 16:38 UTC
Whenever I exit the emulator while it is running, or attempt to close the current ROM via the "Shutdown" menu option, it causes my entire system to freeze for roughly 3 or 4 seconds. Screens do not refresh, cursor is unable to be controlled, etc. After a few seconds the game stops and system behavior returns to normal. This behavior is seen on all of the games I've tested, although it doesn't seem to happen if the game is closed rather quickly. Usually getting to a game's main menu screen is long enough however.

OS: Arch Linux
DE: GNOME 3.38.4
mGBA version: 0.8.3, installed via the mgba-qt Arch package
Games tested: Issue seen on Final Fantasy VI Advance, Kingdom Hearts: Chain of Memories, Sonic Advance, Golden Sun, Super Mario Advance, many others
CPU: Ryzen 5 2400G
GPU: Nvidia GTX 1660 Super

**Comment by brainard52** [comment] 2021-03-21 19:01
> mGBA version: 0.8.3, installed via the mgba-qt Arch package
Looks like 0.8.4 was released according to https://archlinux.org/packages/community/x86_64/mgba-qt/. Does it still happen with that?

**Comment by aquova** [comment] 2021-03-21 19:23
Huh, I have the most up-to-date version of the package, which pacman identifies as 0.8.4, yet my application identifies itself as 0.8.3. I also notice that while the PKGBUILD file for libmgba is set for 0.8.4, only libmgba.so.0.8 and libmgba.so.0.8.3 are included as package contents.

**Comment by endrift** [comment] 2021-03-21 19:25
That's probably #1923 at work.

**Comment by brainard52** [comment] 2021-03-23 19:55
I'm willing to bet that it has to do with Qt. @aquova If you create a new user account, does the issue occur there?

**Comment by endrift** [comment] 2021-03-23 19:57
Also possible: there's currently a bunch of slowdown with large libraries (fixing this is slated for 0.10 unfortunately), so if you have a large library.sqlite3 file I might recommend moving it aside to see if it fixes it.

**Comment by aquova** [comment] 2021-03-23 22:18
I created a new user account, and in it I was able to reproduce the issue, although it wasn't as reproducible. 

My library.sqlite3 file was about 38 KiB, and moving it didn't have any affect, I was still able to reproduce.

**Comment by brainard52** [comment] 2021-03-23 22:40
If you run it from a terminal, does it show any important messages?

**Comment by profi200** [comment] 2021-03-24 02:08
Since this has not been mentioned yet you might wanna look at dmesg output. Maybe the GPU driver is crashing or something.

**Comment by endrift** [comment] 2021-03-24 02:10
Do you know if you're using X11 or Wayland?

**Comment by aquova** [comment] 2021-03-24 04:20
When running from a terminal, no messages are printed

dmesg did not produce any message during the freeze. However, journalctl logs `/usr/lib/gdm-x-session[8422]: (WW) NVIDIA: Wait for channel idle timed out.` every time it occurs. I am using the proprietary nvidia drivers. 

I am on X11

**Comment by endrift** [comment] 2021-03-24 04:25
Googling the error (with the number removed--that's just the process ID) seems to indicate this happens in other circumstances too, and is correlated with a bad driver version.

**Comment by endrift** [comment] 2023-02-09 10:12
Does this still reproduce with modern drivers?

**Comment by aquova** [comment] 2023-02-11 20:45
I have not seen this issue in quite some time

**Closed** 2023-02-11 20:54 UTC
Labels: blocked:needs retest
