### ISSUE TITLE
Rotate the screen.

### ISSUE THREAD

**Issue by SuperFlomm** [mgba-emu/mgba#455] opened 2016-11-02 20:39 UTC
I don't know if there are any commercial games that requires you to hold your GBA sideways or upside down. [But there is a homebrew Flappy Bird clone that does.](https://youtu.be/SNm9kNV9rnw?t=11s)

So, I think there should be an option that allows you to turn the screen by 90, 180 and 270 degrees.

**Comment by endrift** [comment] 2016-11-02 21:58
Dupe of #179. #187 did some work towards it but my nits were never fixed so it didn't get merged.

**Closed by endrift** 2016-11-02 21:58 UTC
Labels: duplicate

**Comment by Korubiiii** [comment] 2024-09-19 02:45
so is this just never going to be added as a feature?

**Comment by jtolio** [comment] 2024-10-05 13:20
Dr Mario and Puzzle League have a mode where the screen is sideways.
