### ISSUE TITLE
Crash after new update

### ISSUE THREAD

**Issue by TigreRoxo** [mgba-emu/mgba#2138] opened 2021-04-22 13:22 UTC
[MSlug.zip](https://github.com/mgba-emu/mgba/files/6358396/MSlug.zip)
[PK FR.zip](https://github.com/mgba-emu/mgba/files/6358397/PK.FR.zip)
After update 0.9.1 all my games crashed after a few moments of gameplay, I tried to change some settings but with no luck. I took the liberty of sending you two different game files since I don't know what would be most useful to solve the bug, the pokemon one was made when it crashed, the metal slug one was made after a little stutter before crash.
I am regressing to version 0.9.0 as it works just fine.
Sorry for my poor English and also greetings from Brazil.

**Comment by endrift** [comment] 2021-04-23 07:39
That's an old CPU. Can you see if setting the display driver setting to "Software" instead of "OpenGL" fixes it?

**Comment by TigreRoxo** [comment] 2021-04-23 12:13
Changing before opening the game gave me a white screen and the game does not start, and changing while the game runs freezes the image and the audio disappears until I return to OpenGL, I tested it in version 0.9.0 and both options are flawless

**Comment by endrift** [comment] 2021-04-23 22:30
Disable video sync and try again, please. Video sync does not work with the software driver.

**Comment by TigreRoxo** [comment] 2021-04-23 23:47
> 
> 
> Disable video sync and try again, please. Video sync does not work with the software driver.

Sorry, I had no idea, it worked, and it looks like the crashes are gone. Thanks!

**Comment by TigreRoxo** [comment] 2021-04-24 00:37
Knowing that video sync does not work with the software, I tested OpenGL without video sync, and it worked as expected and I can activate it during gameplay, but if video sync + OpenGL has been activated since before opening the ROM it will crash after a few moments. (To be more precise, the game freezes but I can still navigate the emulator menus, however when trying to close or minimize the window then the emulator itself crashes, showing the windows message: application is not responding)

**Comment by endrift** [comment] 2021-04-24 04:05
I am _pretty sure_ this is a duplicate of #2137. I just put out a new dev build that might have a fix for that so please try that too.

**Comment by TigreRoxo** [comment] 2021-04-24 11:43
I tried build 0.10-6962-967cc0886, and I still can't use video sync + OpenGL at the same time.

**Comment by endrift** [comment] 2021-04-26 02:02
I was able to trigger more deadlocks so I removed some code that I thought _might_ be causing it, so please try again with latest dev.

**Comment by TigreRoxo** [comment] 2021-04-26 12:02
I tried the latest build and the issue is gone, the sync to video option no longer crashes!

**Closed** 2021-04-26 18:10 UTC
Labels: blocked:needs retest, severity:host crash
