### ISSUE TITLE
Crash/Hang in Gradius Galaxies Stage 3

### ISSUE THREAD

**Issue by Zylysh** [mgba-emu/mgba#2091] opened 2021-03-29 13:14 UTC
Found in mGBA 0.9.0, Windows x64 build on Windows 10 64-bit.
In Stage 3, there's a section where there are many fireballs that emit 3 projectiles each. If too many projectiles and fireballs are on the screen, the game hangs or crashes. This can be avoided by continually moving upward/downward to de-spawn the fireballs. When the game crashes, the dialogue box says "Jumped to invalid address: FFFFFC80" or a similarly high value. The attached file was generated using the bug reporter and includes a save state in the area where the bug occurs.

[Gradius Galaxies.zip](https://github.com/mgba-emu/mgba/files/6221895/Gradius.Galaxies.zip)

**Comment by endrift** [comment] 2021-03-29 17:13
You appear to have a bad dump. I'm having trouble reproducing this on a good dump (but maybe I'm just bad at the game).

**Comment by Zylysh** [comment] 2021-03-29 17:40
I tested the stage out again on my dump and a good dump and neither produced the bug. I have to assume it was the savestate, as I was using them extensively in my playthrough.

**Comment by endrift** [comment] 2021-03-29 17:42
Unfortunate but possible. There are still savestate bugs lurking.

**Comment by endrift** [comment] 2021-04-18 08:01
Though I was never able to reproduce, this was likely caused by the same root issue as #2097, which has been fixed. Tentatively closing this, and you can let me know if it reproduces it dev or 0.9.1 when it comes out.

**Closed by endrift** 2021-04-18 08:01 UTC
Labels: feature:savestates, platform:GBA
