### ISSUE TITLE
Sword of Mana crashing

### ISSUE THREAD

**Issue by rraab8** [mgba-emu/mgba#423] opened 2016-10-02 23:02 UTC
I started playing Sword of Mana and it crashed at the beginning part where you're in the cell and after it asks what the girls name is it crashes. It happens consistently, I also made a save right before the crash if you want the save file.

I'm on Windows 10 with an Intel i5-4200u and an intel 4400 gpu. I'm using version 0.5.0 of mgba.

**Comment by endrift** [comment] 2016-10-02 23:08
Please upload the save. Thanks.

**Comment by rraab8** [comment] 2016-10-02 23:48
[](url)

**Comment by rraab8** [comment] 2016-10-02 23:53
[1267 - Sword of Mana (U)(Mode7).zip](https://github.com/mgba-emu/mgba/files/505319/1267.-.Sword.of.Mana.U.Mode7.zip)

**Comment by endrift** [comment] 2016-10-04 05:51
Can't reproduce on OS X. Will try on Windows. Are you using a BIOS?

**Comment by rraab8** [comment] 2016-10-04 05:54
I'm not using a BIOS.

**Comment by endrift** [comment] 2016-10-04 05:55
Were you loading any savestates when this happened? Savestates are broken in 0.5.0, and are fixed in the nightlies. Please try a nightly.

**Comment by rraab8** [comment] 2016-10-04 06:00
I played up to that part without savestates and it didn't crash. Must be the savestates issue. Thanks for helping with this issue.

**Comment by endrift** [comment] 2016-10-04 06:00
I could confirm the crash only with savestates and only in 0.5.0, not the nightlies. Looks like it was the savestate bug again, which is fixed now.

**Closed by endrift** 2016-10-04 06:00 UTC
Labels: GBA
