### ISSUE TITLE
[Feature Request] Add support for Retro Achievements

### ISSUE THREAD

**Issue by Ansem93** [mgba-emu/mgba#2519] opened 2022-05-11 10:06 UTC
Hi,
I discovered recently Retro Achievement. They add achievement for old games using libretro.
http://retroachievements.org/

Would it be possible to add retro achievement support in mgba?

**Comment by endrift** [comment] 2022-05-11 21:23
Duplicate of #2232

**Closed by endrift** 2022-05-11 21:23 UTC
