### ISSUE TITLE
Flickering graphics after opening/closing text windows in Final Fantasy 1 (GBA)

### ISSUE THREAD

**Issue by MrGaussRA** [mgba-emu/mgba#1919] opened 2020-10-29 02:40 UTC
Version: 0.8.3 - 683ba98
Running on: RetroArch 1.8.8 in RetroPie
Also present in the same build running on LibRetro on Windows 10.

Description:

When playing Final Fantasy 1 and talking to any NPC, small graphic glitches will sometimes flash in the screen as the text window opens or closes. Those graphical glitches are, for the most part, temporary and will stay on the screen for only some frames. Sometimes, however,  those graphic glitches may stay on the screen until it is refreshed (talking again to someone to open a new text window, opening the menu or transitioning from one map to another).

It's very difficult to capture the version o the glitch that is temporary because it happens too fast. Here I include a picture of the glitched screen in the permanent version of this glitch.

![20201028_233849](https://user-images.githubusercontent.com/48816664/97518883-eb553f80-1976-11eb-9d62-a0c69e52eeb2.jpg)

**Comment by endrift** [comment] 2020-10-29 02:47
Duplicate of #1711. It's going to be fixed in the upcoming 0.9, which will release at...some point in the future. It won't be fixed in 0.8.4, but you can work around it using an official BIOS.

**Closed by endrift** 2020-10-29 02:47 UTC
