### ISSUE TITLE
Dialogue boxes have broken graphics in Spyro - Season of Ice (USA) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [mgba-emu/mgba#1963] opened 2020-12-03 11:30 UTC
![Capture2](https://user-images.githubusercontent.com/68873449/101012552-1c98df00-35b7-11eb-8421-94094f6d5e12.PNG)

**Comment by endrift** [comment] 2020-12-03 20:27
Duplicate of #1486.

**Closed by endrift** 2020-12-03 20:27 UTC
