### ISSUE TITLE
mGBA 0.10.3 for Wii Crashes on Startup

### ISSUE THREAD

**Issue by crazyjat** [mgba-emu/mgba#3162] opened 2024-03-10 07:39 UTC
I have no logs and no way to help, but the Wii version of mGBA simply doesn't work on Wii. 

I have it installed to my USB HDD in apps.

**Comment by endrift** [comment] 2024-03-10 07:41
This has already been fixed in dev. Please use a dev build until 0.10.4 comes out. https://mgba.io/downloads.html#development-downloads

Duplicate of #3106

**Closed by endrift** 2024-03-10 07:41 UTC
