### ISSUE TITLE
mgba doesn't open at all for me 

### ISSUE THREAD

**Issue by Blazyboi** [mgba-emu/mgba#3253] opened 2024-07-11 02:43 UTC
so i'm using mbga 0.10.3, which should work for mac but for whatever reason it won't even pop up, anytime i try to open it my mac just tell me that "mgba quit unexpectedly". So i got no idea what is happening and i hope one of you do. Oh and i am running OS Big Sur, maybe its cause i need to update but if not do tell.

**Comment by endrift** [comment] 2024-07-11 02:57
Duplicate of #3159. If you're on Big Sur though, you should use the "Modern macOS" build instead of the legacy build.

Unless you are using the Modern macOS one? If so that's a different bug.

**Comment by Blazyboi** [comment] 2024-07-11 03:49
i am so i don't know what thats about, might have put down the wrong one.

**Comment by endrift** [comment] 2024-07-11 03:51
Can you post the big log that appears when you click for more details?

**Comment by Blazyboi** [comment] 2024-07-11 03:54
there is a lot so one sec

**Comment by Blazyboi** [comment] 2024-07-11 04:00
<img width="878" alt="Screen Shot 2024-07-10 at 8 53 34 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/cd54ea48-f2c9-4096-b8dc-03886148e55c">
<img width="873" alt="Screen Shot 2024-07-10 at 8 53 47 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/09ac679b-1d49-4161-8663-af43e1eb2f26">
<img width="879" alt="Screen Shot 2024-07-10 at 8 54 00 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/172314e1-9ccc-4408-b356-ab0518702ef0">
<img width="882" alt="Screen Shot 2024-07-10 at 8 54 27 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/ea367fec-0cb0-49f1-8fa2-60b42255f32e">
<img width="874" alt="Screen Shot 2024-07-10 at 8 54 55 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/10482300-4c4d-4dfc-bbb7-690e4fd3be99">
<img width="879" alt="Screen Shot 2024-07-10 at 8 55 16 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/ba8cabea-d986-4387-89db-4daf33d1e8ef">
<img width="878" alt="Screen Shot 2024-07-10 at 8 55 38 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/869bc221-d8b8-40b6-9466-27a2897902bf">
<img width="875" alt="Screen Shot 2024-07-10 at 8 55 46 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/7edbca40-fdf9-4365-86d2-fa67eda63ba3">
<img width="877" alt="Screen Shot 2024-07-10 at 8 55 56 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/18fca249-c98f-400a-b7d2-b0ca9458a6b3">
<img width="876" alt="Screen Shot 2024-07-10 at 8 56 08 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/301ddbdc-4d22-4021-a955-041c7536fa64">
<img width="881" alt="Screen Shot 2024-07-10 at 8 56 17 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/492edbfd-c068-45a1-89bf-2a2c27cab1dd">
<img width="877" alt="Screen Shot 2024-07-10 at 8 56 25 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/13075c5e-4f40-4e25-831c-789254b6dc5d">
<img width="877" alt="Screen Shot 2024-07-10 at 8 56 33 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/21e96cb7-0f82-4a19-99d1-678d155a2b2a">
<img width="880" alt="Screen Shot 2024-07-10 at 8 56 41 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/bfe3fa68-34a1-4bed-a602-c5583ec70566">
<img width="876" alt="Screen Shot 2024-07-10 at 8 56 49 PM" src="https://github.com/mgba-emu/mgba/assets/175274672/25c037ff-5880-4aae-977e-2af2dfb76a89">
![Uploading Screen Shot 2024-07-10 at 8.56.59 PM.png…]()

**Comment by Blazyboi** [comment] 2024-07-11 04:00
might have missed a few bars of code cause of how long it was but thats about it

**Comment by endrift** [comment] 2024-07-11 04:01
This has all of what I'm interested in, thanks. It is indeed a different bug.

**Comment by endrift** [comment] 2024-09-19 11:18
Can you see if this works in a recent dev build? I rebuilt all of the libraries that get linked in, which fixed the other bug. Maybe this one will be fixed too?

**Comment by endrift** [comment] 2024-10-31 09:36
Tentatively closing this. Let me know if it's not fixed and I'll reopen this.

**Closed by endrift** 2024-10-31 09:36 UTC
Labels: severity:host crash, system:macOS, blocked:needs retest
