### ISSUE TITLE
The mGBA window isn't visible

### ISSUE THREAD

**Issue by RetroGameReaper** [mgba-emu/mgba#984] opened 2018-02-02 03:16 UTC
Recently mGBA hasn't been visible. If I start a game through Launchbox, I can hear the music, but I can't see anything. Last week I unplugged one my monitors and it was fine. When it did it again I tried unplugging the monitor once more but to no avail. I'd like it if someone could help me fix it.

**Comment by endrift** [comment] 2018-02-03 21:56
Do you know which frontend Launchbox uses? SDL or Qt?

**Comment by endrift** [comment] 2019-09-19 06:08
Does this still reproduce?

**Comment by endrift** [comment] 2020-08-04 08:29
Closing due to lack of reply.

**Closed by endrift** 2020-08-04 08:29 UTC
Labels: category:needs info, category:needs retest
