### ISSUE TITLE
Audio Cracks in the latest Windows Nightly build

### ISSUE THREAD

**Issue by LOuroboros** [mgba-emu/mgba#1052] opened 2018-04-15 01:40 UTC
So, after reading that the latest version of mGBA is supposed to fix some noticeable audio issues, specially with Game Boy games, I decided to give it a go.

The result? I can still hear tons of cracks on Pokémon Polished Crystal and on Pokémon Crystal too.
Here's an example: https://streamable.com/oknzg
_And no, they're not caused by the software I'm using to record the video._

**Comment by orbea** [comment] 2018-04-15 01:48
Sounds like a duplicate of issue https://github.com/mgba-emu/mgba/issues/1052.

**Comment by orbea** [comment] 2018-04-15 01:49
Sounds like a duplicate of issue https://github.com/mgba-emu/mgba/issues/1036.

**Comment by bryc** [comment] 2018-04-15 06:32
Happens in VBA and BGB as well, it's just a quirk of how the sound emulation initializes itself, not an emulation bug or related to @orbea's comment. 

The only way to fix it would be to fade in the audio each time emulation resumes.

**Comment by endrift** [comment] 2018-04-22 00:07
Dupe of #1036.

**Closed by endrift** 2018-04-22 00:07 UTC
