### ISSUE TITLE
wrong version number in osx download 0.8.4

### ISSUE THREAD

**Issue by suschizu** [mgba-emu/mgba#1929] opened 2020-11-04 11:50 UTC
hello!  I just downloaded version 0.8.4 (osx) but the app still shows 0.8.3 as version information 

![Screenshot 2020-11-04 at 12 48 26](https://user-images.githubusercontent.com/16004333/98108476-4d90d180-1e9c-11eb-8589-88370b4a9a8d.png)

**Comment by endrift** [comment] 2020-11-04 18:04
Duplicate of #1923

**Closed** 2020-11-04 18:04 UTC
