### ISSUE TITLE
mGBA 0.8.4 (64 bit) ------> error when executing.

### ISSUE THREAD

**Issue by roioros** [mgba-emu/mgba#1928] opened 2020-11-02 09:38 UTC
Hello!

I have a problem with the latest version (0.8.4), I can't use the 64 bit version because it gives me an error when executing, the 32 bit version works without problems, but using the previous 64 bit version of the mGBA (0.8.3) it also works without any problem.

I am using Windows 7 SP1 64 bit.

I leave here the error that it gives me when executing:

![Untitled](https://user-images.githubusercontent.com/26861500/97852859-11ac0f80-1cd6-11eb-83d7-cef581d07cd3.jpg)

**Comment by endrift** [comment] 2020-11-02 09:41
I've seen a handful of people reporting issues with the 64 bit version. I'll see what I can do.

**Comment by roioros** [comment] 2020-11-02 09:44
Thanks!, I hope you can find what causes this error, anything you need me to try, tell me.

**Comment by endrift** [comment] 2020-11-02 22:36
Did you use the installer or just the 7z archive?

**Comment by roioros** [comment] 2020-11-03 10:05
I tried both and the same happens, it gives an error and does not run.

**Comment by Testsr** [comment] 2020-11-04 07:58
Checking with a Windows 10 64 bit machine and the 64-bit installer, reveal no problems.

**Comment by chaiwat89752** [comment] 2020-11-04 11:36
> Checking with a Windows 10 64 bit machine and the 64-bit installer, reveal no problems.

I have this problem too in Windows 10 64Bit but mGBA 32Bit Installer in Windows 10 64bit is normally work, I think maybe has issue only mGBA 64Bit Installer Version.

**Comment by chaiwat89752** [comment] 2020-11-04 11:36
Please fix it sir.

**Comment by lotharsm** [comment] 2020-11-04 11:43
I can't replicate it on Win 10 64 bit either, neither with the 7z nor with the installer version.

**Comment by chaiwat89752** [comment] 2020-11-04 14:07
"mGBA Development Version" has this problem too

**Comment by roioros** [comment] 2020-11-04 14:25
At least in my case, in Windows 7 SP1 64 bit, the latest version of mGBA (0.8.4 64 bit) does not work (either the 7z or the installer) but the previous version (0.8.3) works perfectly using the 64 bit version.

For more info I leave my computer specs:

CPU: AMD Phenom II x4 965
GPU: AMD HD 7970
RAM: 8 GB DDR3

**Comment by epman100** [comment] 2020-11-12 10:08
same here.  mGBA 0.8.4 win64 crashes on Win7 x64.  it does not crash on Win10 x64 but closes immediately and never runs.

so the mGBA 0.8.4 win64 version is definitely buggy.  mGBA 0.8.4 win32 version on the other hand, works fine on both win7 & win10

**Comment by roioros** [comment] 2020-11-12 20:36
No, sorry, I only have a computer with a Windows 7 (SP1, 64 bit).

**Comment by epman100** [comment] 2020-11-13 17:00
> 
> 
> No, sorry, I only have a computer with a Windows 7 (SP1, 64 bit).

ok.  can you run either Msinfo32.exe or Dxdiag.exe in Win7?  mention either the video card or graphics hardware.
it seems that mGBA 0.8.4 win64 fails to run or crash on certain combinations of CPU + onboard graphics hardware

I had been scratching my head on this one for a few days because I recently ran mGBA 0.8.4 win64 on my brother's Sony laptop with Win7 x64 and it did **NOT** crash (like why did mGBA 0.8.4 ran without problem on there but not on another Win7 x64 machine where it DID crash?)  the Sony laptop had an Intel Core i3-380M CPU with Intel HD Graphics (probably 1st gen Intel core hardware).  AND on two other computers (a Toshiba Satellite 2013 laptop with AMD A6-5200m APU w/ AMD Radeon HD 8400 graphics & my family's Dell Inspiron 620 desktop PC using an Intel Core i5-2500 CPU + Intel HD Graphics 2000), mGBA 0.8.4 64bit ran fine without any problems.

the other Win7 PC was a laptop that had onboard mobile intel 965 express chipset family graphics - mgba 0.8.4 crashed on there.  also did **not** work on my HP desktop computer using AMD Phenom II X4 B97 CPU + onboard nVidia Geforce 6150se graphics - mgba.exe 0.8.4 win64 runs but immediately closes - OS was Win10 v1809 LTSC 2019.  and mgba.exe 0.8.4 win64 also failed to run on another PC with AMD Phenom II X4 925 CPU + onboard ATI Radeon 3000 graphics - OS there was Win10 Pro 20H2.  AND another laptop (an old Dell Inspiron 640m 2007 laptop using mobile intel 945 express chipset family graphics + Intel Core 2 Duo mobile T7600), mgba 64bit 0.8.4 fails to run on there and the OS there was also Win10 v1809 LTSC 2019.

again, mgba 0.8.4 win64 (both portable 7z & installable editions) does NOT like certain old CPU + onboard graphics hardware combos

**Comment by endrift** [comment] 2020-11-13 19:59
Oh, this is probably due to me enabling SSE4.1 on the 64 bit version. I haven't double checked yet but those older CPUs may not support it.

**Comment by roioros** [comment] 2020-11-14 02:49
Exactly!, so that is the problem, my micro (Phenom II x4 965) does not have SSE4.1 instructions.

It only have these instructions:

MMX, 3DNow!, SSE, SSE2, SSE3, SSE4A.

If it's not a hassle, could you make a 64 bit version without that instruction?

Thank you!

**Comment by endrift** [comment] 2020-11-14 09:07
Can you let me know if this build works? I disabled SSE4.1 and SSSE3 in it. [mGBA-0.8.4-win64-qt.zip](https://github.com/mgba-emu/mgba/files/5540410/mGBA-0.8.4-win64-qt.zip)

It's worth noting that I added those with the foreknowledge that this would happen, but I was hoping I could just guide people to using the 32-bit version if you had an older 64-bit CPU (everything made in the past 10+ years supports both of those). But I'm not sure how much of a gain or a loss it is, either.

**Comment by profi200** [comment] 2020-11-14 11:09
To be honest. The 64 bit build probably has no advantage for emulation. Video encoding may benefit from the improved instruction set and wider regs as you said.

**Comment by lotharsm** [comment] 2020-11-14 11:11
It might have no real advantage in the first place, that's right - except that 32bit applications are fading away and 64bit applications are just _way_ more future-proof.

**Comment by roioros** [comment] 2020-11-14 13:16
> 
> 
> Can you let me know if this build works? I disabled SSE4.1 and SSSE3 in it. [mGBA-0.8.4-win64-qt.zip](https://github.com/mgba-emu/mgba/files/5540410/mGBA-0.8.4-win64-qt.zip)
> 
> It's worth noting that I added those with the foreknowledge that this would happen, but I was hoping I could just guide people to using the 32-bit version if you had an older 64-bit CPU (everything made in the past 10+ years supports both of those). Since it seems to be difficult to detect short of just crashing, it may be more difficult than expected. But I'm not sure how much of a gain or a loss it is, either. At least until you try and do video encoding...

Great, thank you very much!!, now with that version you have uploaded it works perfectly.

Thanks!

**Comment by chaiwat89752** [comment] 2020-11-14 15:23
> Can you let me know if this build works? I disabled SSE4.1 and SSSE3 in it. [mGBA-0.8.4-win64-qt.zip](https://github.com/mgba-emu/mgba/files/5540410/mGBA-0.8.4-win64-qt.zip)
> 
> It's worth noting that I added those with the foreknowledge that this would happen, but I was hoping I could just guide people to using the 32-bit version if you had an older 64-bit CPU (everything made in the past 10+ years supports both of those). Since it seems to be difficult to detect short of just crashing, it may be more difficult than expected. But I'm not sure how much of a gain or a loss it is, either. At least until you try and do video encoding...

It's Work Now. Thank you.

**Comment by endrift** [comment] 2020-11-15 00:37
> To be honest. The 64 bit build probably has no advantage for emulation. Video encoding may benefit from the improved instruction set and wider regs as you said.

That's exactly why I would guide people to the 32 bit build if your 64 bit CPU were too old. You wouldn't get the benefit. And Windows will probably not remove 32-bit apps any time soon. But again, I'm not sure how to approach the actual _guiding_, so for now I should just revert that addition.

**Comment by chaiwat89752** [comment] 2020-11-15 08:17
Understood, Please make for accurate & performance in the future, I think you have great job for the future CPU incoming,

**Comment by branchus** [comment] 2020-11-18 09:59
> Can you let me know if this build works? I disabled SSE4.1 and SSSE3 in it. [mGBA-0.8.4-win64-qt.zip](https://github.com/mgba-emu/mgba/files/5540410/mGBA-0.8.4-win64-qt.zip)
> 
> It's worth noting that I added those with the foreknowledge that this would happen, but I was hoping I could just guide people to using the 32-bit version if you had an older 64-bit CPU (everything made in the past 10+ years supports both of those). Since it seems to be difficult to detect short of just crashing, it may be more difficult than expected. But I'm not sure how much of a gain or a loss it is, either. At least until you try and do video encoding...

I would prefer to have an optimized 64bit version, such as enable avx2 too

**Comment by epman100** [comment] 2020-11-20 12:54
> 
> 
> Can you let me know if this build works? I disabled SSE4.1 and SSSE3 in it. [mGBA-0.8.4-win64-qt.zip](https://github.com/mgba-emu/mgba/files/5540410/mGBA-0.8.4-win64-qt.zip)
> 
> It's worth noting that I added those with the foreknowledge that this would happen, but I was hoping I could just guide people to using the 32-bit version if you had an older 64-bit CPU (everything made in the past 10+ years supports both of those). Since it seems to be difficult to detect short of just crashing, it may be more difficult than expected. But I'm not sure how much of a gain or a loss it is, either. At least until you try and do video encoding...

perhaps you should mention this on the [main mGBA downloads page](https://mgba.io/downloads.html) (or even make the mGBA-0.8.4-win64-qt version available on there)

but anyways, thanks for releasing this specific version that works on older 64bit CPUs

**Comment by endrift** [comment] 2020-11-22 19:34
I'm going to post this version on the main downloads page at some point, yeah. Been busy with other things for a bit though.

**Comment by CookiePLMonster** [comment] 2021-01-07 19:08
FYI with Page Heap enabled I find it quite easy to crash mGBA 0.8.4 as soon as the ROM is loaded, and I can't reproduce this issue on the latest dev version - it's possible that 0.8.4 had some (now resolved) memory corruption which resulted in this randomness.

**Comment by endrift** [comment] 2021-01-07 19:32
That would be unrelated to this issue, which prevents mGBA from even opening in the first place on older CPUs

**Comment by endrift** [comment] 2021-04-27 01:27
This was addressed in 0.9.0 (via https://github.com/mgba-emu/dependencies/commit/e0db10bac1d70c2c88bc82a9819d37792c145db8).

**Closed by endrift** 2021-04-27 01:27 UTC
Labels: severity:host crash, severity:regression, system:Windows
