### ISSUE TITLE
games start and screen goes black with launchbox

### ISSUE THREAD

**Issue by dml360** [mgba-emu/mgba#2822] opened 2023-02-11 12:20 UTC
I use the launchbox to standardize and start the games, but in mgba the GBA games started to give a black screen (but the audio works) but in gameboy and gameboy color games this problem does not happen, but if you start the gba game directly through emulator without sweating launchbox it runs normally, I went back to version 0.9.3 and then the GBA games work normally again through launchbox

**Comment by endrift** [comment] 2023-02-11 19:52
Duplicate of #2781.

**Closed by endrift** 2023-02-11 19:52 UTC
