### ISSUE TITLE
Multiplayer between two different save files

### ISSUE THREAD

**Issue by RunisDauphin** [mgba-emu/mgba#1375] opened 2019-04-08 09:22 UTC
Hi, I am Runis Dauphin from Rebelles Unis:

I have a question: How do I play with my save file against another person who has his/her save file?

In several games (such as Pokémon saga and Megaman Battle Network RPGs) exists the posibility to combat one person with another one, each of them with their own cartridges and progress. That is what I try to replicate.

Thanks in advance for your awesome work.

**Comment by endrift** [comment] 2019-04-12 23:25
Dupe of #106

**Closed by endrift** 2019-04-12 23:25 UTC
