### ISSUE TITLE
[Feature Request] Having an option to make the screen smaller in Full-Screen

### ISSUE THREAD

**Issue by xZabuzax** [mgba-emu/mgba#1641] opened 2020-01-23 22:23 UTC
**VisualBoyAdvance-M** has that feature implemented, it's called "Maximum Magnification", it basically allows you to change the "Screen" size of your game while playing it in "Full-Screen".

That's a pretty good feature for GB, GBC & GBA emulators IMHO because it allows you to play games of those handled devices with a smaller screen in your PC, playing it with a smaller screen in your PC "recreates" that same feeling as using the handled device.

Personally I like to change the screen size to 2x while having the emulator in Full-Screen exactly the way **VisualBoyAdvance-M** does it.

Keep up the good work, this emulator is shaping up to be a force to be reckoned with.

**Comment by endrift** [comment] 2020-01-23 22:24
Duplicate of #1493

**Closed by endrift** 2020-01-23 22:24 UTC
