### ISSUE TITLE
Exception When i try to open in homebrew launcher 

### ISSUE THREAD

**Issue by willshadows6628** [mgba-emu/mgba#888] opened 2017-09-26 11:45 UTC
![22014819_1234507353349107_1856102074_n](https://user-images.githubusercontent.com/32298352/30858684-10a2f250-a297-11e7-90ca-150d0e7d659a.jpg)
![22047203_1234507350015774_1511857298_o](https://user-images.githubusercontent.com/32298352/30858685-10af3d6c-a297-11e7-95f8-4f0ea409b29c.jpg)

**Comment by endrift** [comment] 2017-09-26 16:13
Development build or stable release?

**Comment by willshadows6628** [comment] 2017-09-26 17:03
Stable Release. I've tried in some versions and the same has occurred in all,including in 0.6.0

**Comment by endrift** [comment] 2017-09-26 17:50
Can't reproduce. Must have something to do with the files you have in the root of your SD card. Can you give me a list?

**Comment by willshadows6628** [comment] 2017-09-26 19:36
![capturar](https://user-images.githubusercontent.com/32298352/30880361-bab2dab2-a2d8-11e7-8bb2-b494e562f502.PNG)
Thats is all i have in the root

**Comment by endrift** [comment] 2021-03-31 07:08
Does this still happen with modern versions?

**Comment by endrift** [comment] 2021-06-20 07:35
Closing due to lack of reply; assuming fixed.

**Closed by endrift** 2021-06-20 07:35 UTC
Labels: blocked:needs retest, severity:host crash, system:3DS
