### ISSUE TITLE
Wii build causes black screen after opening

### ISSUE THREAD

**Issue by Miepee** [mgba-emu/mgba#3344] opened 2024-11-17 11:38 UTC
Using the 0.10.3 build there is a black screen that appears immediately after opening it from the HBC.

**Comment by endrift** [comment] 2024-11-17 11:39
Duplicate of #3106. I'm hoping to have 0.10.4 with this fixed very soon. In the meantime you can use a development version.

**Closed by endrift** 2024-11-17 11:39 UTC
