### ISSUE TITLE
[Question/Feature Request] Controlling Multiple Instances?

### ISSUE THREAD

**Issue by bellyrose** [mgba-emu/mgba#2035] opened 2021-01-30 06:28 UTC
I'm wondering if it's possible to control multiple instances of mGBA at once. I've tried doing so using an AutoHotKey script that I got online that is used for the same purpose for another game (World of Warcraft), but modifying it to fit with mGBA causes problems.

**Comment by RetroEdit** [comment] 2024-07-14 21:28
Duplicate of #276

**Closed by RetroEdit** 2024-07-14 21:28 UTC
