### ISSUE TITLE
Wii port - Option to not use SGB in GB games

### ISSUE THREAD

**Issue by SieKensou** [mgba-emu/mgba#1284] opened 2019-01-29 15:44 UTC
Would be possible to add an option to the Wii port to use SGB or not? I would like to use the GB games as if they would be running in the GB and not the SGB (to avoid the problem with the missing sounds that are played by the SNES). 
Thanks and congratulations for this great emulator.

**Comment by endrift** [comment] 2019-02-12 21:58
Dupe of #1205, which you also filed.

**Closed by endrift** 2019-02-12 21:58 UTC
