### ISSUE TITLE
Some graphics missing while using OpenGL renderer

### ISSUE THREAD

**Issue by awebeer256** [mgba-emu/mgba#2528] opened 2022-05-20 15:14 UTC
When using the OpenGL video renderer, not everything renders. I've only tried *Mario Kart: Super Circuit* so far.

Here's the title screen under software rendering.
![mkss-title-software](https://user-images.githubusercontent.com/26385859/169552723-fa76a5d0-6e48-4c89-9186-ef1274e94edf.png)
And here it is with OpenGL. The menu is missing.
![mkss-title-opengl](https://user-images.githubusercontent.com/26385859/169552816-5297fe0a-ba0d-4334-b7fa-d571dd5480ab.png)
(Both images were blown up to 2x size after being captured)

And here's what happens at the beginning of each race in a Grand Prix with OpenGL.
![mkss-trackoverview-opengl](https://user-images.githubusercontent.com/26385859/169556882-aec79652-9d97-41f9-84a9-279b0130c96c.gif)

mGBA version: local build, master branch, commit 87738ba (the latest as of this writing).
<details><summary>cmake output</summary>
<p>

```
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module SQLite3|sqlite3 missing for feature USE_SQLITE3.  Feature
  disabled.
Call Stack (most recent call first):
  CMakeLists.txt:484 (find_feature)


-- Build type: Release
-- Platforms:
--      Game Boy Advance: ON
--      Game Boy: ON
-- Features:
--      Debuggers: ON
--      CLI debugger: ON
--      GDB stub: ON
--      GIF/Video recording: ON
--      Screenshot/advanced savestate support: ON
--      ZIP support: libzip
--      7-Zip support: ON
--      SQLite3 game database: ON
--      ELF loading support: ON
--      Discord Rich Presence support: ON
--      OpenGL support: libepoxy
-- Frontends:
--      Qt: ON
--      SDL (2): ON
--      Python bindings: OFF
--      Examples: OFF
-- Test tools:
--      Profiling: OFF
--      Test harness: OFF
--      Test suite: OFF
--      Video test suite: OFF
--      ROM tester: OFF
-- Cores:
--      Libretro core: OFF
-- Libraries:
--      Static: OFF
--      Shared: ON
-- Configuring done
-- Generating done
```

</p>
</details>

System: Fedora 36, x86_64, X11, Nvidia GPU with proprietary driver

**Comment by endrift** [comment] 2022-05-20 21:53
Seems to work for me on 515. What driver version and GPU do you have?

**Comment by awebeer256** [comment] 2022-05-20 22:51
Driver: 510.68.02
GPU: GeForce GTX 1660 SUPER

**Comment by endrift** [comment] 2022-05-20 23:10
Can you see if it happens on 515? I can try downgrading to 510.

**Comment by endrift** [comment] 2022-05-21 20:41
Duplicate of #2500 -- please update that bug report if it's fixed in 515.

**Closed by endrift** 2022-05-21 20:41 UTC

**Comment by awebeer256** [comment] 2022-05-21 21:21
515 isn't in the Fedora repos yet.

**Comment by endrift** [comment] 2022-05-21 21:23
I see. Can you install RenderDoc and grab a capture of one of the faulty frames? RenderDoc might be a bit difficult to figure out, but being unable to reproduce it myself I'm unsure where to go with this.

**Comment by awebeer256** [comment] 2022-05-21 22:44
Okay, so it turns out that when I *lock my session,* the Nvidia driver breaks until I reboot 😤. If I run mGBA immediately after booting, it works.

I've never used RenderDoc before, but even I could see some big problems with a faulty frame:
![Screenshot_20220521_175424](https://user-images.githubusercontent.com/26385859/169671261-be35ed63-f9eb-4052-8167-63cef4236a09.png)


Do you still want a full capture? (And do you know how to fix the Nvidia problem?)

**Comment by endrift** [comment] 2022-05-21 23:13
This isn't the right part of the trace. Capture a single frame and it'll have the actual draw steps, which this isn't.

And no, I don't have an Nvidia GPU in my desktop anymore.

**Comment by awebeer256** [comment] 2022-05-21 23:23
Here.
[faulty-mk.zip](https://github.com/mgba-emu/mgba/files/8748500/faulty-mk.zip)

**Comment by endrift** [comment] 2022-05-22 00:06
Got it, thanks. That contained the info I needed to solve this.
