### ISSUE TITLE
Sigma Star Saga visual glitch

### ISSUE THREAD

**Issue by ShlomiToren** [mgba-emu/mgba#2051] opened 2021-02-23 08:46 UTC
Hey, I'm playing Sigma Star Saga (USA, Europe) on the standalone version. Here's the version:
![image](https://user-images.githubusercontent.com/68924889/108819200-3862be80-75c3-11eb-974c-5bde89afab49.png)

I'm noticing some weird visual bugs. Seem to last 1frame, but I have no idea. Sometimes it looks like a black screen, other times you can notice garbled pixels. Here's a video I captured:
https://drive.google.com/file/d/1dnBxWsh_l1xSInIy8lIXJhpWS_amWKdM/view

You can see the black frames at around 0:14, and the garbled pixels at around 1:15.

Not sure if it matters, but this also happens in the RA core. I also tried VBA 1.8.0 beta 3 and it doesn't seem to happen there, so I don't think the ROM is the issue, but I can upload it as well.

Let me know if I can supply anything else. Thanks!

**Comment by endrift** [comment] 2021-03-23 04:33
I am unable to reproduce on latest development build. Please retest to see if you can still reproduce it on it.

**Comment by endrift** [comment] 2021-04-02 04:35
Closing due to lack of reply. Please respond if you have more info and I can reopen it.

**Closed by endrift** 2021-04-02 04:35 UTC
Labels: blocked:needs retest, hardware:2D, platform:GBA
