### ISSUE TITLE
Screen freeze when loading save state menu on MacOS

### ISSUE THREAD

**Issue by Eraguzy** [mgba-emu/mgba#3145] opened 2024-02-19 09:53 UTC
[Bug report zip file](https://github.com/mgba-emu/mgba/files/14329252/macosbug.zip)
Whenever i go in the saves state menu (maj+F10), when i go back from this menu into the game itself, the gamescreen will freeze (not the whole game, only the screen, you can still hear the right sounds when there are inputs), no matter the number of save states there are and the way you leave this menu (by loading a save state or just cancelling).
I use the latest version of mgba on brew (still 0.10.2).
<img width="967" alt="captureterm" src="https://github.com/mgba-emu/mgba/assets/122539649/9e6ddf2f-5fec-42ad-bad3-4f9c29bb157a">

**Comment by endrift** [comment] 2024-02-19 10:06
Probably a duplicate of #2885

**Closed** 2024-02-19 10:06 UTC
Labels: category:questionable, system:macOS, blocked:needs retest
