### ISSUE TITLE
multiplayer windows sped up

### ISSUE THREAD

**Issue by Codiiboii** [mgba-emu/mgba#3096] opened 2023-12-29 22:05 UTC
[bugrp29.12.23mksc.zip](https://github.com/mgba-emu/mgba/files/13796244/bugrp29.12.23mksc.zip)

when playing with multiplayer windows, opening the multi pak mode on one of them speeds up the other 4 windows A LOT, but the one on the multi pak menu stays at a normal speed

https://github.com/mgba-emu/mgba/assets/91764892/3068c1de-7861-472a-9195-68d38533f979

i have just found that it also only makes everything else speed up when the first window is on the multi pak menu

gameplay is fine

thank youu :)

**Comment by endrift** [comment] 2023-12-30 00:51
Duplicate of #2974. It's been fixed but the fix hasn't made it into a release yet.

**Closed by endrift** 2023-12-30 00:51 UTC
