### ISSUE TITLE
Changing frame size is broken

### ISSUE THREAD

**Issue by sigarettenstank** [mgba-emu/mgba#2999] opened 2023-08-13 09:12 UTC
Using the latest development build. Whatever I choose automatically sets the frame size to 1 and can't be changed back.

![Capture](https://github.com/mgba-emu/mgba/assets/95235094/c490f1d8-9f77-4da8-8463-672d5588cb87)

**Comment by endrift** [comment] 2023-08-14 01:37
Duplicate of #2973

**Closed by endrift** 2023-08-14 01:37 UTC
