### ISSUE TITLE
[3DS] Sonic Advance 3 Extra Zone softlocked

### ISSUE THREAD

**Issue by TwystedXYZ** [mgba-emu/mgba#2977] opened 2023-07-13 22:36 UTC
Release: Latest, stable.
System: New Nintendo 2DS XL
Game: Sonic Advance 3 (USA)
Desc.:
During the Final Zone, Nonaggression, Eggman refuses to charge the energy fully, remaining stuck at a specific frame of his attack. I tried both with and without cheat codes, still nothing. Endrift, I gave you the save file on Discord.

**Comment by endrift** [comment] 2023-07-16 21:58
[Sonic_Advance_3.zip](https://github.com/mgba-emu/mgba/files/12065196/Sonic_Advance_3.zip)

Uploading the save game/states here so I don't lose track of them.

**Comment by ChanseyIsTheBest** [comment] 2023-08-11 05:04
This probably isn't it but I would double check the ROM you are using. Sonic Advance 3 has an infamously buggy prototype that has some issues the final game doesn't have and this may be one of them.

**Comment by endrift** [comment] 2023-11-18 10:24
I've confirmed how the Nonaggression boss is supposed to work on hardware, using this save file. I had to pull out my GameShark just so I had enough lives to not have to redo all of navigation to get to the Final Zone after dying over and over...I don't think I like this game.

Anyway, now that I've finally gotten around to seeing how it works on hardware I can try comparing to see what goes wrong in emulator.

**Comment by endrift** [comment] 2023-12-12 07:25
I'm unable to reproduce this on PC from the save. @TwystedXYZ, can you reproduce on PC or only on 3DS?

**Comment by endrift** [comment] 2024-01-30 05:47
Closing due to lack of a reply.

**Closed by endrift** 2024-01-30 05:47 UTC
Labels: blocked:needs retest
