### ISSUE TITLE
Minish cap lag and sound glitches

### ISSUE THREAD

**Issue by nephitejnf** [mgba-emu/mgba#1585] opened 2019-11-26 22:19 UTC
There are weird noise and game lag in Minish cap, it may correlate with issues people have mentioned in other games. I initially found this in version 0.8-597-6900d130, Big Octo no longer completely freezes the game, but that issue happened during the opening cutscene of the boss fight, but it is more prominent an issue during the figurine house sequence. Not sure what it is, though it might be when the game is running RNG routines, but I'm still not sure. It still happens in the current version, too.

https://www.twitch.tv/videos/513716961

**Comment by endrift** [comment] 2019-12-02 21:17
Can you provide a save file in the figurine house so I can easily test the gashapon? Most saves floating around have them all collected already.

**Comment by nephitejnf** [comment] 2019-12-03 04:37
https://drive.google.com/open?id=19uhuyf2fLw6MeqmFFQx7kBTKVvXeKErm

This is from right after the stream I linked. Saved in Hyrule.

**Comment by endrift** [comment] 2019-12-03 19:24
Odd, it works fine on my end. I may need more information about your setup.

**Comment by nephitejnf** [comment] 2019-12-04 19:45
ROG Strix GL503V
Include and integrated intel graphics with Nvidia GTX 1050 discrete graphics card
16 gigs of ram and Intel i7
running Arch linux

**Comment by endrift** [comment] 2019-12-04 21:04
Do you know if this is running on the iGPU or the dGPU? I'm also on Arch with Intel graphics, but I can try Nvidia graphics.

**Comment by RetroEdit** [comment] 2024-10-06 07:36
I'm going to close it because it's almost five years old and it's a very specific issue that couldn't be reproduced at the time.

If it's still happening and more info can be provided, then this can be reopened. We even know a lot more about Minish Cap nowadays!

**Closed by RetroEdit** 2024-10-06 07:36 UTC
Labels: blocked:needs info
