### ISSUE TITLE
MGBA unacurate audio

### ISSUE THREAD

**Issue by Gamulation** [mgba-emu/mgba#2121] opened 2021-04-12 18:45 UTC
Hi
I am loading a pokémon game, and the GBA boot sound is slightly modifyed, it's like it get's destorted in the higher pitch frequencies. This is aspesually enoying in the Pokémon games, where the text sound is outright unbarable to listen to. This is the only emulator I have found that have this problem. It would be verry nice to have this fixed, as I am now using a different emulator for this reason.
I am testing this on the latest release, 0.9.0 and I'm running Windows 10 X64. My CPU is Intel core I 5-9300H and an nvidia GTX 1650

**Comment by endrift** [comment] 2021-04-12 19:01
Duplicate of #2117.

**Closed by endrift** 2021-04-12 19:01 UTC
