### ISSUE TITLE
Final Fantasy 6 Advance: Sound broken from the very beginning

### ISSUE THREAD

**Issue by tomtung** [mgba-emu/mgba#1171] opened 2018-09-15 06:34 UTC
The sound is broken right after the starting chord played by organ.

**Comment by endrift** [comment] 2018-09-15 21:32
Which platform and version are you using? I can't reproduce. I notice some slight audio distortion but that might just be my audio drivers. Can you be more specific about how it's broken?

**Comment by endrift** [comment] 2018-09-15 23:26
Can you turn on the FPS display to make sure it's running at full speed? It's not always full speed on N3DS.

**Comment by tomtung** [comment] 2018-09-15 23:30
It was 59.75 fps when the sound started cracking, right when the title screen showed up.

**Comment by tomtung** [comment] 2018-09-15 23:33
btw I also tried virtual console injection, and the sound worked fine there.

**Comment by endrift** [comment] 2020-08-17 02:07
Does this still happen for you?

**Comment by Testsr** [comment] 2020-12-02 06:56
@tomtung, can you retest with the latest development version?

**Comment by endrift** [comment] 2020-12-02 21:57
There hasn't been a reply in nearly 4 months, I'm just closing this unless it's confirmed it still is a problem.

**Closed by endrift** 2020-12-02 21:57 UTC
Labels: blocked:needs info, blocked:needs retest, hardware:audio, platform:GBA, system:3DS
