### ISSUE TITLE
Gyroscope is inverted on Wii

### ISSUE THREAD

**Issue by nicotilt** [mgba-emu/mgba#2318] opened 2021-09-28 06:46 UTC
I was happy to see that mGBA had gyro support for Wario Ware Twisted for Wii homebrew. When I tried it out, however, it seemed as though the gyro controls were mirrored. When I tilt left, I go right vice versa. To check if I was doing something wrong, I used vbaGX and while the tilt controls were lower quality, they were oriented correctly. Is there any way to fix this problem?

**Comment by endrift** [comment] 2021-09-28 07:00
Duplicate of #2245; please search in the future.

**Closed by endrift** 2021-09-28 07:00 UTC
