### ISSUE TITLE
"Oh!" demo softlocks mGBA

### ISSUE THREAD

**Issue by fishcu** [mgba-emu/mgba#2676] opened 2022-10-09 15:48 UTC
This demoscene demo softlocks mGBA after a short amount of time: https://www.pouet.net/prod.php?which=54175

The music keeps playing, but the graphics appear frozen. Fast-forwarding shows that the emulation never progresses beyond the broken screen.

How to replicate: Open oh.gb. Let it run. After the second screen transition, the demo will not progress.

Environment: mGBA 0.9.3 release, Windows 10. GTX 1060 laptop version. Latest nvidia drivers.

**Comment by endrift** [comment] 2022-10-09 21:02
Duplicate of #250

**Closed by endrift** 2022-10-09 21:02 UTC
