### ISSUE TITLE
Button for shortcuts has to be pressed twice when using gamepad

### ISSUE THREAD

**Issue by Intiroso** [mgba-emu/mgba#2143] opened 2021-04-25 12:50 UTC
Hello, i download previous versions until 0.7.2 for testing, and since 0.8.1 any button (even axis) assigned to shortcuts  has to be pressed two times to work, every time you want to use that action.
Maybe because the solution used for #1650?

Also wanna congrats for the great GBA emulator that mGBA is (and becoming even more too).

**Comment by endrift** [comment] 2021-04-25 18:48
What gamepad are you using? I use gamepads and have never seen this issue.

**Comment by Intiroso** [comment] 2021-04-25 20:08
I forgot to put those details. 
Already tried with three diferents gamepads: wireless Xbox 360, Logitech Cordless Rumblepad 2 and a Gamecube controller using a Mayflash adapter. I use 4 shortcuts, Load and Save State, Fast forward held (this works as intended) and Toggle fullscreen.

My OS is Windows 7 64bits (tried both versións of the emu, 32b and 64b)

Another thing, every time you open the emulator its trigger any of the shortcuts with just one press, after that "first" action, it will work only with 2 presses (for each shortcut that has used the "first" press). This happens every time you close and reopen the program.
Also doesn't matter the moment  of the second push to trigger the shortcut, could be immediately or several seconds latetly, even if you use other buttons between those principal actions, the shortcut always activates the moment that you press the desingned button for a 2nd time.

**Comment by endrift** [comment] 2021-04-25 20:10
Alright, I'll see if I can reproduce. If so I'll schedule this for 0.9.2.

**Comment by Intiroso** [comment] 2021-04-25 20:12
Thank you very much

**Comment by Hexaae** [comment] 2021-04-27 18:50
Can't reproduce here with Win 10 and mGBA 0.9.1. I assigned ffwd to right-stick of XBox One Bluetooth and always works fine on first press (and next presses).

**Comment by Hexaae** [comment] 2021-05-02 14:45
Ok, tested Toggle Fullscreen assigned to RSTICK press and indeed requires 2 presses to work after first press...

**Closed** 2021-06-13 04:41 UTC
Labels: port:Qt

**Comment by endrift** [comment] 2021-06-13 04:56
Sorry for losing track of this; I'd meant to look into and fix this months ago, but it slipped through the cracks until someone else reported it. I did look through the code at some point to see how it could happen though so I did get a head-start on figuring it out.
