### ISSUE TITLE
0.8.4 Pokemon games do not have stat change animations with OpenGL

### ISSUE THREAD

**Issue by i-liek-katz** [mgba-emu/mgba#1975] opened 2020-12-10 04:33 UTC
0.8.3 OpenGL has stat changes animated (colored upward/downward waves moving up or down) but 0.8.4 does not have them animated when using OpenGL. Using "OpenGL (force version 1.x)" fixes the issue while using 0.8.4 but obviously you're then using "OpenGL (force version 1.x)". Noticed issue on Pokemon Unbound v1.0.1 rom hack, and also tested on Pokemon Fire Red v1.0 and experienced the same issue.

**Comment by endrift** [comment] 2020-12-10 04:35
"Force version 1.x" disables the OpenGL enhancement renderer anyway. It doesn't work below version 3.2 or so.

This may be fixed on latest dev, since it's probably an objwin issue, and objwin got overhauled since 0.8.4.

**Comment by endrift** [comment] 2020-12-10 05:30
I can confirm this has been fixed in dev.

**Closed by endrift** 2020-12-10 05:30 UTC
