### ISSUE TITLE
Bugreport. Speedup kills Romhack after latest Update

### ISSUE THREAD

**Issue by Frawsch** [mgba-emu/mgba#2226] opened 2021-06-22 11:38 UTC
Basically since the latest version of mgba (0.9.1) Pokémon Glazed hangs itself whenever I do speedups. Sometimes its just as laggy as displayed and sometimes it also just stops working all together. in the previous version this was NEVER a problem. So I assume it has something to do with the new speedup implementation.
Tested this with VBA too. No problem.

The mgba Build in Report can be found in attachments.

Here a video that shows whats happening: [https://youtu.be/O8Ds2uugnZw] 
[Bugreport.zip](https://github.com/mgba-emu/mgba/files/6693872/Bugreport.zip)

Hope you can help :)

**Comment by TeoTotoro** [comment] 2021-06-22 11:43
Have you disabled sync to video? It's know to cause crashes like these in 0.9.1.

**Comment by endrift** [comment] 2021-06-22 18:19
Duplicate of #2137 (which got deleted, so you'll find more info in #2138). This bug has been fixed for a while, but I haven't managed to get a new release out. It's been reported so many times by now, though, so please search closed bugs next time.

**Closed** 2021-06-22 18:19 UTC

**Comment by Frawsch** [comment] 2021-07-11 11:10
Okay got it and thanks to the two of you :) and yes it was never enabled to begin with
