### ISSUE TITLE
Multiplayer crashes

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#462] opened 2016-11-10 01:28 UTC
Using OpenGL force 1.x, since with Qt I get slow fps in the second window and with GL I get a black screen

versions: 0.4.1, 0.5.1 (last commit)

Sync to audio = OFF

Steps to reproduce:

* Open mGBA, load a game
* Open a new multiplayer window
* Load the other game
* It'll run a while, then crashes

Ubuntu 14.04, kernel 3.13.0-100-generic, Qt 5.2.1, mesa 10.1.3

```
(gdb) run
Starting program: /usr/games/mgba-qt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe1f93700 (LWP 3891)]
[New Thread 0x7fffd67f4700 (LWP 3892)]
[New Thread 0x7fffcffff700 (LWP 3912)]
[New Thread 0x7fffcf7fe700 (LWP 3913)]
[Thread 0x7fffcf7fe700 (LWP 3913) exited]
[New Thread 0x7fffcf7fe700 (LWP 3914)]
[New Thread 0x7fffceffd700 (LWP 3915)]
QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent
QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent
QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent
QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent
[New Thread 0x7fffce7fc700 (LWP 3916)]
[New Thread 0x7fffccffa700 (LWP 3917)]
SDL Audio: Could not open SDL sound system
[New Thread 0x7fffc3ffe700 (LWP 3918)]
QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent
QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent
QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent
QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent
QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent
QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent
QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent
mgba-qt: ../../src/xcb_conn.c:186: write_vec: Assertion `!c->out.queue_len' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffceffd700 (LWP 3915)]
0x00007ffff4f2cc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
(gdb) 
(gdb) bt full
#0  0x00007ffff4f2cc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 3886
        selftid = 3915
#1  0x00007ffff4f30028 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7fffffffe244, sa_sigaction = 0x7fffffffe244}, sa_mask = {__val = {140737304275204, 140737194976768, 186, 4294967295, 
              140737302918483, 0, 140736666256128, 47244640256, 140736666256048, 140737488350561, 0, 0, 0, 21474836480, 140736951513088, 140737304290232}}, sa_flags = -293378539, 
          sa_restorer = 0x7fffee836630 <__PRETTY_FUNCTION__.10950>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff4f25bf6 in __assert_fail_base (fmt=0x7ffff50763b8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fffee836615 "!c->out.queue_len", 
    file=file@entry=0x7fffee836600 "../../src/xcb_conn.c", line=line@entry=186, function=function@entry=0x7fffee836630 <__PRETTY_FUNCTION__.10950> "write_vec") at assert.c:92
        str = 0x7fffb43324a0 ""
        total = 4096
#3  0x00007ffff4f25ca2 in __GI___assert_fail (assertion=assertion@entry=0x7fffee836615 "!c->out.queue_len", file=file@entry=0x7fffee836600 "../../src/xcb_conn.c", 
    line=line@entry=186, function=function@entry=0x7fffee836630 <__PRETTY_FUNCTION__.10950> "write_vec") at assert.c:101
No locals.
#4  0x00007fffee82ae5b in write_vec (count=0x7fffceffc544, vector=0x7fffceffc548, c=0x5555559199c0) at ../../src/xcb_conn.c:186
        n = <optimized out>
#5  _xcb_conn_wait (c=c@entry=0x5555559199c0, cond=cond@entry=0x55555591aae0, vector=vector@entry=0x7fffceffc548, count=count@entry=0x7fffceffc544) at ../../src/xcb_conn.c:490
        may_read = <optimized out>
        ret = 1
        fd = {fd = 3, events = 5, revents = 4}
#6  0x00007fffee82b191 in _xcb_out_send (c=c@entry=0x5555559199c0, vector=vector@entry=0x7fffceffc580, count=count@entry=1) at ../../src/xcb_out.c:367
        ret = 1
#7  0x00007fffee82b8a7 in _xcb_out_flush_to (c=0x5555559199c0, request=30401) at ../../src/xcb_out.c:394
        vec = {iov_base = 0x55555591ab5c, iov_len = 32}
#8  0x00007fffee82b9c8 in xcb_take_socket (c=0x5555559199c0, return_socket=return_socket@entry=0x7ffff42bc000 <return_socket>, closure=closure@entry=0x555555918600, flags=1, 
    sent=sent@entry=0x7fffceffc618) at ../../src/xcb_out.c:293
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "xcb_take_socket"
#9  0x00007ffff42bba38 in require_socket (dpy=0x555555918600) at ../../src/xcb_io.c:68
        sent = 93824998306064
        flags = <optimized out>
#10 0x00007ffff42bc259 in _XFlush (dpy=0x555555918600) at ../../src/xcb_io.c:511
No locals.
#11 0x00007ffff42bec75 in _XGetRequest (dpy=dpy@entry=0x555555918600, type=type@entry=43 '+', len=len@entry=4) at ../../src/XlibInt.c:1735
        req = <optimized out>
#12 0x00007ffff42b80bb in XSync (dpy=dpy@entry=0x555555918600, discard=discard@entry=0) at ../../src/Sync.c:43
        rep = {type = 0 '\000', revertTo = 0 '\000', sequenceNumber = 0, length = 0, focus = 3612453452, pad1 = 32767, pad2 = 3472868944, pad3 = 32767, pad4 = 0, pad5 = 0}
#13 0x00007ffff681975b in dri2XcbSwapBuffers (pdraw=0x555555b13ed0, remainder=<optimized out>, divisor=0, target_msc=0, dpy=0x555555918600) at ../../../../src/glx/dri2_glx.c:817
        swap_buffers_cookie = <optimized out>
        swap_buffers_reply = <optimized out>
        target_msc_lo = 0
        divisor_lo = 0
        remainder_hi = <optimized out>
        remainder_lo = <optimized out>
        ret = 0
        target_msc_hi = 0
        divisor_hi = 0
        c = 0x5555559199c0
#14 dri2SwapBuffers (pdraw=0x555555b13ed0, target_msc=0, divisor=0, remainder=<optimized out>, flush=<optimized out>) at ../../../../src/glx/dri2_glx.c:855
        flags = <optimized out>
        priv = 0x555555b13ed0
        dpyPriv = 0x555555b1eee0
        psc = 0x555555b1f110
        pdp = 0x555555b0b580
        ret = 0
#15 0x00007ffff629ced1 in QOpenGLContext::swapBuffers (this=<optimized out>, surface=<optimized out>) at kernel/qopenglcontext.cpp:866
        __PRETTY_FUNCTION__ = "void QOpenGLContext::swapBuffers(QSurface*)"
        surfaceHandle = 0x555555b0b4b0
#16 0x00005555555b973d in QGBA::PainterGL::draw() ()
No symbol table info available.
#17 0x00007ffff5d7422e in QObject::event (this=0x555555bbce50, e=<optimized out>) at kernel/qobject.cpp:1147
        mce = <optimized out>
        sw = {receiver = 0x555555bbce50, previousSender = 0x0, currentSender = {sender = 0x0, signal = -1, ref = 1}, switched = true}
#18 0x00007ffff6ddbc8c in QApplicationPrivate::notify_helper (this=this@entry=0x55555590abc0, receiver=receiver@entry=0x555555bbce50, e=e@entry=0x5555593263c0)
    at kernel/qapplication.cpp:3486
        consumed = <optimized out>
#19 0x00007ffff6de0e56 in QApplication::notify (this=0x7fffffffdb90, receiver=0x555555bbce50, e=0x5555593263c0) at kernel/qapplication.cpp:3236
        w = 0x555555bbce50
        extra = <optimized out>
        isProxyWidget = <optimized out>
        __PRETTY_FUNCTION__ = "virtual bool QApplication::notify(QObject*, QEvent*)"
        res = <optimized out>
#20 0x00007ffff5d4bc2d in QCoreApplication::notifyInternal (this=0x7fffffffdb90, receiver=0x555555bbce50, event=event@entry=0x5555593263c0) at kernel/qcoreapplication.cpp:881
        threadData = 0x5555576b96e0
        loopLevelCounter = {threadData = 0x5555576b96e0}
        result = false
        cbdata = {0x555555bbce50, 0x5555593263c0, 0x7fffceffcb1f}
        d = <optimized out>
#21 0x00007ffff5d4de07 in sendEvent (event=0x5555593263c0, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:232
No locals.
#22 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x5555576b96e0) at kernel/qcoreapplication.cpp:1485
        e = 0x5555593263c0
        pe = <optimized out>
        r = <optimized out>
        unlocker = {m = <synthetic pointer>}
        event_deleter = {d = 0x5555593263c0}
        __PRETTY_FUNCTION__ = "static void QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)"
        locker = {val = 93825027249928}
        startOffset = 0
        i = @0x5555576b96fc: 1
        cleanup = {receiver = 0x0, event_type = 0, data = 0x5555576b96e0, exceptionCaught = true}
#23 0x00007ffff5d4e433 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1343
        data = <optimized out>
#24 0x00007ffff5d98cd3 in postEventSourceDispatch (s=0x7fffb4001340) at kernel/qeventdispatcher_glib.cpp:279
        source = 0x7fffb4001340
#25 0x00007fffefce2e04 in g_main_dispatch (context=0x7fffb4000990) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3064
        dispatch = 0x7ffff5d98cc0 <postEventSourceDispatch(GSource*, GSourceFunc, gpointer)>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = <optimized out>
        cb_data = 0x0
        need_destroy = <optimized out>
        source = 0x7fffb4001340
        current = 0x7fffd0002570
        i = 0
#26 g_main_context_dispatch (context=context@entry=0x7fffb4000990) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3663
No locals.
#27 0x00007fffefce3048 in g_main_context_iterate (context=context@entry=0x7fffb4000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3734
        max_priority = 2147483647
        timeout = -1
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 1
        fds = 0x7fffb40013e0
#28 0x00007fffefce30ec in g_main_context_iteration (context=0x7fffb4000990, may_block=1) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3795
        retval = <optimized out>
#29 0x00007ffff5d9898c in QEventDispatcherGlib::processEvents (this=0x7fffb40008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:426
        d = 0x7fffb40008e0
        canWait = true
        savedFlags = {i = 0}
        result = <optimized out>
#30 0x00007ffff5d4a96b in QEventLoop::exec (this=this@entry=0x7fffceffcdd0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
        locker = {val = 93825027376032}
        __PRETTY_FUNCTION__ = "int QEventLoop::exec(QEventLoop::ProcessEventsFlags)"
        ref = {d = 0x7fffb4002e70, locker = @0x7fffceffcd50, exceptionCaught = true}
        d = 0x7fffb4002e70
#31 0x00007ffff5b7323a in QThread::exec (this=<optimized out>) at thread/qthread.cpp:509
        d = 0x5555576d8330
        locker = {val = 93825027376032}
        eventLoop = {<QObject> = {_vptr.QObject = 0x7ffff6185530 <vtable for QEventLoop+16>, static staticMetaObject = {d = {superdata = 0x0, 
                stringdata = 0x7ffff5e96cc0 <qt_meta_stringdata_QObject>, data = 0x7ffff5e96ba0 <qt_meta_data_QObject>, 
                static_metacall = 0x7ffff5d7aa90 <QObject::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = {
              d = 0x7fffb4002e70}, static staticQtMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff5ee1060 <qt_meta_stringdata_Qt>, 
                data = 0x7ffff5ede9a0 <qt_meta_data_Qt>, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}}, static staticMetaObject = {d = {
              superdata = 0x7ffff6181f80 <QObject::staticMetaObject>, stringdata = 0x7ffff5ef46a0 <qt_meta_stringdata_QEventLoop>, 
              data = 0x7ffff5ef4640 <qt_meta_data_QEventLoop>, static_metacall = 0x7ffff5ddee70 <QEventLoop::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
              relatedMetaObjects = 0x0, extradata = 0x0}}}
        returnCode = <optimized out>
#32 0x00007ffff5b77233 in QThreadPrivate::start (arg=0x5555576d7960) at thread/qthread_unix.cpp:345
        __clframe = {__cancel_routine = 0x7ffff5b76500 <QThreadPrivate::finish(void*)>, __cancel_arg = 0x5555576d7960, __do_it = 1, __cancel_type = <optimized out>}
        thr = 0x5555576d7960
        data = <optimized out>
        objectName = {static null = {<No data fields>}, d = 0x5555576b9760}
#33 0x00007ffff29d6184 in start_thread (arg=0x7fffceffd700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7fffceffd700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736666261248, 1859259315937032037, 1, 0, 140736666261952, 140736666261248, -1859151564287821979, -1859266165384595611}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#34 0x00007ffff4ff037d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
(gdb) 
```

**Comment by sergiobenrocha2** [comment] 2016-11-10 02:04
I managed to get Qt working somewhat; only OpenGL force 1.x crashes mgba

**Comment by sergiobenrocha2** [comment] 2016-11-12 19:42
Testing on ubuntu 16.10, 0.5 branch
Qt 5.6.1, kernel 4.8.0-22, mesa 12.0.3

Pokemon - Emerald Version (USA, Europe), crc  1F1C08FB
Pokemon - Ruby Version (USA, Europe) (Rev 2), crc  AEAC73E6

I'm getting this with GL and Qt renderer, as soon as I save in both sides to try mix records:

![mgba - ruby and emerald - record mix](https://cloud.githubusercontent.com/assets/5431285/20240326/d6bc926a-a8fc-11e6-8651-965bc898e48a.png)

If I try trade, it takes a while to get this screen.

And I got this with OpenGL force 1.x:

![mgba - ruby and emerald - record mix__2](https://cloud.githubusercontent.com/assets/5431285/20240401/6924e5ac-a8fe-11e6-8694-5f58c40436f5.png)

I managed to mix record I guess, then when I was exiting the room the Ruby window crashed.

**Comment by sergiobenrocha2** [comment] 2016-11-13 16:56
Seems I can trade and mix records properly only with 0.4.1 on new ubuntu releases, such as 16.10 (I need to test 16.04 yet), using Qt renderer. On 14.04 it kinda works, Qt is buggy there and you get a slow fps second window; you need to disable Sync to audio

I forgot to say, I was using the gba bios in the tests.

**Comment by endrift** [comment] 2021-03-14 08:35
I cannot reproduce this in latest dev. I believe this to either be a dri2 (external) bug or to have been fixed with my recent(ish) GL changes. Please retest.

**Comment by endrift** [comment] 2021-04-02 04:34
Closing due to lack of reply. Please respond if you have more info and I can reopen it.

**Closed by endrift** 2021-04-02 04:34 UTC
Labels: blocked:needs retest, port:Qt, severity:host crash
