### ISSUE TITLE
mGBA fails test 7 of cgb sound

### ISSUE THREAD

**Issue by Kurayami7** [mgba-emu/mgba#2104] opened 2021-04-01 20:09 UTC
![Capture](https://user-images.githubusercontent.com/77198254/113348296-24f50100-9382-11eb-8880-23bbe00bf7c2.PNG)

Also tried it in Sameboy which passes. 

![Capture2](https://user-images.githubusercontent.com/77198254/113348389-3f2edf00-9382-11eb-96a3-427445d49d45.PNG)

Here's the test.

[cgb_sound.zip](https://github.com/mgba-emu/mgba/files/6246270/cgb_sound.zip)

**Comment by endrift** [comment] 2021-04-01 20:11
Duplicate of #1334, although it appears to have gotten worse in the meantime.

**Closed by endrift** 2021-04-01 20:11 UTC
