### ISSUE TITLE
Single Pak Link Broken

### ISSUE THREAD

**Issue by wildgoosespeeder** [mgba-emu/mgba#425] opened 2016-10-04 06:41 UTC
In mGBA 0.5.0, any game that supports single pak links is broken during transmission. Tried it with SMA4 and the F-Zero games. Multi pak links are fine.
- Windows 8.1 Pro 64-bit
- Intel Core i5-3210M @ 2.5 Ghz
- 12GB RAM

To allow for single pak mode, you need the GBA BIOS enabled. When the animation is playing, press start+select.

**Comment by endrift** [comment] 2016-10-04 06:43
Known issue. It's a problem with Normal SIO mode.

**Comment by wildgoosespeeder** [comment] 2016-10-04 06:44
Enhancement? Isn't this a bug?

**Comment by endrift** [comment] 2016-10-04 06:44
It's an unimplemented feature.

**Comment by wildgoosespeeder** [comment] 2016-10-04 06:45
But it attempts to run but fails. Seems like a bug to me.

**Comment by endrift** [comment] 2016-10-04 06:45
The reason it fails is because the hardware transmission mode it uses isn't implemented. That's not a bug, it's an unimplemented feature.

**Comment by wildgoosespeeder** [comment] 2016-10-04 06:49
Do you have any idea how to write it? NO$GBA emulates properly if it is open source if you don't know how.

**Comment by endrift** [comment] 2016-10-04 06:51
I had a half-working implementation previously, but I removed it due to it not working fully and breaking some other stuff. I'll put it back and get it working fully later.

Also NO$GBA is not open source, and please don't doubt whether or not I can implement a feature. I wrote the whole emulator basically by myself.

**Comment by wildgoosespeeder** [comment] 2016-10-04 06:54
I wasn't doubting you. Thought I could save you some time, if at all possible. Turns out I can't because NO$GBA is not open source (bummer).

**Comment by endrift** [comment] 2016-10-04 06:56
Ah, sorry, it came off a bit harsher than you'd meant it then. There's documentation out there of how it works, but for some reason it would bail out after transferring about 1/4 of the data, and I never got around to debugging it. It was a low priority for me due to the fact that single pak isn't really as useful in emulators as it is on hardware.

**Comment by Testsr** [comment] 2020-03-05 22:27
Is the Normal SIO mode still unimplemented? If so, I would work on it.

**Comment by endrift** [comment] 2020-03-05 22:30
What do you mean "still"? It's been implemented for ages, it's just kinda broken due to how I sync multiple cores.

**Comment by Testsr** [comment] 2020-03-05 23:00
The last update on this thread had the normal SIO not done.
I think the solution to Single Pak Play is to get SWI 25h implemented. 
See https://www.akkit.org/info/gbatek.htm#biosmultibootsinglegamepak

**Comment by endrift** [comment] 2020-03-05 23:01
You're wrong. The problem is that normal mode is broken (even if it is implemented). SWI 0x25 isn't used.

**Comment by Testsr** [comment] 2020-03-05 23:34
The normal mode you are talking about only supports two GBAs, right?

**Comment by Testsr** [comment] 2020-03-06 00:51
Apparently, SIO MultiPlayer mode is generally used for the data transfer, not Normal Mode.

**Comment by Testsr** [comment] 2020-03-06 01:45
I tested the newest Master build on with a gba bios. 
Opened up Sonic Advance 3 in one mGBA multiplayer window and booted the bios in the second multiplayer window.  When Single Pak mode was selected on the Battle screen,the windows connected successfully, but after that the roms errored out.

**Comment by endrift** [comment] 2020-03-06 01:51
Yes, because (as I said) normal mode is currently broken.

**Comment by Testsr** [comment] 2020-03-06 01:55
Yes, but I don't think the games use Normal Mode for transferring data.

**Comment by endrift** [comment] 2020-03-06 01:59
Having debugged this only a few days ago, you're again wrong. Normal mode is used for game upload (though in-game communication is done through multiplayer mode).

**Comment by Testsr** [comment] 2020-03-06 02:03
Ok, you are correct.

**Comment by Testsr** [comment] 2020-03-06 02:44
Can I help you in getting normal mode to be less broken?

**Comment by Testsr** [comment] 2020-03-06 04:48
BTW,the first block is sent but not received. Then a CRC check is preformed.

**Comment by Testsr** [comment] 2020-03-06 06:25
By the way, what are the problems with Normal mode Transfer?

**Comment by endrift** [comment] 2020-03-06 08:58
As I said already, the way I sync multiple cores is fragile and it's not compatible with normal mode at the moment. It would take some heavy revamping of this sync code to fix, which admittedly I've been talking about doing anyway.

**Comment by Testsr** [comment] 2020-03-06 10:00
I hope the  this sync code revamp gets done soon. I am sorry for being foolish about things I did not know. Can I help you with anything?

**Comment by endrift** [comment] 2020-09-08 05:47
I forgot to comment on this after I did it, but I did [some work](c6ca0d25c01f1b65a2d90636e5b550eee27a545e) on Normal Mode a month ago, but this issue still doesn't appear to be resolved. Further investigation is still needed.

**Comment by Testsr** [comment] 2020-11-05 07:46
Have you done any further investigations? Unpatching #1642 on my fork of the latest master, and playing Sonic Advance 2 reveals that the data is being transfered but there seems to be no stopping condition.

**Closed** 2021-02-13 12:06 UTC
Labels: platform:GBA, severity:enhancement
