### ISSUE TITLE
Garbled Graphics due to bad transparency, bad audio in Famicom Mini - Vol. 22 - Nazo no Murasamejou

### ISSUE THREAD

**Issue by codebase7** [mgba-emu/mgba#194] opened 2015-12-29 00:41 UTC
The game runs but produces a completely white title screen. Continuing to the main menu we get a whited out background which renders the white text unreadable. Going in game is possible and quite playable (assuming you manage to navigate the name entry screen) but does not draw the scenery nor the text on the status bar. After doing some fiddling with the video buffer options, it seems that the game is not handling transparency on the sprites buffer correctly as the missing graphics are on background 3 but obscured by the sprites buffer.

The sound is working but has instances (about once every 5 to 10 seconds) where the audio glitches out for a few seconds before returning to normal. (This can produce bleeding ears noise, so it's probably buffer corruption....)

mGBA Version: 0.3.2 Branch: heads/0.3.2 Revision: 30220a3c4bdb47db679517150b2b849ebaae463c
OS: Windows 7 64bit

Main menu:
![mainmenu_gamescreen](https://cloud.githubusercontent.com/assets/4889398/12027769/140e74f8-ad9a-11e5-9447-0a93dba47dab.png)

Main menu log screen:
![mainmenu_logscreen](https://cloud.githubusercontent.com/assets/4889398/12027771/1d718fda-ad9a-11e5-952f-f682127903f1.png)

In game with Obj buffer disabled:
![ingame_gamescreen_obj_disabled](https://cloud.githubusercontent.com/assets/4889398/12027773/2c61cc58-ad9a-11e5-9700-749a1d1ef430.png)

In game with Obj buffer enabled:
![ingame_gamescreen_obj_enabled](https://cloud.githubusercontent.com/assets/4889398/12027774/304b8f48-ad9a-11e5-8be4-ab15f299995b.png)

In game log screen:
![ingame_logscreen](https://cloud.githubusercontent.com/assets/4889398/12027777/343cc78e-ad9a-11e5-8ab6-83426390cb0a.png)

**Comment by endrift** [comment] 2015-12-29 03:54
Hmm, need to test this on hardware to see what's actually going on, but it looks like it's setting a sprite to be transformed and then using a zero matrix for the transformation. Which is bad. Not sure what the expected behavior here is for such a case.

**Comment by endrift** [comment] 2016-01-04 09:16
I can't reproduce the audio corruption in master, but the video issues are fixed in bfd73a793def72f49243a9566526c6904593336b. Turns out I had an unimplemented feature that was breaking it.

**Closed by endrift** 2016-01-04 09:16 UTC
Labels: minor bug

**Comment by taisel** [comment] 2016-01-04 10:34
Wondering if this was a poorly coded rom or an intentional anti-piracy technique.

**Comment by endrift** [comment] 2016-01-05 04:24
It looks super intentional. They drew 8 large sprites offscreen per scan line and then covered the entire screen with sprites, using a very specific rotation value. It might be another antiemulation technique.
