### ISSUE TITLE
Top Gear Rally glitch

### ISSUE THREAD

**Issue by Tasosgemah** [mgba-emu/mgba#489] opened 2017-01-03 22:24 UTC
In Top Gear Rally, the car (and some UI elements) disappear. Every now and then they re-appear for a second and they disappear again. 

Tested on 0.5.1 and 0.5.2.

**Comment by endrift** [comment] 2017-01-03 22:24
Dupe of #485. Use a nightly.

**Closed by endrift** 2017-01-03 22:24 UTC
