### ISSUE TITLE
Overrides don't apply if window is closed

### ISSUE THREAD

**Issue by rweichler** [mgba-emu/mgba#445] opened 2016-10-15 21:57 UTC
# With no ROM loaded

![screen shot 2016-10-15 at 2 49 50 pm](https://cloud.githubusercontent.com/assets/1661613/19413595/bffac1c2-92e6-11e6-9f04-9749a621c731.png)
- Save option is not selectable, even after changing settings
# With a ROM loaded

![screen shot 2016-10-15 at 2 49 35 pm](https://cloud.githubusercontent.com/assets/1661613/19413599/d2385fb6-92e6-11e6-9bc5-91b152aad7ee.png)
- Save option is selectable for some reason?

**Comment by endrift** [comment] 2016-10-16 08:40
This is working as intended. The overrides are for the next game to be loaded, so it won't know what the override will apply to until it's loaded; hence, it can't save it while a game isn't loaded.

**Comment by rweichler** [comment] 2016-10-16 19:54
@endrift it isn't though. For example, with no ROM loaded, I disabled Autodetect and turned on Realtime clock, then pressed close.

Then, I loaded FireRed (SHA1: `41cb23d8dccc8ebd7c649cd8fbb58eeace6e2fdc`), and the patch for [Liquid Crystal](http://romhackersonline.com/livebeta/lc/builds/PKMNLC-3.3.00512.ips). The realtime clock was disabled.

**Comment by endrift** [comment] 2016-10-16 20:02
Don't close the window. The overrides don't apply if the window is closed. This is a known issue that I didn't get around to fixing before 0.5.

**Comment by rweichler** [comment] 2016-10-16 20:03
Oh, I see. Thank you.

**Comment by rweichler** [comment] 2016-10-16 20:07
@endrift: Still doesn't work. I kept the window open, but when loading FireRed it unchecks "Realtime clock".

Before loading ROM:
![image](https://cloud.githubusercontent.com/assets/1661613/19420496/6c06f19c-93a1-11e6-9858-696fbc6070de.png)

After loading ROM:
![image](https://cloud.githubusercontent.com/assets/1661613/19420499/7d44eefa-93a1-11e6-8b36-202645c66cf2.png)

**Comment by endrift** [comment] 2016-10-16 20:14
Hmm, I can confirm this. Let me take a closer look.

**Comment by rweichler** [comment] 2016-10-16 20:21
Alright.... something really weird is going on. I changed this on line 255 of `src/gba/core.c`:

```c
    struct GBACartridgeOverride override;
    const struct GBACartridge* cart = (const struct GBACartridge*) gba->memory.rom;
    if (cart) {
        memcpy(override.id, &cart->id, sizeof(override.id));
        if (GBAOverrideFind(gbacore->overrides, &override)) {
            GBAOverrideApply(gba, &override);
        }
        GBAHardwareInitRTC(&gba->memory.hw); // new code
    }
```

And the realtime clock *still* doesn't work! :/ Any ideas?

**Comment by endrift** [comment] 2016-10-16 20:31
Manual override setting is fixed in 250c19b91c738716e981d52f4fb1edd8b6c16a51. But Liquid Crystal is still unhappy, despite the RTC being now actually present, and I don't know why. I've been told that it works on the ports though, so I'm not sure.

**Comment by rweichler** [comment] 2016-10-16 20:47
Thanks! I guess I'll try Shiny Gold, then.

**Comment by endrift** [comment] 2017-09-21 05:46
This should be fixed by now.

**Closed by endrift** 2017-09-21 05:46 UTC
Labels: feature:usability, port:Qt, severity:minor bug
