### ISSUE TITLE
[Request] Allow binding inputs to more than one button

### ISSUE THREAD

**Issue by ROMaster2** [mgba-emu/mgba#157] opened 2015-11-08 23:02 UTC
Since the average player is likely to have more than two main buttons on their controller, it'd be nice to be able to bind R and L to both the shoulder buttons and the X and Y. For now this can be worked around with Joy2Key, but an internal solution would be cool.

**Comment by endrift** [comment] 2015-11-08 23:03
Dupe of #87.

**Closed by endrift** 2015-11-08 23:03 UTC
