### ISSUE TITLE
mGBA-0.10.3-wii black screen

### ISSUE THREAD

**Issue by svk-gif** [mgba-emu/mgba#3316] opened 2024-10-15 08:30 UTC
When booting "mGBA-0.10.3-wii" for the Wii it just crashes/black screen.

vWii on WiiU

**Comment by endrift** [comment] 2024-10-15 08:31
Duplicate of https://github.com/mgba-emu/mgba/issues/3106, fixed in dev months ago. Use a dev build for now. 0.10.4 should be coming out soon.

**Closed by endrift** 2024-10-15 08:31 UTC
