### ISSUE TITLE
White screen on 2Ds and screen is halfway cut off

### ISSUE THREAD

**Issue by Caffinat** [mgba-emu/mgba#2216] opened 2021-06-12 18:56 UTC
I homebrewed my ds and downloaded this I installed pokemon fire red and when I go into it I see a write screen with unimportant text at the bottom I click around and when I Click on the shoulder buttons I hear a weird sound, so then I open it with the app and the screen is halfway off screen to where I can only soo the left side of the screen any suggestions

**Comment by endrift** [comment] 2021-06-19 04:18
I don't know what this white screen or unimportant text you're talking about is, but the cut off top screen is a duplicate of #2167, which is fixed and will work in 0.9.2 when that comes out.

**Comment by endrift** [comment] 2021-07-11 05:42
Please retest in 0.9.2, which just came out.

**Comment by endrift** [comment] 2021-07-25 00:27
Closing due to lack of reply.

**Closed by endrift** 2021-07-25 00:27 UTC
Labels: blocked:needs retest
