### ISSUE TITLE
Full screen exclusive mode

### ISSUE THREAD

**Issue by Hexaae** [mgba-emu/mgba#2142] opened 2021-04-24 10:50 UTC
Please, can you add Full Screen **Exclusive** mode for improved smoothness (G-Sync'ed screens etc.)?
Current full screen seems just a full window borderless mode.

Windows 10 20H2, 1070 8GB, NVidia 462.31, G-Sync screen.

**Comment by endrift** [comment] 2021-04-26 00:09
Duplicate of #884.

**Closed by endrift** 2021-04-26 00:09 UTC
