### ISSUE TITLE
Trading in Pokemon Red & Blue

### ISSUE THREAD

**Issue by MrJaguarIsTheBest** [mgba-emu/mgba#2417] opened 2022-01-10 02:12 UTC
I am trying to trade in Pokemon Red and Blue. When I go to the trading spot, the 2nd Game(The One I opened on multiplayer window) freezes midway in talking to the lady. When I talk to the lady in the first game she says I need a friend.

**Comment by endrift** [comment] 2022-01-19 11:28
Duplicate of #2390.

**Closed by endrift** 2022-01-19 11:28 UTC
