### ISSUE TITLE
[Feature Request] Option to accept keyboard inputs when window is not in focus

### ISSUE THREAD

**Issue by sebmal1337** [mgba-emu/mgba#3216] opened 2024-05-28 01:21 UTC
Hi! Love the emulator and I was wondering if it'd be possible to have an option to have it recognize keyboard inputs when the window isn't in focus (Bizhawk has this as a checkbox, for example). Currently it does this for controller inputs which is great, but I'm using mGBA for a dumb stream gimmick where I need it to hit the load state key right after opening, and every so often for seemingly no reason the window doesn't properly stay in focus and it throws the whole thing off. Extremely niche use case so probably low priority I know lol, but it'd be a ton of help for me if the emulator supported this! Thanks!

**Comment by endrift** [comment] 2024-05-28 01:26
Duplicate of #1378

Unfortunately I'm not really sure if it's possible with the toolkit I'm using for keyboard input.

**Closed by endrift** 2024-05-28 01:26 UTC
