### ISSUE TITLE
Real Time clock not staying on the specified time

### ISSUE THREAD

**Issue by PencilAmazing** [mgba-emu/mgba#828] opened 2017-07-27 14:53 UTC
Windows 10 Home edition Version 1703. mGBA 0.6.0. Going to Game Pak Sensors, choosing any of the clock options then pressing "now" doesn't set the in game clock at all. Exit the menu then return, and it will reset back to 10:00:00 PM 12/31/99. Exiting and relaunching the emulator doesn't help at all.

**Comment by endrift** [comment] 2017-07-30 04:42
Seems to work for me on 0.6.0, although it is broken in master.

**Comment by endrift** [comment] 2017-08-03 21:52
It's been fixed in master by the way. Please verify that it works or that there is a usability concern I need to address.

**Comment by bdp1312** [comment] 2018-07-11 23:29
I am having a nearly identical issue to the one described by the OP. Except my rtc resets to January 1, 2000, 12am. I'm using Windows 10 home, version 1803 and MGBA 0.6.3.

**Comment by endrift** [comment] 2018-07-11 23:30
What game?

**Comment by bdp1312** [comment] 2018-07-16 23:09
Pokemon emerald

**Comment by endrift** [comment] 2021-03-14 08:25
I don't seem to be able to reproduce this with mGBA 0.8.4 on Windows 10. Please retest, and if it still reproduces, give details reproduction instructions.

**Comment by endrift** [comment] 2021-04-18 00:05
Closing due to lack of reply. Please open a new bug if it comes up again.

**Closed by endrift** 2021-04-18 00:05 UTC
Labels: blocked:needs retest, port:Qt, severity:minor bug
